from typing import Literal

class AesGcmBox:
    MAGIC: bytes
    AAD: bytes
    def __init__(self, *, key: bytes | None = None, password: str | None = None, kdf: Literal['scrypt'] = 'scrypt', scrypt_n: int = ..., scrypt_r: int = 8, scrypt_p: int = 1, salt: bytes | None = None) -> None: ...
    @staticmethod
    def is_encrypted(blob: bytes) -> bool: ...
    def encrypt(self, plaintext: bytes) -> bytes: ...
    def decrypt(self, blob: bytes) -> bytes: ...
