"""
Request models for the Clappia API.
"""

# Import from app_definition
# Import from analytics
from .analytics import (
    BaseUpsertChartRequest,
    UpsertBarChartDefinitionRequest,
    UpsertDataTableChartDefinitionRequest,
    UpsertDoughnutChartDefinitionRequest,
    UpsertGanttChartDefinitionRequest,
    UpsertLineChartDefinitionRequest,
    UpsertMapChartDefinitionRequest,
    UpsertPieChartDefinitionRequest,
    UpsertSummaryChartDefinitionRequest,
)
from .app_definition import (
    AddPageBreakRequest,
    BaseUpsertFieldRequest,
    UpdateAppMetadataRequest,
    UpdatePageBreakRequest,
    UpsertFieldAddressRequest,
    UpsertFieldAIRequest,
    UpsertFieldButtonRequest,
    UpsertFieldCheckboxRequest,
    UpsertFieldCodeReaderRequest,
    UpsertFieldCodeRequest,
    UpsertFieldCounterRequest,
    UpsertFieldDatabaseRequest,
    UpsertFieldDateRequest,
    UpsertFieldDependencyAppRequest,
    UpsertFieldDropdownRequest,
    UpsertFieldEazypayPaymentGatewayRequest,
    UpsertFieldEmailInputRequest,
    UpsertFieldEmojiRequest,
    UpsertFieldFileRequest,
    UpsertFieldFormulaRequest,
    UpsertFieldGpsLocationRequest,
    UpsertFieldImageViewerRequest,
    UpsertFieldLiveTrackingRequest,
    UpsertFieldManualAddressRequest,
    UpsertFieldNfcReaderRequest,
    UpsertFieldNumberInputRequest,
    UpsertFieldPaymentGatewayRequest,
    UpsertFieldPaypalPaymentGatewayRequest,
    UpsertFieldPdfViewerRequest,
    UpsertFieldPhoneNumberRequest,
    UpsertFieldProgressBarRequest,
    UpsertFieldRadioRequest,
    UpsertFieldRangeRequest,
    UpsertFieldRazorpayPaymentGatewayRequest,
    UpsertFieldReadOnlyFileRequest,
    UpsertFieldReadOnlyTextRequest,
    UpsertFieldRestApiRequest,
    UpsertFieldRichTextEditorRequest,
    UpsertFieldSignatureRequest,
    UpsertFieldSliderRequest,
    UpsertFieldStripePaymentGatewayRequest,
    UpsertFieldTagsRequest,
    UpsertFieldTextAreaRequest,
    UpsertFieldTextRequest,
    UpsertFieldTimeRequest,
    UpsertFieldToggleRequest,
    UpsertFieldUniqueSequentialRequest,
    UpsertFieldUrlInputRequest,
    UpsertFieldValidationRequest,
    UpsertFieldVideoViewerRequest,
    UpsertFieldVoiceRequest,
    UpsertSectionRequest,
)

# Import from submission
from .submission import (
    CreateSubmissionRequest,
    EditSubmissionRequest,
    GetSubmissionRequest,
    GetSubmissionsAggregationRequest,
    GetSubmissionsCountRequest,
    GetSubmissionsInExcelRequest,
    GetSubmissionsRequest,
    UpdateSubmissionOwnersRequest,
    UpdateSubmissionStatusRequest,
)

# Import from workflow
from .workflow import (
    BaseUpsertWorkflowStepRequest,
    UpsertAiWorkflowStepRequest,
    UpsertApprovalWorkflowStepRequest,
    UpsertCodeWorkflowStepRequest,
    UpsertConditionWorkflowStepRequest,
    UpsertCreateSubmissionWorkflowStepRequest,
    UpsertDatabaseWorkflowStepRequest,
    UpsertDeleteSubmissionWorkflowStepRequest,
    UpsertEditSubmissionWorkflowStepRequest,
    UpsertEmailWorkflowStepRequest,
    UpsertFindSubmissionWorkflowStepRequest,
    UpsertLoopWorkflowStepRequest,
    UpsertMobileNotificationWorkflowStepRequest,
    UpsertRestApiWorkflowStepRequest,
    UpsertSlackWorkflowStepRequest,
    UpsertSmsWorkflowStepRequest,
    UpsertWaitWorkflowStepRequest,
    UpsertWhatsAppWorkflowStepRequest,
)

# Import from workplace
from .workplace import (
    AddUserToAppRequest,
    AddUserToWorkplaceRequest,
    BaseWorkplaceRequest,
    UpdateWorkplaceUserAttributesRequest,
    UpdateWorkplaceUserDetailsRequest,
)

__all__ = [
    # App Definition
    "AddPageBreakRequest",
    # Workplace
    "AddUserToAppRequest",
    "AddUserToWorkplaceRequest",
    # Analytics
    "BaseUpsertChartRequest",
    "BaseUpsertFieldRequest",
    # Workflow
    "BaseUpsertWorkflowStepRequest",
    "BaseWorkplaceRequest",
    # Submission
    "CreateSubmissionRequest",
    "EditSubmissionRequest",
    "GetSubmissionRequest",
    "GetSubmissionsAggregationRequest",
    "GetSubmissionsCountRequest",
    "GetSubmissionsInExcelRequest",
    "GetSubmissionsRequest",
    "UpdateAppMetadataRequest",
    "UpdatePageBreakRequest",
    "UpdateSubmissionOwnersRequest",
    "UpdateSubmissionStatusRequest",
    "UpdateWorkplaceUserAttributesRequest",
    "UpdateWorkplaceUserDetailsRequest",
    "UpsertAiWorkflowStepRequest",
    "UpsertApprovalWorkflowStepRequest",
    "UpsertBarChartDefinitionRequest",
    "UpsertCodeWorkflowStepRequest",
    "UpsertConditionWorkflowStepRequest",
    "UpsertCreateSubmissionWorkflowStepRequest",
    "UpsertDataTableChartDefinitionRequest",
    "UpsertDatabaseWorkflowStepRequest",
    "UpsertDeleteSubmissionWorkflowStepRequest",
    "UpsertDoughnutChartDefinitionRequest",
    "UpsertEditSubmissionWorkflowStepRequest",
    "UpsertEmailWorkflowStepRequest",
    "UpsertFieldAIRequest",
    "UpsertFieldAddressRequest",
    "UpsertFieldButtonRequest",
    "UpsertFieldCheckboxRequest",
    "UpsertFieldCodeReaderRequest",
    "UpsertFieldCodeRequest",
    "UpsertFieldCounterRequest",
    "UpsertFieldDatabaseRequest",
    "UpsertFieldDateRequest",
    "UpsertFieldDependencyAppRequest",
    "UpsertFieldDropdownRequest",
    "UpsertFieldEazypayPaymentGatewayRequest",
    "UpsertFieldEmailInputRequest",
    "UpsertFieldEmojiRequest",
    "UpsertFieldFileRequest",
    "UpsertFieldFormulaRequest",
    "UpsertFieldGpsLocationRequest",
    "UpsertFieldImageViewerRequest",
    "UpsertFieldLiveTrackingRequest",
    "UpsertFieldManualAddressRequest",
    "UpsertFieldNfcReaderRequest",
    "UpsertFieldNumberInputRequest",
    "UpsertFieldPaymentGatewayRequest",
    "UpsertFieldPaypalPaymentGatewayRequest",
    "UpsertFieldPdfViewerRequest",
    "UpsertFieldPhoneNumberRequest",
    "UpsertFieldProgressBarRequest",
    "UpsertFieldRadioRequest",
    "UpsertFieldRangeRequest",
    "UpsertFieldRazorpayPaymentGatewayRequest",
    "UpsertFieldReadOnlyFileRequest",
    "UpsertFieldReadOnlyTextRequest",
    "UpsertFieldRestApiRequest",
    "UpsertFieldRichTextEditorRequest",
    "UpsertFieldSignatureRequest",
    "UpsertFieldSliderRequest",
    "UpsertFieldStripePaymentGatewayRequest",
    "UpsertFieldTagsRequest",
    "UpsertFieldTextAreaRequest",
    "UpsertFieldTextRequest",
    "UpsertFieldTimeRequest",
    "UpsertFieldToggleRequest",
    "UpsertFieldUniqueSequentialRequest",
    "UpsertFieldUrlInputRequest",
    "UpsertFieldValidationRequest",
    "UpsertFieldVideoViewerRequest",
    "UpsertFieldVoiceRequest",
    "UpsertFindSubmissionWorkflowStepRequest",
    "UpsertGanttChartDefinitionRequest",
    "UpsertLineChartDefinitionRequest",
    "UpsertLoopWorkflowStepRequest",
    "UpsertMapChartDefinitionRequest",
    "UpsertMobileNotificationWorkflowStepRequest",
    "UpsertPieChartDefinitionRequest",
    "UpsertRestApiWorkflowStepRequest",
    "UpsertSectionRequest",
    "UpsertSlackWorkflowStepRequest",
    "UpsertSmsWorkflowStepRequest",
    "UpsertSummaryChartDefinitionRequest",
    "UpsertWaitWorkflowStepRequest",
    "UpsertWhatsAppWorkflowStepRequest",
]
