"""Constants for RIFF format."""

RIFF_HEADER_SIZE = 12
RIFF_CHUNK_ID_SIZE = 4
RIFF_WAVE_FORMAT_POSITION = 8
RIFF_MIN_DATA_SIZE_FOR_ID3V2 = 10
RIFF_INFO_CHUNK_MIN_SIZE = 16
RIFF_MIN_VERSION_LENGTH = 3
RIFF_AUDIO_FORMAT_IEEE_FLOAT = 3
RIFF_FORMAT_CHUNK_MIN_SIZE = 16

# BWF bext chunk constants
BEXT_MIN_CHUNK_SIZE = 602  # 256+32+32+10+8+8+2+64+190
BEXT_ORIGINATION_DATE_SIZE = 10
BEXT_ORIGINATION_TIME_SIZE = 8
BEXT_LOUDNESS_METADATA_SIZE = 10  # 5 fields * 2 bytes each
BWF_V2_VERSION = 2
