# src/serger/__init__.py

"""Serger — Stitch your module into a single file.

Full developer API
==================
This package re-exports all non-private symbols from its submodules,
making it suitable for programmatic use, custom integrations, or plugins.
Anything prefixed with "_" is considered internal and may change.

Highlights:
    - main()              → CLI entrypoint
    - run_build()         → Execute a build configuration
    - resolve_config()    → Merge CLI args with config files
    - get_metadata()      → Retrieve version / commit info
"""

from .actions import get_metadata, watch_for_changes
from .build import (
    collect_included_files,
    expand_include_pattern,
    find_package_root,
    resolve_order_paths,
    run_build,
)
from .cli import HintingArgumentParser, main
from .config import (
    DRYRUN_KEYS,
    DRYRUN_MSG,
    FIELD_EXAMPLES,
    ROOT_ONLY_KEYS,
    ROOT_ONLY_MSG,
    CommentsMode,
    DocstringMode,
    DocstringModeLocation,
    DocstringModeSimple,
    ExternalImportMode,
    IncludeConfig,
    IncludeResolved,
    InternalImportMode,
    MainMode,
    MetaBuildConfigResolved,
    ModuleActionAffects,
    ModuleActionCleanup,
    ModuleActionFull,
    ModuleActionMode,
    ModuleActions,
    ModuleActionScope,
    ModuleActionSimple,
    ModuleActionType,
    ModuleMode,
    OriginType,
    PathResolved,
    PostCategoryConfig,
    PostCategoryConfigResolved,
    PostProcessingConfig,
    PostProcessingConfigResolved,
    PyprojectMetadata,
    RootConfig,
    RootConfigResolved,
    SchemaErrorAggregator,
    ShimSetting,
    StitchMode,
    ToolConfig,
    ToolConfigResolved,
    ValidationSummary,
    can_run_configless,
    extract_pyproject_metadata,
    find_config,
    load_and_validate_config,
    load_config,
    parse_config,
    resolve_build_config,
    resolve_config,
    resolve_post_processing,
    validate_config,
)
from .constants import (
    BUILD_TIMESTAMP_PLACEHOLDER,
    BUILD_TOOL_FIND_MAX_LINES,
    DEFAULT_CATEGORIES,
    DEFAULT_CATEGORY_ORDER,
    DEFAULT_COMMENTS_MODE,
    DEFAULT_DISABLE_BUILD_TIMESTAMP,
    DEFAULT_DOCSTRING_MODE,
    DEFAULT_DRY_RUN,
    DEFAULT_ENV_DISABLE_BUILD_TIMESTAMP,
    DEFAULT_ENV_LOG_LEVEL,
    DEFAULT_ENV_RESPECT_GITIGNORE,
    DEFAULT_ENV_WATCH_INTERVAL,
    DEFAULT_EXTERNAL_IMPORTS,
    DEFAULT_INTERNAL_IMPORTS,
    DEFAULT_LICENSE_FALLBACK,
    DEFAULT_LOG_LEVEL,
    DEFAULT_MAIN_MODE,
    DEFAULT_MAIN_NAME,
    DEFAULT_MODULE_MODE,
    DEFAULT_OUT_DIR,
    DEFAULT_RESPECT_GITIGNORE,
    DEFAULT_SHIM,
    DEFAULT_SOURCE_BASES,
    DEFAULT_STITCH_MODE,
    DEFAULT_STRICT_CONFIG,
    DEFAULT_USE_PYPROJECT_METADATA,
    DEFAULT_WATCH_INTERVAL,
    RUNTIME_MODES,
)
from .logs import AppLogger, getAppLogger
from .main_config import (
    FunctionCollision,
    MainBlock,
    detect_collisions,
    detect_function_parameters,
    detect_main_blocks,
    find_main_function,
    generate_auto_renames,
    parse_main_name,
    rename_function_in_source,
    select_main_block,
)
from .meta import (
    DESCRIPTION,
    PROGRAM_CONFIG,
    PROGRAM_DISPLAY,
    PROGRAM_ENV,
    PROGRAM_PACKAGE,
    PROGRAM_SCRIPT,
    Metadata,
)
from .module_actions import (
    apply_cleanup_behavior,
    apply_module_actions,
    apply_single_action,
    check_shim_stitching_mismatches,
    extract_module_name_from_source_path,
    generate_actions_from_mode,
    get_deleted_modules_from_actions,
    separate_actions_by_affects,
    set_mode_generated_action_defaults,
    validate_action_dest,
    validate_action_source_exists,
    validate_module_actions,
    validate_no_circular_moves,
    validate_no_conflicting_operations,
    validate_rename_action,
)
from .selftest import run_selftest
from .stitch import (
    ModuleSymbols,
    compute_module_order,
    detect_name_collisions,
    extract_commit,
    extract_version,
    force_mtime_advance,
    is_serger_build,
    process_comments,
    process_docstrings,
    split_imports,
    stitch_modules,
    strip_redundant_blocks,
    suggest_order_mismatch,
    verify_all_modules_listed,
    verify_no_broken_imports,
)
from .utils import (
    derive_module_name,
    discover_installed_packages_roots,
    is_excluded,
    make_includeresolved,
    make_pathresolved,
    shorten_path_for_display,
    shorten_paths_for_display,
    validate_required_keys,
)
from .verify_script import (
    build_tool_command,
    execute_post_processing,
    find_tool_executable,
    post_stitch_processing,
    verify_compiles,
    verify_compiles_string,
    verify_executes,
)


__all__ = [  # noqa: RUF022
    # actions
    "get_metadata",
    "watch_for_changes",
    # build
    "collect_included_files",
    "expand_include_pattern",
    "find_package_root",
    "resolve_order_paths",
    "run_build",
    # cli
    "HintingArgumentParser",
    "main",
    # config
    "CommentsMode",
    "DocstringMode",
    "DocstringModeLocation",
    "DocstringModeSimple",
    "DRYRUN_KEYS",
    "DRYRUN_MSG",
    "ExternalImportMode",
    "FIELD_EXAMPLES",
    "IncludeConfig",
    "IncludeResolved",
    "InternalImportMode",
    "MainMode",
    "MetaBuildConfigResolved",
    "ModuleActionAffects",
    "ModuleActionCleanup",
    "ModuleActionFull",
    "ModuleActionMode",
    "ModuleActionScope",
    "ModuleActionSimple",
    "ModuleActionType",
    "ModuleActions",
    "ModuleMode",
    "OriginType",
    "PathResolved",
    "PostCategoryConfig",
    "PostCategoryConfigResolved",
    "PostProcessingConfig",
    "PostProcessingConfigResolved",
    "PyprojectMetadata",
    "ROOT_ONLY_KEYS",
    "ROOT_ONLY_MSG",
    "RootConfig",
    "RootConfigResolved",
    "SchemaErrorAggregator",
    "ShimSetting",
    "StitchMode",
    "ToolConfig",
    "ToolConfigResolved",
    "ValidationSummary",
    "can_run_configless",
    "extract_pyproject_metadata",
    "find_config",
    "load_and_validate_config",
    "load_config",
    "parse_config",
    "resolve_build_config",
    "resolve_config",
    "resolve_post_processing",
    "validate_config",
    # constants
    "BUILD_TIMESTAMP_PLACEHOLDER",
    "BUILD_TOOL_FIND_MAX_LINES",
    "DEFAULT_CATEGORIES",
    "DEFAULT_CATEGORY_ORDER",
    "DEFAULT_COMMENTS_MODE",
    "DEFAULT_DISABLE_BUILD_TIMESTAMP",
    "DEFAULT_DOCSTRING_MODE",
    "DEFAULT_DRY_RUN",
    "DEFAULT_ENV_DISABLE_BUILD_TIMESTAMP",
    "DEFAULT_ENV_LOG_LEVEL",
    "DEFAULT_ENV_RESPECT_GITIGNORE",
    "DEFAULT_ENV_WATCH_INTERVAL",
    "DEFAULT_EXTERNAL_IMPORTS",
    "DEFAULT_INTERNAL_IMPORTS",
    "DEFAULT_LICENSE_FALLBACK",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_MAIN_MODE",
    "DEFAULT_MAIN_NAME",
    "DEFAULT_MODULE_MODE",
    "DEFAULT_OUT_DIR",
    "DEFAULT_RESPECT_GITIGNORE",
    "DEFAULT_SHIM",
    "DEFAULT_SOURCE_BASES",
    "DEFAULT_STITCH_MODE",
    "DEFAULT_STRICT_CONFIG",
    "DEFAULT_USE_PYPROJECT_METADATA",
    "DEFAULT_WATCH_INTERVAL",
    "RUNTIME_MODES",
    # logs
    "AppLogger",
    "getAppLogger",
    # main_config
    "FunctionCollision",
    "MainBlock",
    "detect_collisions",
    "detect_function_parameters",
    "detect_main_blocks",
    "find_main_function",
    "generate_auto_renames",
    "parse_main_name",
    "rename_function_in_source",
    "select_main_block",
    # meta
    "DESCRIPTION",
    "Metadata",
    "PROGRAM_CONFIG",
    "PROGRAM_DISPLAY",
    "PROGRAM_ENV",
    "PROGRAM_PACKAGE",
    "PROGRAM_SCRIPT",
    # module_actions
    "apply_cleanup_behavior",
    "apply_module_actions",
    "apply_single_action",
    "check_shim_stitching_mismatches",
    "extract_module_name_from_source_path",
    "generate_actions_from_mode",
    "get_deleted_modules_from_actions",
    "separate_actions_by_affects",
    "set_mode_generated_action_defaults",
    "validate_action_dest",
    "validate_action_source_exists",
    "validate_module_actions",
    "validate_no_circular_moves",
    "validate_no_conflicting_operations",
    "validate_rename_action",
    # selftest
    "run_selftest",
    # stitch
    "ModuleSymbols",
    "compute_module_order",
    "detect_name_collisions",
    "extract_commit",
    "extract_version",
    "force_mtime_advance",
    "is_serger_build",
    "process_comments",
    "process_docstrings",
    "split_imports",
    "stitch_modules",
    "strip_redundant_blocks",
    "suggest_order_mismatch",
    "verify_all_modules_listed",
    "verify_no_broken_imports",
    # utils
    "derive_module_name",
    "discover_installed_packages_roots",
    "is_excluded",
    "make_includeresolved",
    "make_pathresolved",
    "shorten_path_for_display",
    "shorten_paths_for_display",
    "validate_required_keys",
    # verify_script
    "build_tool_command",
    "execute_post_processing",
    "find_tool_executable",
    "post_stitch_processing",
    "verify_compiles",
    "verify_compiles_string",
    "verify_executes",
]
