# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import alexasomba_paystack
from alexasomba_paystack.models.dedicated_nuban_create_response_data_customer import DedicatedNubanCreateResponseDataCustomer  # noqa: E501
from alexasomba_paystack.rest import ApiException

class TestDedicatedNubanCreateResponseDataCustomer(unittest.TestCase):
    """DedicatedNubanCreateResponseDataCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DedicatedNubanCreateResponseDataCustomer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DedicatedNubanCreateResponseDataCustomer`
        """
        model = alexasomba_paystack.models.dedicated_nuban_create_response_data_customer.DedicatedNubanCreateResponseDataCustomer()  # noqa: E501
        if include_optional :
            return DedicatedNubanCreateResponseDataCustomer(
                id = 56, 
                first_name = '', 
                last_name = '', 
                email = '', 
                customer_code = '', 
                phone = '', 
                metadata = alexasomba_paystack.models.metadata.metadata(), 
                risk_action = '', 
                international_format_phone = ''
            )
        else :
            return DedicatedNubanCreateResponseDataCustomer(
                id = 56,
                first_name = '',
                last_name = '',
                email = '',
                customer_code = '',
                phone = '',
                metadata = alexasomba_paystack.models.metadata.metadata(),
                risk_action = '',
                international_format_phone = '',
        )
        """

    def testDedicatedNubanCreateResponseDataCustomer(self):
        """Test DedicatedNubanCreateResponseDataCustomer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
