# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import alexasomba_paystack
from alexasomba_paystack.models.transaction_totals_response import TransactionTotalsResponse  # noqa: E501
from alexasomba_paystack.rest import ApiException

class TestTransactionTotalsResponse(unittest.TestCase):
    """TransactionTotalsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TransactionTotalsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionTotalsResponse`
        """
        model = alexasomba_paystack.models.transaction_totals_response.TransactionTotalsResponse()  # noqa: E501
        if include_optional :
            return TransactionTotalsResponse(
                status = True, 
                message = '', 
                data = alexasomba_paystack.models.transaction_totals_response_data.TransactionTotalsResponse_data(
                    total_transactions = 56, 
                    total_volume = 56, 
                    total_volume_by_currency = [
                        alexasomba_paystack.models.transaction_total_volume_by_currency_array.TransactionTotalVolumeByCurrencyArray(
                            currency = '', 
                            amount = 56, )
                        ], 
                    pending_transfers = 56, 
                    pending_transfers_by_currency = [
                        alexasomba_paystack.models.transaction_pending_transfers_by_currency_array.TransactionPendingTransfersByCurrencyArray(
                            currency = '', 
                            amount = 56, )
                        ], )
            )
        else :
            return TransactionTotalsResponse(
                status = True,
                message = '',
                data = alexasomba_paystack.models.transaction_totals_response_data.TransactionTotalsResponse_data(
                    total_transactions = 56, 
                    total_volume = 56, 
                    total_volume_by_currency = [
                        alexasomba_paystack.models.transaction_total_volume_by_currency_array.TransactionTotalVolumeByCurrencyArray(
                            currency = '', 
                            amount = 56, )
                        ], 
                    pending_transfers = 56, 
                    pending_transfers_by_currency = [
                        alexasomba_paystack.models.transaction_pending_transfers_by_currency_array.TransactionPendingTransfersByCurrencyArray(
                            currency = '', 
                            amount = 56, )
                        ], ),
        )
        """

    def testTransactionTotalsResponse(self):
        """Test TransactionTotalsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
