
import base64
DATA_B64 = "ewrCoCDCoCDCoCDCoCAib2JqZWN0cyI6IFsKwqAgwqAgwqAgwqAgwqAgwqAgInTDoHUgSFZUTC01NzQiCsKgIMKgIMKgIMKgIF0sCsKgIMKgIMKgIMKgICJwYXNzYWdlIjogIklJLiBWw5lORyBCSeG7gk5cbjIuIFbDuW5nIGJp4buDbiBtaeG7gW4gVHJ1bmcsIFHEkEhTXG5hKSBIb+G6oXQgxJHhu5luZyBj4bunYSBUcnVuZyBRdeG7kWNcbi0gVMOgdSBxdcOibiBz4buxOiAwNyB0w6B1ICh0xINuZyAwMSB0w6B1KSwgdHJvbmcgxJHDszogVMOgdSBRTS03MjYsIHTDoHUgTmFtIFRy4bqvYyA0MjksIDAxIHTDoHUgKGNoxrBhIHLDtSBz4buRIGhp4buHdSwga2nhu4N1IGxv4bqhaSkg4bufIFBow7ogTMOibTsgdMOgdSBIVlRMLTYyMCBCVEIgxJDDoSBC4bqvYyAyOGhsOyAwMSB0w6B1IChjaMawYSByw7Ugc+G7kSBoaeG7h3UsIGtp4buDdSBsb+G6oWkpIOG7nyDEkeG6o28gSG/DoG5nIFNhOyB0w6B1IFRo4buleSBM4bujaSAxMCDhu58gTsSQTiBCw7RuZyBCYXkgNjVobDsgdMOgdSBIVlRMLTU3NCB0aGVvIGTDtWkgdMOgdSBLaHUgdHLhu6VjIERELTExNC9OaOG6rXQgQuG6o24g4bufIMSQxJBCIENhbSBSYW5oIDY1aGwuIiwKwqAgwqAgwqAgwqAgImNvb3JzIjogWwrCoCDCoCDCoCDCoCDCoCDCoCBbCsKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgIDExMC4yMTU1NTIsCsKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgIDEyLjM3ODYzMgrCoCDCoCDCoCDCoCDCoCDCoCBdCsKgIMKgIMKgIMKgIF0sCsKgIMKgIMKgIMKgICJsb2NzIjogWwrCoCDCoCDCoCDCoCDCoCDCoCAixJDEkEIgQ2FtIFJhbmggNjVobCIKwqAgwqAgwqAgwqAgXSwKwqAgwqAgwqAgwqAgIm9iamVjdF9hY3Rpb24iOiAibW9uaXRvcmluZyIsCsKgIMKgIMKgIMKgICJzZXZlcml0eSI6ICJtZWRpdW0iLArCoCDCoCDCoCDCoCAicmVhc29uIjogInTDoHUgSFZUTC01NzQgdGhlbyBkw7VpIHTDoHUgbsaw4bubYyBuZ2/DoGkgdHJvbmcgdsO5bmcgxJHhurdjIHF1eeG7gW4ga2luaCB04bq/IGPhu6dhIFZp4buHdCBOYW0gdOG6oWkgxJDEkEIgQ2FtIFJhbmggNjVobCIKwqAgwqAgfQ=="
def save(filename="code_moi_ve.py"):
    try:
        decoded = base64.b64decode(DATA_B64).decode("utf-8")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(decoded)
        print(f"OK: Da luu code vao {filename}")
    except Exception as e:
        print(f"LOI: {e}")
