from ..Base import *
from ..Proxy import *
from ..AcadObject import *

class AcadUtility(AppObject):
    def __init__(self, obj) -> None: ...
    def AngleFromXAxis(self, Point1: In[PyGePoint3d], Point2: In[PyGePoint3d]) -> float: ...
    def AngleToReal(self, Angle: In[str], Unit: In[AcAngleUnits]) -> float: ...
    def AngleToString(self, Angle: In[float], Unit: In[AcAngleUnits], Precision: In[int]) -> str: ...
    def CreateTypedArray(self, Type: In[VbVarType], Value1, *args): ...
    def DistanceToReal(self, Distance: In[str], Unit: In[AcUnits]) -> float: ...
    def GetAngle(self, Point: In[PyGePoint3d] = None, Prompt: In[str] = '') -> float: ...
    def GetCorner(self, Point: In[PyGePoint3d], Prompt: In[str] = '') -> tuple: ...
    def GetDistance(self, Point: In[PyGePoint3d] = None, Prompt: In[str] = None) -> float: ...
    def GetEntity(self, Prompt: In[str] = '') -> tuple: ...
    def GetInput(self) -> str: ...
    def GetInteger(self, Prompt: In[str] = '') -> int: ...
    def GetKeyword(self, Prompt: In[str] = '') -> str: ...
    def GetObjectIdString(self, acadObject: In[AcadObject], bHex: In[bool]) -> str: ...
    def GetOrientation(self, Point: In[PyGePoint3d], Prompt: In[str] = '') -> float: ...
    def GetPoint(self, Point: In[PyGePoint3d] = None, Prompt: In[str] = '') -> tuple: ...
    def GetReal(self, Prompt: In[str] = '') -> float: ...
    def GetRemoteFile(self, URL: In[str], IgnoreCache: In[bool]) -> None: ...
    def GetString(self, HasSpaces: In[int], Prompt: In[str] = '') -> float: ...
    def GetSubEntity(self, Prompt: In[str] = '') -> tuple: ...
    def InitializeUserInput(self, Bits: In[int], Keyword: In[str] = None) -> None: ...
    def IsRemoteFile(self, LocalFile: In[str], URL: In[str]) -> bool: ...
    def IsURL(self, URL: In[str]) -> bool: ...
    def LaunchBrowserDialog(self, DialogTitle: In[str], OpenButtonCaption: In[str], StartPageURL: In[str], RegistryRootKey: In[str], OpenButtonAlwaysEnabled: In[bool]) -> bool: ...
    def PolarPoint(self, Point: In[PyGePoint3d], Angle: In[float], Distance: In[float]) -> PyGePoint3d: ...
    def Prompt(self, Message: In[str]) -> None: ...
    def PutRemoteFile(self, URL: In[str], LocalFile: In[str]) -> None: ...
    def RealToString(self, Value: In[float], Unit: In[AcUnits], Precision: In[int]) -> str: ...
    def SendModelessOperationEnded(self) -> str: ...
    def SendModelessOperationStart(self, Context: In[str]) -> None: ...
    def TranslateCoordinates(self, Point: In[PyGePoint3d], FromCoordSystem: In[AcCoordinateSystem], ToCoordSystem: In[AcCoordinateSystem], Displacement: In[int], OCSNormal: In[PyGeVector3d] = None) -> tuple: ...

class VbVarType(IntEnum):
    vbBoolean = 11
    vbInteger = 2
    vbLong = 3
    vbSingle = 4
    vbDouble = 5
