from ..Base import *
from ..Proxy import *
from ..AcadObject import *
from .AcadLayout import *

class AcadLayouts(IAcadObjectCollection):
    def __init__(self, obj) -> None: ...
    def Add(self, InsertionPoint: In[PyGePoint3d], Name: In[str]) -> AcadLayout: ...
    def Item(self, Index: In[int]) -> AcadLayout: ...
    def __iter__(self): ...
