from ..Base import *
from ..Proxy import *
from ..AcadObject import IAcadObjectCollection as IAcadObjectCollection
from .AcadDimStyle import AcadDimStyle as AcadDimStyle

class AcadDimStyles(IAcadObjectCollection):
    def __init__(self, obj) -> None: ...
    def Add(self, Name: In[str]) -> AcadDimStyle: ...
    def Item(self, Index: In[int]) -> AcadDimStyle: ...
    def __iter__(self): ...
