from ..Base import *
from ..Proxy import *
from ..AcadObject import *

class AcadSelectionSet(AppObject):
    def __init__(self, obj) -> None: ...
    Application: AcadApplication
    Count: int
    Name: str
    def AddItems(self, Items: In[vObjectArray]) -> None: ...
    def Clear(self) -> None: ...
    def Delete(self) -> None: ...
    def Erase(self) -> None: ...
    def Highlight(self, HighlightFlag: In[bool]) -> None: ...
    def Item(self, Index: In[int | str]) -> AcadObject: ...
    def RemoveItems(self, Objects: In[vObjectArray]) -> None: ...
    def Select(self, Mode: In[AcSelect], Point1: In[PyGePoint3d] = None, Point2: In[PyGePoint3d] = None, FilterType: In[Variant[AdeskDxfCode]] = None, FilterData: In[Variant] = None) -> None: ...
    def SelectAtPoint(self, Point: In[PyGePoint3d], FilterType: In[Variant[AdeskDxfCode]] = None, FilterData: In[Variant] = None) -> None: ...
    def SelectByPolygon(self, Mode: In[AcSelect], PointsList: In[PyGePoint3dArray], FilterType: In[Variant[AdeskDxfCode]] = None, FilterData: In[Variant] = None) -> None: ...
    def SelectOnScreen(self, FilterType: In[Variant[AdeskDxfCode]] = None, FilterData: In[Variant] = None) -> None: ...
    def Update(self) -> None: ...
