from ..Base import *
from ..AcadObject import *
from ..Proxy import AccessMode as AccessMode, proxy_property as proxy_property

class AcadPreferencesProfiles(AppObject):
    def __init__(self, obj) -> None: ...
    ActiveProfile: str
    Application: AcadApplication
    def CopyProfile(self, oldProfileName: In[str], newProfileName: In[str]) -> None: ...
    def DeleteProfile(self, ProfileName: In[str]) -> None: ...
    def ExportProfile(self, Profile: In[str], RegFile: In[str]) -> None: ...
    def GetAllProfileNames(self) -> tuple[str]: ...
    def ImportProfile(self, Profile: In[str], RegFile: In[str], IncludePathInfo: In[bool]) -> None: ...
    def RenameProfile(self, origProfileName: In[str], newProfileName: In[str]) -> None: ...
    def ResetProfile(self, Profile: In[str]) -> None: ...
