from ..Base import *
from ..Proxy import *
from ..AcadObject import *

class AcadPopupMenu(AppObject):
    def __init__(self, obj) -> None: ...
    Application: AcadApplication
    Count: int
    Name: str
    NameNoMnemonic: str
    OnMenuBar: bool
    Parent: AppObject
    ShortcutMenu: bool
    TagString: str
    def AddMenuItem(self, Index: In[int | str], Label: In[str], Macro: In[str]) -> AcadPopupMenuItem: ...
    def AddSeparator(self, Index: In[int | str]) -> AcadPopupMenuItem: ...
    def AddSubMenu(self, Index: In[int | str], Label: In[str]) -> AcadPopupMenu: ...
    def InsertInMenuBar(self, Index: In[int | str]) -> None: ...
    def Item(self, Index: In[int | str]) -> AcadPopupMenu: ...
    def RemoveMenuFromMenuBar(self, Index: In[int]) -> None: ...
