from ..Base import *
from ..Proxy import *
from .AcadDatabase import AcadDatabase as AcadDatabase, IAcadDatabase as IAcadDatabase
from .AcadUCS import AcadUCS as AcadUCS

class AcadDocument(AcadDatabase):
    def __init__(self, obj) -> None: ...
    Active: bool
    ActiveDimStyle: AcadDimStyle
    ActiveLayer: AcadLayer
    ActiveLayout: AcadLayout
    ActiveLinetype: AcadLineType
    ActiveMaterial: AcadMaterial
    ActivePViewport: AcadPViewport
    ActiveSelectionSet: AcadSelectionSet
    ActiveSpace: AcActiveSpace
    ActiveTextStyle: AcadTextStyle
    ActiveUCS: AcadUCS
    ActiveViewport: AcadViewport
    Application: AcadApplication
    Database: IAcadDatabase
    FullName: str
    Height: float
    HWND: int
    MSpace: bool
    Name: str
    ObjectSnapMode: bool
    Path: str
    PickfirstSelectionSet: AcadSelectionSet
    Plot: AcadPlot
    ReadOnly: bool
    Saved: bool
    SelectionSets: AcadSelectionSet
    SummaryInfo: AcadSummaryInfo
    Utility: AcadUtility
    Width: float
    WindowState: AcWindowState
    WindowTitle: str
    def Activate(self) -> None: ...
    def AuditInfo(self, FixError: In[bool]) -> None: ...
    def Close(self, SaveChanges: In[bool] = False, FileName: In[str] = '') -> None: ...
    def EndUndoMark(self) -> None: ...
    def Export(self, FileName: In[str], Extension: In[str], SelectionSet: In[AcadSelectionSet]) -> None: ...
    def GetVariable(self, Name: In[str]) -> any: ...
    def Import(self, FileName: In[str], InsertionPoint: In[PyGePoint3d], ScaleFactor: In[float]) -> AcadBlockReference | None: ...
    def LoadShapeFile(self, FullName: In[str]) -> None: ...
    def New(self, TemplateFileName: In[str]) -> AcadDocument: ...
    def Open(self, Name: In[str], ReadOnly: In[bool] = False) -> AcadDocument: ...
    def PostCommand(self, Command: In[str]) -> None: ...
    def PurgeAll(self) -> None: ...
    def Regen(self, WhichViewports: In[AcRegenType]) -> None: ...
    def Save(self) -> None: ...
    def SaveAs(self, FileName: In[str], FileType: In[AcSaveAsType] = ..., SecurityParams: In[AcadSecurityParams] = None) -> None: ...
    def SendCommand(self, Command: In[str]) -> None: ...
    def SetVariable(self, Name: In[str], Value: In[Variant]) -> None: ...
    def StartUndoMark(self) -> None: ...
    def WBlock(self, FileName: In[str], SelectionSet: In[AcadSelectionSet]) -> None: ...
