from ..Base import *
from ..Proxy import *
from ..AcadObject import *
from ..Objects import *
from ..AcadEntity import *
from ..Entities import *

class IAcadBlock(IAcadObjectCollection):
    def __init__(self, obj) -> None: ...
    def Add3DFace(self, Point1: In[PyGePoint3d], Point2: In[PyGePoint3d], Point3: In[PyGePoint3d], Point4: In[PyGePoint3d] = None) -> Acad3DFace: ...
    def Add3DMesh(self, M: In[int], N: In[int], PointsMatrix: In[vDoubleArray]) -> AcadPolygonMesh: ...
    def Add3DPoly(self, PointsArray: In[PyGePoint3dArray]) -> Acad3DPolyline: ...
    def AddArc(self, Center: In[PyGePoint3d], Radius: In[float], StartAngle: In[float], EndAngle: In[float]) -> AcadArc: ...
    def AddAttribute(self, Height: In[float], Mode: In[AcAttributeMode], Prompt: In[str], InsertionPoint: In[PyGePoint3d], Tag: In[str], Value: In[str]) -> AcadAttribute: ...
    def AddBox(self, Origin: In[PyGePoint3d], Length: In[float], Width: In[float], Height: In[float]) -> Acad3DSolid: ...
    def AddCircle(self, Center: In[PyGePoint3d], Radius: In[float]) -> AcadCircle: ...
    def AddCone(self, Center: In[PyGePoint3d], BaseRadius: In[float], Height: In[float]) -> Acad3DSolid: ...
    def AddCustomObject(self, ClassName: In[str]) -> AcadObject: ...
    def AddCylinder(self, Center: In[PyGePoint3d], Radius: In[float], Height: In[float]) -> Acad3DSolid: ...
    def AddDim3PointAngular(self, AngleVertex: In[PyGePoint3d], FirstEndPoint: In[PyGePoint3d], SecondEndPoint: In[PyGePoint3d], TextPoint: In[PyGePoint3d]) -> AcadDim3PointAngular: ...
    def AddDimAligned(self, ExtLine1Point: In[PyGePoint3d], ExtLine2Point: In[PyGePoint3d], TextPosition: In[PyGePoint3d]) -> AcadDimAligned: ...
    def AddDimArc(self, ArcCenter: In[PyGePoint3d], FirstEndPoint: In[PyGePoint3d], SecondEndPoint: In[PyGePoint3d], ArcPoint: In[PyGePoint3d]) -> AcadDimArcLength: ...
    def AddDimDiametric(self, ChordPoint: In[PyGePoint3d], FarChordPoint: In[PyGePoint3d], LeaderLength: In[float]) -> AcadDimDiametric: ...
    def AddDimOrdinate(self, DefinitionPoint: In[PyGePoint3d], LeaderEndPoint: In[PyGePoint3d], UseXAxis: In[bool]) -> AcadDimOrdinate: ...
    def AddDimRadial(self, Center: In[PyGePoint3d], ChordPoint: In[PyGePoint3d], LeaderLength: In[float]) -> AcadDimRadial: ...
    def AddDimRadialLarge(self, Center: In[PyGePoint3d], ChordPoint: In[PyGePoint3d], OverrideCenter: In[PyGePoint3d], JogPoint: In[PyGePoint3d], JogAngle: In[float]) -> AcadDimRadialLarge: ...
    def AddDimRotated(self, XLine1Point: In[PyGePoint3d], XLine2Point: In[PyGePoint3d], DimLineLocation: In[PyGePoint3d], RotationAngle: In[float]) -> AcadDimRotated: ...
    def AddEllipse(self, Center: In[PyGePoint3d], MajorAxis: In[PyGeVector3d], RadiusRatio: In[float]) -> AcadEllipse: ...
    def AddEllipticalCone(self, Center: In[PyGePoint3d], MajorRadius: In[float], MinorRadius: In[float], Height: In[float]) -> Acad3DSolid: ...
    def AddEllipticalCylinder(self, Center: In[PyGePoint3d], MajorRadius: In[float], MinorRadius: In[float], Height: In[float]) -> Acad3DSolid: ...
    def AddExtrudedSolid(self, Profile: In[AcadRegion], Height: In[float], TaperAngle: In[float]) -> Acad3DSolid: ...
    def AddExtrudedSolidAlongPath(self, Profile: In[AcadRegion], Path: In[AcadArc | AcadCircle | AcadEllipse | AcadPolyline | AcadSpline]) -> Acad3DSolid: ...
    def AddHatch(self, PatternType: In[AcPatternType | AcGradientPatternType], PatternName: In[str], Associativity: In[bool], HatchObjectType: In[AcHatchObjectType] = None) -> AcadHatch: ...
    def AddLeader(self, PointsArray: In[PyGePoint3d], Annotation: In[AcadBlockReference | AcadMtext | AcadTolerance], Type: In[AcLeaderType]) -> AcadLeader: ...
    def AddLightWeightPolyline(self, VerticesList: In[PyGePoint2dArray]) -> AcadLWPolyline: ...
    def AddLine(self, StartPoint: In[PyGePoint3d], EndPoint: In[PyGePoint3d]) -> AcadLine: ...
    def AddMInsertBlock(self, InsertionPoint: In[PyGePoint3d], Name: In[str], XScale: In[float], YScale: In[float], ZScale: In[float], Rotation: In[float], NumRows: In[int], NumColumns: In[int], RowSpacing: In[float], ColumnSpacing: In[float], Password: In[Variant] = ...) -> AcadMInsertBlock: ...
    def AddMLeader(self, pointsArray: In[PyGePoint3dArray]) -> AcadMLeader: ...
    def AddMLine(self, VertexList: In[PyGePoint3dArray]) -> AcadMLine: ...
    def AddMText(self, InsertionPoint: In[PyGePoint3d], Width: In[float], Text: In[str]) -> AcadMtext: ...
    def AddPoint(self, Point: In[PyGePoint3d]) -> AcadPoint: ...
    def AddPolyfaceMesh(self, VerticesList: In[PyGePoint3dArray], FaceList: In[vShortArray]) -> AcadPolyfaceMesh: ...
    def AddPolyline(self, VerticesList: In[PyGePoint3dArray]) -> AcadPolyline: ...
    def AddRaster(self, ImageFileName: In[str], InsertionPoint: In[PyGePoint3d], ScaleFactor: In[float], RotationAngle: In[float]) -> AcadRasterImage: ...
    def AddRay(self, Point1: In[PyGePoint3d], Point2: In[PyGePoint3d]) -> AcadRay: ...
    def AddRegion(self, ObjectList: In[vObjectArray[AcadArc | AcadCircle | AcadEllipse | AcadLine | AcadLWPolyline | AcadSpline]]) -> vObjectArray[AcadRegion]: ...
    def AddRevolvedSolid(self, Profile: In[AcadRegion], AxisPoint: In[PyGePoint3d], AxisDir: In[PyGeVector3d], Angle: In[float]) -> Acad3DSolid: ...
    def AddSection(self, FromPoint: In[PyGePoint3d], ToPoint: In[PyGePoint3d], planeVector: In[PyGeVector3d]) -> AcadSection: ...
    def AddShape(self, Name: In[str], InsertionPoint: In[PyGePoint3d], ScaleFactor: In[float], Rotation: In[float]) -> AcadShape: ...
    def AddSolid(self, Point1: In[PyGePoint3d], Point2: In[PyGePoint3d], Point3: In[PyGePoint3d], Point4: In[PyGePoint3d]) -> AcadSolid: ...
    def AddSphere(self, Center: In[PyGePoint3d], Radius: In[float]) -> Acad3DSolid: ...
    def AddSpline(self, PointsArray: In[PyGePoint3dArray], StartTangent: In[PyGeVector3d], EndTangent: In[PyGeVector3d]) -> AcadSpline: ...
    def AddTable(self, InsertionPoint: In[PyGePoint3d], NumRows: In[int], NumColumns: In[int], RowHeight: In[float], ColWidth: In[float]) -> AcadTable: ...
    def AddText(self, TextString: In[str], InsertionPoint: In[PyGePoint3d], Height: In[float]) -> AcadText: ...
    def AddTolerance(self, Text: In[str], InsertionPoint: In[PyGePoint3d], Direction: In[PyGeVector3d]) -> AcadTolerance: ...
    def AddTorus(self, Center: In[PyGePoint3d], TorusRadius: In[float], TubeRadius: In[float]) -> Acad3DSolid: ...
    def AddTrace(self, PointsArray: In[PyGePoint3dArray]) -> AcadTrace: ...
    def AddWedge(self, Center: In[PyGePoint3d], Length: In[float], Width: In[float], Height: In[float]) -> Acad3DSolid: ...
    def AddXline(self, Point1: In[PyGePoint3d], Point2: In[PyGePoint3d]) -> AcadXline: ...
    def AttachExternalReference(self, PathName: In[str], Name: In[str], InsertionPoint: In[PyGePoint3d], XScale: In[float], YScale: In[float], ZScale: In[float], Rotation: In[float], Overlay: In[bool], Password: In[Variant] = ...) -> AcadExternalReference: ...
    def InsertBlock(self, InsertionPoint: In[PyGePoint3d], Name: In[str], Xscale: In[float] = 1.0, Yscale: In[float] = 1.0, ZScale: In[float] = 1.0, Rotation: In[float] = 0.0, Password: In[Variant] = ...) -> AcadBlockReference: ...

class AcadBlock(IAcadBlock):
    def __init__(self, obj) -> None: ...
    BlockScaling: AcBlockScaling
    Comments: str
    Explodable: bool
    IsDynamicBlock: bool
    IsLayout: bool
    IsXRef: bool
    Layout: AcadLayout
    Material: str
    Name: str
    Origin: PyGePoint3d
    Path: str
    Units: AcInsertUnits
    XRefDatabase: AcadDatabase
    def Bind(self, bPrefixName: In[bool]) -> None: ...
    def Delete(self) -> None: ...
    def Detach(self) -> None: ...
    def Reload(self) -> None: ...
    def Unload(self) -> None: ...
