from ..Base import *
from ..Proxy import *
from ..AcadObject import *

class AcadLayers(IAcadObjectCollection):
    def __init__(self, obj) -> None: ...
    def Add(self, Name: In[str]) -> AcadLayer: ...
    def Item(self, Index: In[int | str]) -> AcadLayer: ...
    def __iter__(self): ...
