from ..Base import *
from ..Proxy import *
from ..AcadObject import *
from ..AcadEntity import *

class AcadSortentsTable(AcadObject):
    def __init__(self, obj) -> None: ...
    def Block(self) -> AcadBlock: ...
    def GetFullDrawOrder(self, honorSortentsSysvar: In[bool]) -> vObjectArray: ...
    def GetRelativeDrawOrder(self, honorSortentsSysvar: In[bool]) -> vObjectArray: ...
    def MoveAbove(self, Target: In[AcadEntity]) -> vObjectArray: ...
    def MoveBelow(self, Target: In[AcadEntity]) -> vObjectArray: ...
    def MoveToBottom(self, Objects: In[vObjectArray]) -> None: ...
    def MoveToTop(self, Objects: In[vObjectArray]) -> None: ...
    def SetRelativeDrawOrder(self, Objects: In[vObjectArray]) -> None: ...
    def SwapOrder(self, Object1: In[AcadEntity], Object2: In[AcadEntity]) -> None: ...
