from ..Base import *
from ..Proxy import *
from ..AcadObject import *
from .AcadUCS import AcadUCS as AcadUCS

class AcadUCSs(IAcadObjectCollection):
    def __init__(self, obj) -> None: ...
    def Add(self, Origin: In[PyGePoint3d], XAxisPoint: In[PyGePoint3d], YAxisPoint: In[PyGePoint3d], Name: In[str]) -> AcadUCS: ...
    def Item(self, Index: In[int]) -> AcadUCS: ...
    def __iter__(self): ...
