from ..Base import *
from ..Proxy import *
from ..AcadObject import *
from .AcadHyperlink import *

class AcadHyperlinks(AppObjectCollection):
    def __init__(self, obj) -> None: ...
    Application: AcadApplication
    Count: int
    def Add(self, Name: In[str], Description: In[str] = '', NamedLocation: In[str] = '') -> AcadHyperlink: ...
    def Item(self, Index: In[int | str]) -> AcadHyperlink: ...
    def __iter__(self): ...
