# Generated by Django 5.1.8 on 2025-07-31 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0007_installedapplicationtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapplication',
            name='application_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_types', to='adestis_netbox_applications.installedapplicationtypes'),
        ),
    ]
