export const MultilineComment: 1;
export const LineComment: 2;
export const Magic: 3;
export const Script: 4;
export const Identifier: 5;
export const String: 6;
export const Keyword: 7;
export const Symbol: 8;
export const SystemCommand: 9;
