# Generated by Django 5.1.7 on 2025-04-10 17:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0014_mbaespecializacao_teste_noticia"),
    ]

    operations = [
        migrations.AddField(
            model_name="enaptemplatev1",
            name="suap_courses",
            field=wagtail.fields.StreamField(
                [("suap_courses", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Título", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitulo", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 3, "label": "Máximo de cursos apresentados"},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1), ("num_items", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
