# Generated by Django 5.1.6 on 2025-06-03 01:27

import enap_designsystem.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "enap_designsystem",
            "0161_alter_areaaluno_body_alter_cursoeadpage_curso_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursoeadpage",
            name="faq_curso",
            field=wagtail.fields.StreamField(
                [("accordion", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("", "Default")],
                            "label": "Template",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Custom CSS Class",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom ID", "max_length": 255, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("custom_template", 0),
                                ("custom_css_class", 1),
                                ("custom_id", 2),
                            ]
                        ],
                        {},
                    ),
                    4: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("enap_designsystem.EnapAccordionSnippet",),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("settings", 3), ("accordion", 4)]],
                        {},
                    ),
                },
                default=enap_designsystem.models.get_default_faq_curso,
            ),
        ),
    ]
