# Generated by Django 5.1.6 on 2025-06-09 02:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0183_editalconcursoinovacao_cronograma"),
    ]

    operations = [
        migrations.AddField(
            model_name="editalconcursoinovacao",
            name="premios",
            field=wagtail.fields.StreamField(
                [("premios", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Imagem de fundo da seção (opcional)",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Título da seção (ex: Quais são os prêmios?)",
                            "max_length": 200,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#2F4F4F", "Verde Escuro"),
                                ("#000000", "Preto"),
                                ("#4A4A4A", "Cinza Escuro"),
                                ("#696969", "Cinza Médio"),
                                ("#8B4513", "Marrom"),
                                ("#800080", "Roxo"),
                                ("#8B0000", "Vermelho Escuro"),
                                ("#191970", "Azul Marinho"),
                            ],
                            "help_text": "Cor do título",
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Texto do tópico/prêmio", "max_length": 500},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("topico", 3)]],
                        {
                            "help_text": "Adicione os tópicos/prêmios (até 15 itens)",
                            "max_num": 15,
                            "min_num": 1,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("imagem_fundo", 0),
                                ("titulo", 1),
                                ("cor_titulo", 2),
                                ("topicos", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
