# Generated by Django 5.1.6 on 2025-08-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0319_remove_enapnoticia_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enapnoticia",
            name="legenda_home",
            field=models.TextField(
                blank=True,
                help_text="Texto que aparece nas listagens da home (máx. 500 caracteres). Se vazio, usará o subtítulo.",
                max_length=500,
                verbose_name="Legenda para Home",
            ),
        ),
    ]
