# Generated by Django 5.1.7 on 2025-05-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "enap_designsystem",
            "0072_alter_enapnoticiaimportada_imagem_externa_and_more",
        ),
        ("enap_designsystem", "0078_alter_areaaluno_body_alter_enapcomponentes_body"),
    ]

    operations = []
