# Generated by Django 5.1.7 on 2025-05-27 13:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0124_remove_jobvacancypage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvacancypage",
            name="image",
            field=wagtail.fields.StreamField(
                [("image", 0)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Imagem", "required": False},
                    )
                },
                null=True,
                verbose_name="Imagem",
            ),
        ),
    ]
