# Generated by Django 5.1.6 on 2025-11-28 19:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "enap_designsystem",
            "0503_alter_areaaluno_body_alter_enapcomponentes_body_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="capsulaindexpage",
            name="menu",
            field=wagtail.fields.StreamField(
                [("menu_nav", 12)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Texto do menu", "max_length": 50},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL externa", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Ou escolha uma página interna",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Marcar como item ativo",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("texto", 0),
                                ("url", 1),
                                ("pagina_interna", 2),
                                ("ativo", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {
                            "help_text": "Itens do menu de navegação",
                            "max_num": 10,
                            "min_num": 1,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Imagem de logo da esquerda", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Link ao clicar na logo", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor de fundo do menu",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor do texto do menu",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor do item ativo",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor do hover nos itens",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("items_menu", 5),
                                ("logo", 6),
                                ("logo_url", 7),
                                ("cor_fundo", 8),
                                ("cor_texto", 9),
                                ("cor_ativo", 10),
                                ("cor_hover", 11),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="capsulapage",
            name="menu",
            field=wagtail.fields.StreamField(
                [("menu_nav", 12)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Texto do menu", "max_length": 50},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL externa", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Ou escolha uma página interna",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Marcar como item ativo",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("texto", 0),
                                ("url", 1),
                                ("pagina_interna", 2),
                                ("ativo", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {
                            "help_text": "Itens do menu de navegação",
                            "max_num": 10,
                            "min_num": 1,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Imagem de logo da esquerda", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Link ao clicar na logo", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor de fundo do menu",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor do texto do menu",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor do item ativo",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor do hover nos itens",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("items_menu", 5),
                                ("logo", 6),
                                ("logo_url", 7),
                                ("cor_fundo", 8),
                                ("cor_texto", 9),
                                ("cor_ativo", 10),
                                ("cor_hover", 11),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rotapage",
            name="menu",
            field=wagtail.fields.StreamField(
                [("menu_nav", 12)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Texto do menu", "max_length": 50},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL externa", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Ou escolha uma página interna",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Marcar como item ativo",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("texto", 0),
                                ("url", 1),
                                ("pagina_interna", 2),
                                ("ativo", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {
                            "help_text": "Itens do menu de navegação",
                            "max_num": 10,
                            "min_num": 1,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Imagem de logo da esquerda", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Link ao clicar na logo", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor de fundo do menu",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor do texto do menu",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor do item ativo",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("#FFFFFF", "Branco (#FFFFFF)"),
                                ("#F8F9FA", "Cinza Claro (#F8F9FA)"),
                                ("#000000", "Preto (#000000)"),
                                ("#2F134F", "Roxo 100 LIIA (#2F134F)"),
                                ("#F2F1F3", "Cinza LIIA 10 (#F2F1F3)"),
                                ("#492277", "Roxo 90 LIIA (#492277)"),
                                ("#525258", "Cinza LIIA 100 (#525258)"),
                                ("#AD6BFC", "Roxo GNOVA (#AD6BFC)"),
                                ("#007D7A", "Verde Enap 70 (#007D7A)"),
                                ("#024248", "Verde ENAP (#024248)"),
                                ("#007D7A", "Verde Link ENAP (#007D7A)"),
                                ("#AD6BFC", "Roxo Gnova (#AD6BFC)"),
                                ("#B396FC", "Roxo Claro Gnova (#B396FC)"),
                                ("#2F134F", "Roxo Escuro LIIA (#2F134F)"),
                            ],
                            "help_text": "Cor do hover nos itens",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("items_menu", 5),
                                ("logo", 6),
                                ("logo_url", 7),
                                ("cor_fundo", 8),
                                ("cor_texto", 9),
                                ("cor_ativo", 10),
                                ("cor_hover", 11),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
