class NetAdapterInfo:
    def __init__(self, *, include_virtual: bool = False, include_loopback: bool = False, only_up: bool = True, require_ip: bool = False) -> None: ...
    def get_data(self): ...
