import example_dagster_codebase.partitioned_statically_etl.partioned_etl_task_1
import example_dagster_codebase.partitioned_statically_etl.partioned_etl_task_2
import example_dagster_codebase.partitioned_statically_etl.partioned_etl_task_3
