# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr

class BalanceFetchLedgerResponseArray(BaseModel):
    """
    BalanceFetchLedgerResponseArray
    """
    integration: StrictInt = Field(...)
    domain: StrictStr = Field(...)
    balance: StrictInt = Field(...)
    currency: StrictStr = Field(...)
    difference: StrictInt = Field(...)
    reason: StrictStr = Field(...)
    model_responsible: StrictStr = Field(...)
    model_row: StrictInt = Field(...)
    id: StrictInt = Field(...)
    created_at: StrictStr = Field(..., alias="createdAt")
    updated_at: StrictStr = Field(..., alias="updatedAt")
    __properties = ["integration", "domain", "balance", "currency", "difference", "reason", "model_responsible", "model_row", "id", "createdAt", "updatedAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BalanceFetchLedgerResponseArray:
        """Create an instance of BalanceFetchLedgerResponseArray from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BalanceFetchLedgerResponseArray:
        """Create an instance of BalanceFetchLedgerResponseArray from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BalanceFetchLedgerResponseArray.parse_obj(obj)

        _obj = BalanceFetchLedgerResponseArray.parse_obj({
            "integration": obj.get("integration"),
            "domain": obj.get("domain"),
            "balance": obj.get("balance"),
            "currency": obj.get("currency"),
            "difference": obj.get("difference"),
            "reason": obj.get("reason"),
            "model_responsible": obj.get("model_responsible"),
            "model_row": obj.get("model_row"),
            "id": obj.get("id"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt")
        })
        return _obj


