# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class MetadataCustomFieldsArray(BaseModel):
    """
    MetadataCustomFieldsArray
    """
    value: StrictStr = Field(...)
    display_name: StrictStr = Field(...)
    variable_name: StrictStr = Field(...)
    __properties = ["value", "display_name", "variable_name"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MetadataCustomFieldsArray:
        """Create an instance of MetadataCustomFieldsArray from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MetadataCustomFieldsArray:
        """Create an instance of MetadataCustomFieldsArray from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MetadataCustomFieldsArray.parse_obj(obj)

        _obj = MetadataCustomFieldsArray.parse_obj({
            "value": obj.get("value"),
            "display_name": obj.get("display_name"),
            "variable_name": obj.get("variable_name")
        })
        return _obj


