# coding: utf-8

"""
    Pingera API

     The official API for Pingera, a monitoring and status page platform. This API allows you to manage checks, organizations, incidents, and more.   Some useful links: * [Pingera website](https://pingera.ru?utm_source=api_docs) * [API documentation](https://docs.pingera.ru/api/overview) * [Application](https://app.pingera.ru) * [Status page](https://status.pingera.ru) 

    The version of the OpenAPI document: v1
    Contact: privet@pingera.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pingera.models.alert_channel import AlertChannel
from typing import Optional, Set
from typing_extensions import Self

class AlertRule1(BaseModel):
    """
    AlertRule1
    """ # noqa: E501
    channels: Optional[List[AlertChannel]] = Field(default=None, description="List of alert channels configured for this rule.")
    condition: Optional[StrictStr] = Field(default=None, description="The condition that triggers this alert rule.")
    channel_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="List of alert channel IDs to send notifications to.")
    check_id: Optional[StrictStr] = Field(default=None, description="The identifier of the monitor check this rule applies to.")
    auto_resolve: Optional[StrictBool] = Field(default=True, description="Whether alerts should automatically resolve when the check recovers. Defaults to true.")
    multi_region_threshold: Optional[Dict[str, Any]] = Field(default=None, description="Threshold configuration for 'specific_count' mode. Example: {'count': 2}")
    created_at: Optional[datetime] = Field(default=None, description="The timestamp when the alert rule was created in ISO format.")
    check_name: Optional[Any] = Field(default=None, description="The name of the monitor check this rule applies to.")
    severity: Optional[StrictStr] = Field(default=None, description="The severity level of alerts generated by this rule.")
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = Field(default=None, description="A user-friendly name for the alert rule. Max 100 characters.")
    cooldown_period: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=300, description="Time in seconds to wait before triggering another alert. Defaults to 300.")
    enabled: Optional[StrictBool] = Field(default=True, description="Whether the alert rule is enabled. Defaults to true.")
    updated_at: Optional[datetime] = Field(default=None, description="The timestamp when the alert rule was last updated in ISO format.")
    id: Optional[StrictStr] = Field(default=None, description="The unique identifier for the alert rule.")
    multi_region_mode: Optional[StrictStr] = Field(default='any_region', description="How to evaluate multi-region check failures. Defaults to 'any_region'.")
    condition_parameters: Optional[Dict[str, Any]] = Field(default=None, description="Parameters specific to the trigger condition. Required for some conditions.")
    __properties: ClassVar[List[str]] = ["channels", "condition", "channel_ids", "check_id", "auto_resolve", "multi_region_threshold", "created_at", "check_name", "severity", "name", "cooldown_period", "enabled", "updated_at", "id", "multi_region_mode", "condition_parameters"]

    @field_validator('condition')
    def condition_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['check_failed', 'check_timeout', 'check_degraded', 'consecutive_failures', 'uptime_below_threshold']):
            raise ValueError("must be one of enum values ('check_failed', 'check_timeout', 'check_degraded', 'consecutive_failures', 'uptime_below_threshold')")
        return value

    @field_validator('severity')
    def severity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high', 'critical']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high', 'critical')")
        return value

    @field_validator('multi_region_mode')
    def multi_region_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any_region', 'all_regions', 'majority', 'specific_count']):
            raise ValueError("must be one of enum values ('any_region', 'all_regions', 'majority', 'specific_count')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlertRule1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "channels",
            "created_at",
            "check_name",
            "updated_at",
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in channels (list)
        _items = []
        if self.channels:
            for _item_channels in self.channels:
                if _item_channels:
                    _items.append(_item_channels.to_dict())
            _dict['channels'] = _items
        # set to None if multi_region_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.multi_region_threshold is None and "multi_region_threshold" in self.model_fields_set:
            _dict['multi_region_threshold'] = None

        # set to None if check_name (nullable) is None
        # and model_fields_set contains the field
        if self.check_name is None and "check_name" in self.model_fields_set:
            _dict['check_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlertRule1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "channels": [AlertChannel.from_dict(_item) for _item in obj["channels"]] if obj.get("channels") is not None else None,
            "condition": obj.get("condition"),
            "channel_ids": obj.get("channel_ids"),
            "check_id": obj.get("check_id"),
            "auto_resolve": obj.get("auto_resolve") if obj.get("auto_resolve") is not None else True,
            "multi_region_threshold": obj.get("multi_region_threshold"),
            "created_at": obj.get("created_at"),
            "check_name": obj.get("check_name"),
            "severity": obj.get("severity"),
            "name": obj.get("name"),
            "cooldown_period": obj.get("cooldown_period") if obj.get("cooldown_period") is not None else 300,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "updated_at": obj.get("updated_at"),
            "id": obj.get("id"),
            "multi_region_mode": obj.get("multi_region_mode") if obj.get("multi_region_mode") is not None else 'any_region',
            "condition_parameters": obj.get("condition_parameters")
        })
        return _obj


