# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

class PlanCreateResponseData(BaseModel):
    """
    PlanCreateResponseData
    """
    currency: StrictStr = Field(...)
    name: StrictStr = Field(...)
    amount: StrictInt = Field(...)
    interval: StrictStr = Field(...)
    integration: StrictInt = Field(...)
    domain: StrictStr = Field(...)
    plan_code: StrictStr = Field(...)
    invoice_limit: StrictInt = Field(...)
    send_invoices: StrictBool = Field(...)
    send_sms: StrictBool = Field(...)
    hosted_page: StrictBool = Field(...)
    migrate: StrictBool = Field(...)
    is_archived: StrictBool = Field(...)
    id: StrictInt = Field(...)
    created_at: StrictStr = Field(..., alias="createdAt")
    updated_at: StrictStr = Field(..., alias="updatedAt")
    __properties = ["currency", "name", "amount", "interval", "integration", "domain", "plan_code", "invoice_limit", "send_invoices", "send_sms", "hosted_page", "migrate", "is_archived", "id", "createdAt", "updatedAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlanCreateResponseData:
        """Create an instance of PlanCreateResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlanCreateResponseData:
        """Create an instance of PlanCreateResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlanCreateResponseData.parse_obj(obj)

        _obj = PlanCreateResponseData.parse_obj({
            "currency": obj.get("currency"),
            "name": obj.get("name"),
            "amount": obj.get("amount"),
            "interval": obj.get("interval"),
            "integration": obj.get("integration"),
            "domain": obj.get("domain"),
            "plan_code": obj.get("plan_code"),
            "invoice_limit": obj.get("invoice_limit"),
            "send_invoices": obj.get("send_invoices"),
            "send_sms": obj.get("send_sms"),
            "hosted_page": obj.get("hosted_page"),
            "migrate": obj.get("migrate"),
            "is_archived": obj.get("is_archived"),
            "id": obj.get("id"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt")
        })
        return _obj


