from _typeshed import Incomplete

GLOBAL_SSH_INSTANCE: Incomplete

class CLASS_mySQLNetSSH:
    ssh: Incomplete
    forward_threads: Incomplete
    running: bool
    def __init__(self) -> None: ...
    def CUF_SSH_Connect(self, host, port, user, password=None, pkey_path=None, pkey_pass=None): ...
    def CUF_AddPortForward(self, local_host, local_port, remote_host, remote_port) -> None: ...
    def CUF_Tunnel_Start(self): ...
    def CUF_Tunnel_Stop(self) -> None: ...
    def CUF_IsAlive(self): ...
    def CUF_ReleaseAll(self) -> None: ...
