from _typeshed import Incomplete
from dataclasses import dataclass
from enum import IntEnum
from typing import Any

class ENUM_DB_CHARSET(IntEnum):
    cE_DBCS_ascii = 0
    cE_DBCS_big5 = 1
    cE_DBCS_binary = 2
    cE_DBCS_cp1250 = 3
    cE_DBCS_gb2312 = 4
    cE_DBCS_gbk = 5
    cE_DBCS_latin1 = 6
    cE_DBCS_latin2 = 7
    cE_DBCS_latin5 = 8
    cE_DBCS_latin7 = 9
    cE_DBCS_utf16 = 10
    cE_DBCS_utf16le = 11
    cE_DBCS_utf32 = 12
    cE_DBCS_utf8mb3 = 13
    cE_DBCS_utf8mb4 = 14

class ENUM_TABLE_TYPE(IntEnum):
    cE_TABTP_Standard = 1
    cE_TABTP_Memory = 2
    cE_TABTP_MyISAM = 3

class ENUM_FIELD_TYPE(IntEnum):
    cE_FLDTP_INT = 1
    cE_FLDTP_VARCHAR = 2
    cE_FLDTP_FLOAT = 3
    cE_FLDTP_DATETIME = 4
    cE_FLDTP_TEXT = 5

class ENUM_INDEX_TYPE(IntEnum):
    cE_IDX_Normal = 1
    cE_IDX_Unique = 2
    cE_IDX_FullText = 3
    cE_IDX_Spatial = 4

@dataclass
class STRU_DEF_Fields:
    ms_Name: str
    mE_Type: ENUM_FIELD_TYPE
    mi_Length: int | None = ...
    mB_PrimaryKey: bool = ...
    mB_AutoInc: bool = ...
    mB_Nullable: bool = ...
    mU_Default: Any | None = ...
    mB_Unique: bool = ...

@dataclass
class STRU_DEF_Index:
    ms_IndexName: str
    obj_FieldList: list
    mE_IndexType: ENUM_INDEX_TYPE = ...
    mB_Unique: bool = ...
    mB_FullText: bool = ...
    mB_Spatial: bool = ...

@dataclass
class STRU_mySQLDBInfo:
    ms_DB_HostIP: str = ...
    mi_DB_Port: int = ...
    ms_DB_Name: str = ...
    ms_User: str = ...
    ms_Password: str = ...

class CLASS_mySQLDBCtrl:
    CUms_DB_HostIP: str
    CUmi_DB_Port: int
    CUms_DB_Name: str
    CUms_User: str
    CUms_Password: str
    CUobj_Conn: Incomplete
    CVmi_qryRECCNT: int
    CVmsa_DBCS: Incomplete
    def __init__(self) -> None: ...
    def CUF_SET_Charset(self, PmE_DB_Charset: ENUM_DB_CHARSET): ...
    def CUF_OpenConnection_DBCS(self, Pms_DB_HostIP, Pmi_DB_Port, Pms_DB_Name, Pms_User, Pms_Password, PmE_DB_CHARSET): ...
    def CUF_OpenConnection(self, Pms_DB_HostIP, Pmi_DB_Port, Pms_DB_Name, Pms_User, Pms_Password): ...
    def CUF_DB_OpenConn(self, Pstru_mySQLDBInfo: STRU_mySQLDBInfo): ...
    def CUF_DB_OpenSQL(self, Pobj_Connection, Pms_SQL): ...
    def CUF_DB_OpenSQL_utf8(self, Pobj_Connection, Pms_SQL): ...
    def CUF_DB_FETCH(self, Pobj_Query): ...
    def CUF_DB_Next(self, Pobj_Query): ...
    def CUF_Next(self, Pobj_Query): ...
    def CUF_DB_ExecSQL(self, Pobj_Connection, Pms_SQL): ...
    def CUF_DB_ExecSQL_utf8(self, Pobj_Connection, Pms_SQL): ...
    def CUF_DB_RecordCount(self, Pobj_Query): ...
    def CUF_DB_RECCOUNT(self, Pobj_Query): ...
    def CUF_DB_Eof(self, Pobj_Query): ...
    def CUF_Eof(self, Pobj_Query): ...
    def CUF_str_utf8(self, Pobj_DataSet): ...
    def CUF_utf8(self, Pobj_DataSet): ...
    def CUF_str_big5(self, Pobj_DataSet): ...
    def CUF_big5(self, Pobj_DataSet): ...
    def CUF_GetBlobField(self, Pobj_DataSet, Pms_BlobFieldName, Pms_FileName) -> None: ...
    def CUF_GET_Blob(self, Pobj_Query, Pms_BlobFieldName, Pms_FileName) -> None: ...
    def CUF_SetBlobField(self, Pobj_Query, Pms_TableName, Pms_QUERY, Pms_BlobFieldName, Pms_FileName) -> None: ...
    def CUF_SET_BLOB(self, Pobj_Query, Pms_TableName, Pms_QUERY, Pms_BlobFieldName, Pms_FileName) -> None: ...
    def CUF_Table_Find(self, Pms_TableName: str) -> bool: ...
    def CUF_Table_Drop(self, Pms_TableName: str) -> bool: ...
    def CUF_Table_List(self, Pobj_TableNameList: list) -> bool: ...
    def CUF_TABLE_Create(self, PmE_TableType: ENUM_TABLE_TYPE, Pms_TableName: str, Pobj_FieldsList: list[STRU_DEF_Fields], PmB_ExecSQL: bool = True, PmB_ForceCreate: bool = False) -> str: ...
    def CUF_INDEX_Create(self, Pms_TableName: str, Pobj_IndexList: list[STRU_DEF_Index], PmB_ExecSQL: bool = True) -> list: ...
    def CUF_INDEX_Drop(self, Pms_TableName: str, Pobj_IndexNameList: list, PmB_ExecSQL: bool = True) -> list: ...
    def CUF_GetServerDateTime(self, Pms_SEPCHAR_DATE, Pms_SEPCHAR_TIME, Pms_SEPERATOR): ...
    def CUF_GetServerDateTime1(self, PmB_DELIMITER): ...
    def CUF_GetServerDateTime2(self): ...
    def CUF_GetServerDate(self, Pms_DELIMITER): ...
    def CUF_GetServerTime(self, Pms_DELIMITER): ...
    def CUF_AddTime(self, Pms_DateTime, Pmi_TimeSecond): ...
    def CUF_AddTime_Current(self, Pmi_TimeSecond): ...
