# coding: utf-8

"""
    Backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebiose_cloud_client.api.forge_endpoints_api import ForgeEndpointsApi


class TestForgeEndpointsApi(unittest.IsolatedAsyncioTestCase):
    """ForgeEndpointsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ForgeEndpointsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_agent_during_forge_cycle(self) -> None:
        """Test case for add_agent_during_forge_cycle

        """
        pass

    async def test_add_agents_during_forge_cycle(self) -> None:
        """Test case for add_agents_during_forge_cycle

        """
        pass

    async def test_delete_forge(self) -> None:
        """Test case for delete_forge

        """
        pass

    async def test_end_forge_cycle(self) -> None:
        """Test case for end_forge_cycle

        """
        pass

    async def test_forges_cycles_forge_cycle_uuid_deduct_compute_banks_post(self) -> None:
        """Test case for forges_cycles_forge_cycle_uuid_deduct_compute_banks_post

        """
        pass

    async def test_forges_cycles_forge_cycle_uuid_select_agents_get(self) -> None:
        """Test case for forges_cycles_forge_cycle_uuid_select_agents_get

        """
        pass

    async def test_forges_cycles_forge_cycle_uuid_usage_post(self) -> None:
        """Test case for forges_cycles_forge_cycle_uuid_usage_post

        """
        pass

    async def test_get_forge(self) -> None:
        """Test case for get_forge

        """
        pass

    async def test_get_forge_cycles(self) -> None:
        """Test case for get_forge_cycles

        """
        pass

    async def test_get_forges(self) -> None:
        """Test case for get_forges

        """
        pass

    async def test_get_spend(self) -> None:
        """Test case for get_spend

        """
        pass

    async def test_start_new_forge_cycle(self) -> None:
        """Test case for start_new_forge_cycle

        """
        pass

    async def test_update_forge(self) -> None:
        """Test case for update_forge

        """
        pass


if __name__ == '__main__':
    unittest.main()
