# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intrepidcs/vspyx/rpc/Runtime/ImplementationDataType.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'intrepidcs/vspyx/rpc/Runtime/ImplementationDataType.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from intrepidcs.vspyx.rpc.Runtime import References_pb2 as intrepidcs_dot_vspyx_dot_rpc_dot_Runtime_dot_References__pb2
from intrepidcs.vspyx.rpc.Runtime import DataDefinition_pb2 as intrepidcs_dot_vspyx_dot_rpc_dot_Runtime_dot_DataDefinition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9intrepidcs/vspyx/rpc/Runtime/ImplementationDataType.proto\x12\x1cintrepidcs.vspyx.rpc.Runtime\x1a-intrepidcs/vspyx/rpc/Runtime/References.proto\x1a\x31intrepidcs/vspyx/rpc/Runtime/DataDefinition.proto\"\xed\x02\n\x13SwDataDefProperties\x12\x19\n\x11\x43\x61librationAccess\x18\x01 \x01(\t\x12Z\n\x19ImplementationDataTypeRef\x18\x02 \x01(\x0b\x32\x37.intrepidcs.vspyx.rpc.Runtime.ImplementationDataTypeRef\x12>\n\x0b\x42\x61seTypeRef\x18\x03 \x01(\x0b\x32).intrepidcs.vspyx.rpc.Runtime.BaseTypeRef\x12H\n\x0f\x44\x61taConstraints\x18\x04 \x01(\x0b\x32/.intrepidcs.vspyx.rpc.Runtime.DataConstraintRef\x12\x43\n\x0b\x43ompuMethod\x18\x05 \x01(\x0b\x32,.intrepidcs.vspyx.rpc.Runtime.CompuMethodRefH\x00\x42\x10\n\x0e\x43ompuMethodRef\"\xce\x01\n\x16ImplementationDataType\x12\x10\n\x08\x43\x61tegory\x18\x01 \x01(\t\x12\x45\n\nProperties\x18\x02 \x01(\x0b\x32\x31.intrepidcs.vspyx.rpc.Runtime.SwDataDefProperties\x12\x46\n\x08\x45lements\x18\x03 \x03(\x0b\x32\x34.intrepidcs.vspyx.rpc.Runtime.ImplementationDataType\x12\x13\n\x0bTypeEmitter\x18\x04 \x01(\tB\"Z intrepidcs.com/vspyx/rpc/runtimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intrepidcs.vspyx.rpc.Runtime.ImplementationDataType_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z intrepidcs.com/vspyx/rpc/runtime'
  _globals['_SWDATADEFPROPERTIES']._serialized_start=190
  _globals['_SWDATADEFPROPERTIES']._serialized_end=555
  _globals['_IMPLEMENTATIONDATATYPE']._serialized_start=558
  _globals['_IMPLEMENTATIONDATATYPE']._serialized_end=764
# @@protoc_insertion_point(module_scope)
