from typing import List, Iterable, Optional, Tuple

class WaveletMatrix:
    def __init__(self, data: Iterable[int]) -> None: ...
    def __getitem__(self, index: int) -> int: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> "WaveletMatrix": ...
    def __deepcopy__(self, memo) -> "WaveletMatrix": ...
    def values(self) -> List[int]: ...
    def access(self, index: int) -> int: ...
    def rank(self, value: int, end: int) -> int: ...
    def select(self, value: int, kth: int) -> Optional[int]: ...
    def quantile(self, start: int, end: int, kth: int) -> int: ...
    def topk(self, start: int, end: int, k: Optional[int] = None) -> List[Tuple[int, int]]: ...
    def range_sum(self, start: int, end: int) -> int: ...
    def range_intersection(
        self, start1: int, end1: int, start2: int, end2: int
    ) -> List[Tuple[int, int, int]]: ...
    def range_freq(
        self, start: int, end: int, lower: Optional[int] = None, upper: Optional[int] = None
    ) -> int: ...
    def range_list(
        self, start: int, end: int, lower: Optional[int] = None, upper: Optional[int] = None
    ) -> List[Tuple[int, int]]: ...
    def range_maxk(
        self, start: int, end: int, k: Optional[int] = None
    ) -> List[Tuple[int, int]]: ...
    def range_mink(
        self, start: int, end: int, k: Optional[int] = None
    ) -> List[Tuple[int, int]]: ...
    def prev_value(
        self, start: int, end: int, lower: Optional[int] = None, upper: Optional[int] = None
    ) -> Optional[int]: ...
    def next_value(
        self, start: int, end: int, lower: Optional[int] = None, upper: Optional[int] = None
    ) -> Optional[int]: ...

class DynamicWaveletMatrix:
    def __init__(self, data: Iterable[int], max_bit: Optional[int] = None) -> None: ...
    def __getitem__(self, index: int) -> int: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> "DynamicWaveletMatrix": ...
    def __deepcopy__(self, memo) -> "DynamicWaveletMatrix": ...
    def values(self) -> List[int]: ...
    def access(self, index: int) -> int: ...
    def rank(self, value: int, end: int) -> int: ...
    def select(self, value: int, kth: int) -> Optional[int]: ...
    def quantile(self, start: int, end: int, kth: int) -> int: ...
    def topk(self, start: int, end: int, k: Optional[int] = None) -> List[Tuple[int, int]]: ...
    def range_sum(self, start: int, end: int) -> int: ...
    def range_intersection(
        self, start1: int, end1: int, start2: int, end2: int
    ) -> List[Tuple[int, int, int]]: ...
    def range_freq(
        self, start: int, end: int, lower: Optional[int] = None, upper: Optional[int] = None
    ) -> int: ...
    def range_list(
        self, start: int, end: int, lower: Optional[int] = None, upper: Optional[int] = None
    ) -> List[Tuple[int, int]]: ...
    def range_maxk(
        self, start: int, end: int, k: Optional[int] = None
    ) -> List[Tuple[int, int]]: ...
    def range_mink(
        self, start: int, end: int, k: Optional[int] = None
    ) -> List[Tuple[int, int]]: ...
    def prev_value(
        self, start: int, end: int, lower: Optional[int] = None, upper: Optional[int] = None
    ) -> Optional[int]: ...
    def next_value(
        self, start: int, end: int, lower: Optional[int] = None, upper: Optional[int] = None
    ) -> Optional[int]: ...
    def max_bit(self) -> int: ...
    def insert(self, index: int, value: int) -> None: ...
    def remove(self, index: int) -> int: ...
    def update(self, index: int, value: int) -> int: ...
