# coding: utf-8

"""
    public-api

    Public-facing API for external access

    The version of the OpenAPI document: 33585ef
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from knowledge_stack.models.resp_folder_contents import RespFolderContents

class TestRespFolderContents(unittest.TestCase):
    """RespFolderContents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RespFolderContents:
        """Test RespFolderContents
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RespFolderContents`
        """
        model = RespFolderContents()
        if include_optional:
            return RespFolderContents(
                folder_id = '',
                folders = [
                    knowledge_stack.models.resp_folder.RespFolder(
                        id = '', 
                        name = '', 
                        parent_id = '', 
                        folder_metadata = knowledge_stack.models.folder_metadata.FolderMetadata(), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tags = [
                            knowledge_stack.models.resp_tag.RespTag(
                                id = '', 
                                name = '', 
                                color = '', 
                                description = '', )
                            ], 
                        folder_path = '', 
                        document_count = 56, 
                        subfolder_count = 56, )
                    ],
                documents = [
                    null
                    ],
                folder_count = 56,
                document_count = 56,
                total_count = 56,
                limit = 56,
                offset = 56
            )
        else:
            return RespFolderContents(
        )
        """

    def testRespFolderContents(self):
        """Test RespFolderContents"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
