# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import alexasomba_paystack
from alexasomba_paystack.models.transfer_verify_response import TransferVerifyResponse  # noqa: E501
from alexasomba_paystack.rest import ApiException

class TestTransferVerifyResponse(unittest.TestCase):
    """TransferVerifyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TransferVerifyResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferVerifyResponse`
        """
        model = alexasomba_paystack.models.transfer_verify_response.TransferVerifyResponse()  # noqa: E501
        if include_optional :
            return TransferVerifyResponse(
                status = True, 
                message = '', 
                data = alexasomba_paystack.models.transfer_verify_response_data.TransferVerifyResponse_data(
                    amount = 56, 
                    created_at = '', 
                    currency = '', 
                    domain = '', 
                    failures = null, 
                    id = 56, 
                    integration = 56, 
                    reason = '', 
                    reference = '', 
                    source = '', 
                    source_details = null, 
                    status = '', 
                    titan_code = null, 
                    transfer_code = '', 
                    transferred_at = null, 
                    updated_at = '', 
                    recipient = alexasomba_paystack.models.transfer_verify_response_data_recipient.TransferVerifyResponse_data_recipient(
                        active = True, 
                        created_at = '', 
                        currency = '', 
                        description = '', 
                        domain = '', 
                        email = '', 
                        id = 56, 
                        integration = 56, 
                        metadata = alexasomba_paystack.models.metadata.metadata(), 
                        name = '', 
                        recipient_code = '', 
                        type = '', 
                        updated_at = '', 
                        is_deleted = True, 
                        details = alexasomba_paystack.models.transfer_verify_response_data_recipient_details.TransferVerifyResponse_data_recipient_details(
                            authorization_code = null, 
                            account_number = '', 
                            account_name = '', 
                            bank_code = '', 
                            bank_name = '', ), ), 
                    session = alexasomba_paystack.models.transfer_list_response_array_session.TransferListResponseArray_session(
                        provider = null, 
                        id = null, ), 
                    gateway_response = '', )
            )
        else :
            return TransferVerifyResponse(
                status = True,
                message = '',
                data = alexasomba_paystack.models.transfer_verify_response_data.TransferVerifyResponse_data(
                    amount = 56, 
                    created_at = '', 
                    currency = '', 
                    domain = '', 
                    failures = null, 
                    id = 56, 
                    integration = 56, 
                    reason = '', 
                    reference = '', 
                    source = '', 
                    source_details = null, 
                    status = '', 
                    titan_code = null, 
                    transfer_code = '', 
                    transferred_at = null, 
                    updated_at = '', 
                    recipient = alexasomba_paystack.models.transfer_verify_response_data_recipient.TransferVerifyResponse_data_recipient(
                        active = True, 
                        created_at = '', 
                        currency = '', 
                        description = '', 
                        domain = '', 
                        email = '', 
                        id = 56, 
                        integration = 56, 
                        metadata = alexasomba_paystack.models.metadata.metadata(), 
                        name = '', 
                        recipient_code = '', 
                        type = '', 
                        updated_at = '', 
                        is_deleted = True, 
                        details = alexasomba_paystack.models.transfer_verify_response_data_recipient_details.TransferVerifyResponse_data_recipient_details(
                            authorization_code = null, 
                            account_number = '', 
                            account_name = '', 
                            bank_code = '', 
                            bank_name = '', ), ), 
                    session = alexasomba_paystack.models.transfer_list_response_array_session.TransferListResponseArray_session(
                        provider = null, 
                        id = null, ), 
                    gateway_response = '', ),
        )
        """

    def testTransferVerifyResponse(self):
        """Test TransferVerifyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
