# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import alexasomba_paystack
from alexasomba_paystack.models.dedicated_nuban_deactivate_response_data import DedicatedNubanDeactivateResponseData  # noqa: E501
from alexasomba_paystack.rest import ApiException

class TestDedicatedNubanDeactivateResponseData(unittest.TestCase):
    """DedicatedNubanDeactivateResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DedicatedNubanDeactivateResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DedicatedNubanDeactivateResponseData`
        """
        model = alexasomba_paystack.models.dedicated_nuban_deactivate_response_data.DedicatedNubanDeactivateResponseData()  # noqa: E501
        if include_optional :
            return DedicatedNubanDeactivateResponseData(
                bank = alexasomba_paystack.models.dedicated_nuban_list_response_array_bank.DedicatedNubanListResponseArray_bank(
                    name = '', 
                    id = 56, 
                    slug = '', ), 
                account_name = '', 
                account_number = '', 
                assigned = True, 
                currency = '', 
                metadata = None, 
                active = True, 
                id = 56, 
                created_at = '', 
                updated_at = '', 
                assignment = alexasomba_paystack.models.dedicated_nuban_deactivate_response_data_assignment.DedicatedNubanDeactivateResponse_data_assignment(
                    assignee_id = 56, 
                    assignee_type = '', 
                    assigned_at = '', 
                    integration = 56, 
                    account_type = '', )
            )
        else :
            return DedicatedNubanDeactivateResponseData(
                bank = alexasomba_paystack.models.dedicated_nuban_list_response_array_bank.DedicatedNubanListResponseArray_bank(
                    name = '', 
                    id = 56, 
                    slug = '', ),
                account_name = '',
                account_number = '',
                assigned = True,
                currency = '',
                metadata = None,
                active = True,
                id = 56,
                created_at = '',
                updated_at = '',
                assignment = alexasomba_paystack.models.dedicated_nuban_deactivate_response_data_assignment.DedicatedNubanDeactivateResponse_data_assignment(
                    assignee_id = 56, 
                    assignee_type = '', 
                    assigned_at = '', 
                    integration = 56, 
                    account_type = '', ),
        )
        """

    def testDedicatedNubanDeactivateResponseData(self):
        """Test DedicatedNubanDeactivateResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
