# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import alexasomba_paystack
from alexasomba_paystack.models.verify_response_data_log import VerifyResponseDataLog  # noqa: E501
from alexasomba_paystack.rest import ApiException

class TestVerifyResponseDataLog(unittest.TestCase):
    """VerifyResponseDataLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VerifyResponseDataLog
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyResponseDataLog`
        """
        model = alexasomba_paystack.models.verify_response_data_log.VerifyResponseDataLog()  # noqa: E501
        if include_optional :
            return VerifyResponseDataLog(
                start_time = 56, 
                time_spent = 56, 
                attempts = 56, 
                errors = 56, 
                success = True, 
                mobile = True, 
                input = [
                    null
                    ], 
                history = [
                    alexasomba_paystack.models.verify_response_data_log_history_inner.VerifyResponse_data_log_history_inner(
                        type = '', 
                        message = '', 
                        time = 56, )
                    ]
            )
        else :
            return VerifyResponseDataLog(
                start_time = 56,
                time_spent = 56,
                attempts = 56,
                errors = 56,
                success = True,
                mobile = True,
                input = [
                    null
                    ],
                history = [
                    alexasomba_paystack.models.verify_response_data_log_history_inner.VerifyResponse_data_log_history_inner(
                        type = '', 
                        message = '', 
                        time = 56, )
                    ],
        )
        """

    def testVerifyResponseDataLog(self):
        """Test VerifyResponseDataLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
