# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intrepidcs/vspyx/rpc/Runtime/Value.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'intrepidcs/vspyx/rpc/Runtime/Value.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from intrepidcs.vspyx.rpc.Core import Numeric_pb2 as intrepidcs_dot_vspyx_dot_rpc_dot_Core_dot_Numeric__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(intrepidcs/vspyx/rpc/Runtime/Value.proto\x12\x1cintrepidcs.vspyx.rpc.Runtime\x1a\'intrepidcs/vspyx/rpc/Core/Numeric.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n\x05Value\x12\x35\n\x07Numeric\x18\x01 \x01(\x0b\x32\".intrepidcs.vspyx.rpc.Core.NumericH\x00\x12\x10\n\x06String\x18\x04 \x01(\tH\x00\x12\x0f\n\x05\x42ytes\x18\x05 \x01(\x0cH\x00\x12\x10\n\x06Object\x18\x06 \x01(\tH\x00\x12-\n\tTimestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07Invalid\x18\x08 \x01(\x08\x42\x06\n\x04\x44\x61taB\"Z intrepidcs.com/vspyx/rpc/runtimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intrepidcs.vspyx.rpc.Runtime.Value_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z intrepidcs.com/vspyx/rpc/runtime'
  _globals['_VALUE']._serialized_start=149
  _globals['_VALUE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
