import polars as pl

# Hand-made dataframe with the relations between départements, NUTS2, and NUTS1.
NUTS_DF = pl.DataFrame(
    [
        ["FR1", "Île-de-France", "FR10", "Île-de-France", "FR101", "75", "Paris"],
        ["FR1", "Île-de-France", "FR10", "Île-de-France", "FR102", "77", "Seine-et-Marne"],
        ["FR1", "Île-de-France", "FR10", "Île-de-France", "FR103", "78", "Yvelines"],
        ["FR1", "Île-de-France", "FR10", "Île-de-France", "FR104", "91", "Essonne"],
        ["FR1", "Île-de-France", "FR10", "Île-de-France", "FR105", "92", "Hauts-de-Seine"],
        ["FR1", "Île-de-France", "FR10", "Île-de-France", "FR106", "93", "Seine-Saint-Denis"],
        ["FR1", "Île-de-France", "FR10", "Île-de-France", "FR107", "94", "Val-de-Marne"],
        ["FR1", "Île-de-France", "FR10", "Île-de-France", "FR108", "95", "Val-d'Oise"],
        ["FRB", "Centre-Val de Loire", "FRB0", "Centre-Val de Loire", "FRB01", "18", "Cher"],
        ["FRB", "Centre-Val de Loire", "FRB0", "Centre-Val de Loire", "FRB02", "28", "Eure-et-Loir"],
        ["FRB", "Centre-Val de Loire", "FRB0", "Centre-Val de Loire", "FRB03", "36", "Indre"],
        ["FRB", "Centre-Val de Loire", "FRB0", "Centre-Val de Loire", "FRB04", "37", "Indre-et-Loire"],
        ["FRB", "Centre-Val de Loire", "FRB0", "Centre-Val de Loire", "FRB05", "41", "Loir-et-Cher"],
        ["FRB", "Centre-Val de Loire", "FRB0", "Centre-Val de Loire", "FRB06", "45", "Loiret"],
        ["FRC", "Bourgogne-Franche-Comté", "FRC1", "Bourgogne", "FRC11", "21", "Côte-d'Or"],
        ["FRC", "Bourgogne-Franche-Comté", "FRC1", "Bourgogne", "FRC12", "58", "Nièvre"],
        ["FRC", "Bourgogne-Franche-Comté", "FRC1", "Bourgogne", "FRC13", "71", "Saône-et-Loire"],
        ["FRC", "Bourgogne-Franche-Comté", "FRC1", "Bourgogne", "FRC14", "89", "Yonne"],
        ["FRC", "Bourgogne-Franche-Comté", "FRC2", "Franche-Comté", "FRC21", "25", "Doubs"],
        ["FRC", "Bourgogne-Franche-Comté", "FRC2", "Franche-Comté", "FRC22", "39", "Jura"],
        ["FRC", "Bourgogne-Franche-Comté", "FRC2", "Franche-Comté", "FRC23", "70", "Haute-Saône"],
        ["FRC", "Bourgogne-Franche-Comté", "FRC2", "Franche-Comté", "FRC25", "90", "Territoire de Belfort"],
        ["FRD", "Normandie", "FRD1", "Basse-Normandie", "FRD11", "14", "Calvados"],
        ["FRD", "Normandie", "FRD1", "Basse-Normandie", "FRD12", "50", "Manche"],
        ["FRD", "Normandie", "FRD1", "Basse-Normandie", "FRD13", "61", "Orne"],
        ["FRD", "Normandie", "FRD2", "Haute-Normandie", "FRD21", "27", "Eure"],
        ["FRD", "Normandie", "FRD2", "Haute-Normandie", "FRD22", "76", "Seine-Maritime"],
        ["FRE", "Hauts-de-France", "FRE1", "Nord-Pas-de-Calais", "FRE11", "59", "Nord"],
        ["FRE", "Hauts-de-France", "FRE1", "Nord-Pas-de-Calais", "FRE12", "62", "Pas-de-Calais"],
        ["FRE", "Hauts-de-France", "FRE2", "Picardie", "FRE21", "02", "Aisne"],
        ["FRE", "Hauts-de-France", "FRE2", "Picardie", "FRE22", "60", "Oise"],
        ["FRE", "Hauts-de-France", "FRE2", "Picardie", "FRE23", "80", "Somme"],
        ["FRF", "Grand Est", "FRF1", "Alsace", "FRF11", "67", "Bas-Rhin"],
        ["FRF", "Grand Est", "FRF1", "Alsace", "FRF12", "68", "Haut-Rhin"],
        ["FRF", "Grand Est", "FRF2", "Champagne-Ardenne", "FRF21", "08", "Ardennes"],
        ["FRF", "Grand Est", "FRF2", "Champagne-Ardenne", "FRF22", "10", "Aube"],
        ["FRF", "Grand Est", "FRF2", "Champagne-Ardenne", "FRF23", "51", "Marne"],
        ["FRF", "Grand Est", "FRF2", "Champagne-Ardenne", "FRF24", "52", "Haute-Marne"],
        ["FRF", "Grand Est", "FRF3", "Lorraine", "FRF31", "54", "Meurthe-et-Moselle"],
        ["FRF", "Grand Est", "FRF3", "Lorraine", "FRF32", "55", "Meuse"],
        ["FRF", "Grand Est", "FRF3", "Lorraine", "FRF33", "57", "Moselle"],
        ["FRF", "Grand Est", "FRF3", "Lorraine", "FRF34", "88", "Vosges"],
        ["FRG", "Pays de la Loire", "FRG0", "Pays de la Loire", "FRG01", "44", "Loire-Atlantique"],
        ["FRG", "Pays de la Loire", "FRG0", "Pays de la Loire", "FRG02", "49", "Maine-et-Loire"],
        ["FRG", "Pays de la Loire", "FRG0", "Pays de la Loire", "FRG03", "53", "Mayenne"],
        ["FRG", "Pays de la Loire", "FRG0", "Pays de la Loire", "FRG04", "72", "Sarthe"],
        ["FRG", "Pays de la Loire", "FRG0", "Pays de la Loire", "FRG05", "85", "Vendée"],
        ["FRH", "Bretagne", "FRH0", "Bretagne", "FRH01", "22", "Côtes-d'Armor"],
        ["FRH", "Bretagne", "FRH0", "Bretagne", "FRH02", "29", "Finistère"],
        ["FRH", "Bretagne", "FRH0", "Bretagne", "FRH03", "35", "Ille-et-Vilaine"],
        ["FRH", "Bretagne", "FRH0", "Bretagne", "FRH04", "56", "Morbihan"],
        ["FRI", "Nouvelle-Aquitaine", "FRI1", "Aquitaine", "FRI11", "24", "Dordogne"],
        ["FRI", "Nouvelle-Aquitaine", "FRI1", "Aquitaine", "FRI12", "33", "Gironde"],
        ["FRI", "Nouvelle-Aquitaine", "FRI1", "Aquitaine", "FRI13", "40", "Landes"],
        ["FRI", "Nouvelle-Aquitaine", "FRI1", "Aquitaine", "FRI14", "47", "Lot-et-Garonne"],
        ["FRI", "Nouvelle-Aquitaine", "FRI1", "Aquitaine", "FRI15", "64", "Pyrénées-Atlantiques"],
        ["FRI", "Nouvelle-Aquitaine", "FRI2", "Limousin", "FRI21", "19", "Corrèze"],
        ["FRI", "Nouvelle-Aquitaine", "FRI2", "Limousin", "FRI22", "23", "Creuse"],
        ["FRI", "Nouvelle-Aquitaine", "FRI2", "Limousin", "FRI23", "87", "Haute-Vienne"],
        ["FRI", "Nouvelle-Aquitaine", "FRI3", "Poitou-Charentes", "FRI31", "16", "Charente"],
        ["FRI", "Nouvelle-Aquitaine", "FRI3", "Poitou-Charentes", "FRI32", "17", "Charente-Maritime"],
        ["FRI", "Nouvelle-Aquitaine", "FRI3", "Poitou-Charentes", "FRI33", "79", "Deux-Sèvres"],
        ["FRI", "Nouvelle-Aquitaine", "FRI3", "Poitou-Charentes", "FRI34", "86", "Vienne"],
        ["FRJ", "Occitanie", "FRJ1", "Languedoc-Roussillon", "FRJ11", "11", "Aude"],
        ["FRJ", "Occitanie", "FRJ1", "Languedoc-Roussillon", "FRJ12", "30", "Gard"],
        ["FRJ", "Occitanie", "FRJ1", "Languedoc-Roussillon", "FRJ13", "34", "Hérault"],
        ["FRJ", "Occitanie", "FRJ1", "Languedoc-Roussillon", "FRJ14", "48", "Lozère"],
        ["FRJ", "Occitanie", "FRJ1", "Languedoc-Roussillon", "FRJ15", "66", "Pyrénées-Orientales"],
        ["FRJ", "Occitanie", "FRJ2", "Midi-Pyrénées", "FRJ21", "09", "Ariège"],
        ["FRJ", "Occitanie", "FRJ2", "Midi-Pyrénées", "FRJ22", "12", "Aveyron"],
        ["FRJ", "Occitanie", "FRJ2", "Midi-Pyrénées", "FRJ23", "31", "Haute-Garonne"],
        ["FRJ", "Occitanie", "FRJ2", "Midi-Pyrénées", "FRJ24", "32", "Gers"],
        ["FRJ", "Occitanie", "FRJ2", "Midi-Pyrénées", "FRJ25", "46", "Lot"],
        ["FRJ", "Occitanie", "FRJ2", "Midi-Pyrénées", "FRJ26", "65", "Hautes-Pyrénées"],
        ["FRJ", "Occitanie", "FRJ2", "Midi-Pyrénées", "FRJ27", "81", "Tarn"],
        ["FRJ", "Occitanie", "FRJ2", "Midi-Pyrénées", "FRJ28", "82", "Tarn-et-Garonne"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK1", "Auvergne", "FRK11", "03", "Allier"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK1", "Auvergne", "FRK12", "15", "Cantal"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK1", "Auvergne", "FRK13", "43", "Haute-Loire"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK1", "Auvergne", "FRK14", "63", "Puy-de-Dôme"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK2", "Rhône-Alpes", "FRK21", "01", "Ain"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK2", "Rhône-Alpes", "FRK22", "07", "Ardèche"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK2", "Rhône-Alpes", "FRK23", "26", "Drôme"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK2", "Rhône-Alpes", "FRK24", "38", "Isère"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK2", "Rhône-Alpes", "FRK25", "42", "Loire"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK2", "Rhône-Alpes", "FRK26", "69", "Rhône"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK2", "Rhône-Alpes", "FRK27", "73", "Savoie"],
        ["FRK", "Auvergne-Rhône-Alpes", "FRK2", "Rhône-Alpes", "FRK28", "74", "Haute-Savoie"],
        ["FRL", "Provence-Alpes-Côte d'Azur", "FRL0", "Provence-Alpes-Côte d'Azur", "FRL01", "04", "Alpes-de-Haute-Provence"],
        ["FRL", "Provence-Alpes-Côte d'Azur", "FRL0", "Provence-Alpes-Côte d'Azur", "FRL02", "05", "Hautes-Alpes"],
        ["FRL", "Provence-Alpes-Côte d'Azur", "FRL0", "Provence-Alpes-Côte d'Azur", "FRL03", "06", "Alpes-Maritimes"],
        ["FRL", "Provence-Alpes-Côte d'Azur", "FRL0", "Provence-Alpes-Côte d'Azur", "FRL04", "13", "Bouches-du-Rhône"],
        ["FRL", "Provence-Alpes-Côte d'Azur", "FRL0", "Provence-Alpes-Côte d'Azur", "FRL05", "83", "Var"],
        ["FRL", "Provence-Alpes-Côte d'Azur", "FRL0", "Provence-Alpes-Côte d'Azur", "FRL06", "84", "Vaucluse"],
        ["FRM", "Corse", "FRM0", "Corse", "FRM01", "2A", "Corse-du-Sud"],
        ["FRM", "Corse", "FRM0", "Corse", "FRM02", "2B", "Haute-Corse"],
        ["FRY", "Départements d'Outre Mer", "FRY1", "Guadeloupe", "FRY10", "971", "Guadeloupe"],
        ["FRY", "Départements d'Outre Mer", "FRY2", "Martinique", "FRY20", "972", "Martinique"],
        ["FRY", "Départements d'Outre Mer", "FRY3", "Guyane", "FRY30", "973", "Guyane"],
        ["FRY", "Départements d'Outre Mer", "FRY4", "La Réunion", "FRY40", "974", "La Réunion"],
        ["FRY", "Départements d'Outre Mer", "FRY5", "Mayotte", "FRY50", "976", "Mayotte"],
    ],
    schema=["NUTS1", "NUTS1_name", "NUTS2", "NUTS2_name", "NUTS3", "dep_code", "dep_name"],
    orient="row",
)  # fmt: skip


def add_nuts_data(lf: pl.LazyFrame, prefix: str):
    """Given a LazyFrame with a "{prefix}_dep" column, adds the corresponding "dep_name", "NUTS1",
    "NUTS1_name", "NUTS2", and "NUTS2_name" columns.
    """
    dep_col = f"{prefix}_dep"
    # Add NUTS data.
    lf = lf.join(NUTS_DF.lazy(), left_on=dep_col, right_on="dep_code", how="left")
    lf = lf.rename(
        {
            "dep_name": f"{prefix}_dep_name",
            "NUTS1": f"{prefix}_nuts1",
            "NUTS2": f"{prefix}_nuts2",
            "NUTS1_name": f"{prefix}_nuts1_name",
            "NUTS2_name": f"{prefix}_nuts2_name",
        }
    )
    return lf
