# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intrepidcs/vspyx/rpc/Frames/Source.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'intrepidcs/vspyx/rpc/Frames/Source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from intrepidcs.vspyx.rpc.Frames import Driver_pb2 as intrepidcs_dot_vspyx_dot_rpc_dot_Frames_dot_Driver__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(intrepidcs/vspyx/rpc/Frames/Source.proto\x12\x1bintrepidcs.vspyx.rpc.Frames\x1a(intrepidcs/vspyx/rpc/Frames/Driver.proto\"\xc0\x02\n\x06Source\x12\x19\n\x11SourceDescription\x18\x01 \x01(\t\x12\x39\n\x05State\x18\x03 \x01(\x0e\x32*.intrepidcs.vspyx.rpc.Frames.Source.EState\x12\x12\n\nTypeString\x18\x04 \x01(\t\x12\x1e\n\x16UniqueIdentifierString\x18\x05 \x01(\t\x12\x34\n\x07\x44rivers\x18\x06 \x03(\x0b\x32#.intrepidcs.vspyx.rpc.Frames.Driver\"v\n\x06\x45State\x12\x11\n\rUninitialized\x10\x00\x12\x0c\n\x08NotReady\x10\x01\x12\t\n\x05Ready\x10\x02\x12\x0b\n\x07Opening\x10\x03\x12\x08\n\x04Open\x10\x04\x12\n\n\x06Online\x10\x05\x12\x0b\n\x07\x43losing\x10\x06\x12\x10\n\x0c\x44isconnected\x10\x07\x42!Z\x1fintrepidcs.com/vspyx/rpc/framesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intrepidcs.vspyx.rpc.Frames.Source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037intrepidcs.com/vspyx/rpc/frames'
  _globals['_SOURCE']._serialized_start=116
  _globals['_SOURCE']._serialized_end=436
  _globals['_SOURCE_ESTATE']._serialized_start=318
  _globals['_SOURCE_ESTATE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
