
import base64
DATA_B64 = "ewrCoCDCoCDCoCDCoCAib2JqZWN0cyI6IFsKwqAgwqAgwqAgwqAgwqAgwqAgIlTDoHUgbmdoacOqbiBj4bupdSwga2jhuqNvIHPDoXQiCsKgIMKgIMKgIMKgIF0sCsKgIMKgIMKgIMKgICJwYXNzYWdlIjogIklJLiBWw5lORyBCSeG7gk5cbjMuIFbDuW5nIGJp4buDbiBUcsaw4budbmcgU2EsIERLSSB2w6AgcGjDrWEgTmFtXG5hKSBUw6B1IFRydW5nIFF14buRY1xuLSBUw6B1IG5naGnDqm4gY+G7qXUsIGto4bqjbyBzw6F0ICgwNCB0w6B1KTpcbisgVMOgdSBIREgtMTAgKyAwNyB0w6B1IGLhuqNvIHbhu4cgdGnhur9wIHThu6VjIHTDoWMgbmdoaeG7h3AgdHV54bq/biAxNyB0aGVvIGjGsOG7m25nIFRCLCBMw7pjIDIzLjAwIOG7nyDEkEIgcGjDuiBxdcO9IDE1MGhsOyDEkeG6v24gMDUuMDAgbmfDoHkgMzEvNSBjw6FjaCDEkEIgUGjDuiBRdcO9IDEyMGhsLCDEkWkgc8OidSB2w6BvIFTDonkgxJBRS1QgMTEyaGw7IDAzIHTDoHUgY+G7p2EgVGEgKEtOLTQ2NSwgNDY4LCBDU0IgNjAxMSkgYsOhbSB0dXnDqm4gdHJ1eeG7gW4gxJHhuqV1IHRyYW5oIDc5IGzGsOG7o3Q7IFRRIHBo4bqjbiB0dXnDqm4gdHJ1eeG7gW4gMDkgbMaw4bujdC4iLArCoCDCoCDCoCDCoCAiY29vcnMiOiBbCsKgIMKgIMKgIMKgIMKgIMKgIFsKwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgMTEwLjc1MTE4NSwKwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgMTIuMjg2Njc0CsKgIMKgIMKgIMKgIMKgIMKgIF0sCsKgIMKgIMKgIMKgIMKgIMKgIFsKwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgMTEwLjM4NzgxOCwKwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgMTEuOTM1MzMzCsKgIMKgIMKgIMKgIMKgIMKgIF0KwqAgwqAgwqAgwqAgXSwKwqAgwqAgwqAgwqAgImxvY3MiOiBbCsKgIMKgIMKgIMKgIMKgIMKgICLEkEIgUGjDuiBRdcO9IDE1MGhsIiwKwqAgwqAgwqAgwqAgwqAgwqAgIsSQQiBQaMO6IFF1w70gMTIwaGwiCsKgIMKgIMKgIMKgIF0sCsKgIMKgIMKgIMKgICJvYmplY3RfYWN0aW9uIjogInN1cnZleSIsCsKgIMKgIMKgIMKgICJzZXZlcml0eSI6ICJtZWRpdW0iLArCoCDCoCDCoCDCoCAicmVhc29uIjogIlTDoHUgbmdoacOqbiBj4bupdSwga2jhuqNvIHPDoXQga2jhuqNvIHPDoXQgdHLDoWkgcGjDqXAgdsO5bmcgxJHhurdjIHF1eeG7gW4ga2luaCB04bq/IGPhu6dhIFZp4buHdCBOYW0gdOG6oWkgxJBCIFBow7ogUXXDvSAxNTBobCzEkEIgUGjDuiBRdcO9IDEyMGhsOlxuQ8OzIHRow7RuZyB0aW4gduG7gSAwMyB0w6B1IGPhu6dhIFRhIChLTi00NjUsIDQ2OCwgQ1NCIDYwMTEpIGLDoW0gdHV5w6puIHRydXnhu4FuIMSR4bqldSB0cmFuaC4iCsKgIMKgIH0="
def save(filename="code_moi_ve.py"):
    try:
        decoded = base64.b64decode(DATA_B64).decode("utf-8")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(decoded)
        print(f"OK: Da luu code vao {filename}")
    except Exception as e:
        print(f"LOI: {e}")
