# (c) 2025 Mario Sieg. <mario.sieg.64@gmail.com>

set(MAG_ENABLE_COLOR OFF)

function(pad_text text width out)
    string(LENGTH "${text}" _len)
    math(EXPR _pad "(${width}) - ${_len}")
    if (_pad GREATER 0)
        string(REPEAT " " ${_pad} _spaces)
    else()
        set(_spaces "")
    endif()
    set(${out} "${text}${_spaces}" PARENT_SCOPE)
endfunction()

function(mag_print_cpu_backend_summary)
    if(MAG_ENABLE_COLOR)
        set(CLR_RESET  "\\033[0m")
        set(CLR_GREEN  "\\033[1;32m")
        set(CLR_YELLOW "\\033[1;33m")
        set(CLR_CYAN   "\\033[1;36m")
        set(CLR_DIM    "\\033[2m")
    else()
        set(CLR_RESET  "")
        set(CLR_GREEN  "")
        set(CLR_YELLOW "")
        set(CLR_CYAN   "")
        set(CLR_DIM    "")
    endif()
    set(H1 "Backend")
    set(H2 "Source")
    set(H3 "POSIX Flags")
    set(H4 "MSVC Flags")
    set(H5 "Status")
    set(H6 "Note")
    string(LENGTH "${H1}" W1)
    string(LENGTH "${H2}" W2)
    string(LENGTH "${H3}" W3)
    string(LENGTH "${H4}" W4)
    string(LENGTH "${H5}" W5)
    string(LENGTH "${H6}" W6)
    foreach(row IN LISTS MAG_BACKEND_ROWS)
        string(REPLACE "::" ";" F "${row}")
        list(GET F 0 C1)
        list(GET F 1 C2)
        list(GET F 2 C3)
        list(GET F 3 C4)
        list(GET F 4 C5)
        list(GET F 5 C6)
        string(LENGTH "${C1}" L1)
        string(LENGTH "${C2}" L2)
        string(LENGTH "${C3}" L3)
        string(LENGTH "${C4}" L4)
        string(LENGTH "${C5}" L5)
        string(LENGTH "${C6}" L6)
        if (L1 GREATER W1)
            set(W1 ${L1})
        endif()
        if (L2 GREATER W2)
            set(W2 ${L2})
        endif()
        if (L3 GREATER W3)
            set(W3 ${L3})
        endif()
        if (L4 GREATER W4)
            set(W4 ${L4})
        endif()
        if (L5 GREATER W5)
            set(W5 ${L5})
        endif()
        if (L6 GREATER W6)
            set(W6 ${L6})
        endif()
    endforeach()
    function(pad_text text width out)
        string(LENGTH "${text}" _len)
        math(EXPR _pad "(${width}) - ${_len}")
        if (_pad GREATER 0)
            string(REPEAT " " ${_pad} _spaces)
        else()
            set(_spaces "")
        endif()
        set(${out} "${text}${_spaces}" PARENT_SCOPE)
    endfunction()
    math(EXPR HRLEN "${W1}+${W2}+${W3}+${W4}+${W5}+${W6}+19")
    string(REPEAT "-" ${HRLEN} HR)
    pad_text("${H1}" ${W1} P1)
    pad_text("${H2}" ${W2} P2)
    pad_text("${H3}" ${W3} P3)
    pad_text("${H4}" ${W4} P4)
    pad_text("${H5}" ${W5} P5)
    pad_text("${H6}" ${W6} P6)
    message(STATUS "")
    message(STATUS "${CLR_CYAN}================ CPU Backend Summary ================${CLR_RESET}")
    message(STATUS "${CLR_DIM}${HR}${CLR_RESET}")
    message(STATUS "${CLR_DIM}|${CLR_RESET} ${P1} ${CLR_DIM}|${CLR_RESET} ${P2} ${CLR_DIM}|${CLR_RESET} ${P3} ${CLR_DIM}|${CLR_RESET} ${P4} ${CLR_DIM}|${CLR_RESET} ${P5} ${CLR_DIM}|${CLR_RESET} ${P6} ${CLR_DIM}|${CLR_RESET}")
    message(STATUS "${CLR_DIM}${HR}${CLR_RESET}")
    foreach(row IN LISTS MAG_BACKEND_ROWS)
        string(REPLACE "::" ";" F "${row}")
        list(GET F 0 C1)
        list(GET F 1 C2)
        list(GET F 2 C3)
        list(GET F 3 C4)
        list(GET F 4 C5)
        list(GET F 5 C6)
        pad_text("${C1}" ${W1} P1)
        pad_text("${C2}" ${W2} P2)
        pad_text("${C3}" ${W3} P3)
        pad_text("${C4}" ${W4} P4)
        pad_text("${C5}" ${W5} P5)
        pad_text("${C6}" ${W6} P6)
        if (C5 STREQUAL "Built")
            set(C5_CLR "${CLR_GREEN}${C5}${CLR_RESET}")
        else()
            set(C5_CLR "${CLR_YELLOW}${C5}${CLR_RESET}")
        endif()
        message(STATUS "${CLR_DIM}|${CLR_RESET} ${P1} ${CLR_DIM}|${CLR_RESET} ${P2} ${CLR_DIM}|${CLR_RESET} ${P3} ${CLR_DIM}|${CLR_RESET} ${P4} ${CLR_DIM}|${CLR_RESET} ${C5_CLR} ${CLR_DIM}|${CLR_RESET} ${P6} ${CLR_DIM}|${CLR_RESET}")
    endforeach()
    message(STATUS "${CLR_DIM}${HR}${CLR_RESET}")
    set(_total 0)
    set(_built 0)
    foreach(row IN LISTS MAG_BACKEND_ROWS)
        math(EXPR _total "${_total}+1")
        string(REPLACE "::" ";" _F "${row}")
        list(GET _F 4 _status)
        if (_status STREQUAL "Built")
            math(EXPR _built "${_built}+1")
        endif()
    endforeach()
    math(EXPR _skipped "${_total}-${_built}")
    if (_total GREATER 0)
        math(EXPR _pct "(${_built}*100 + ${_total}/2) / ${_total}")
    else()
        set(_pct 0)
    endif()
    message(STATUS "CPU specializations built: ${_built}/${_total} (${_pct}%)")
    if (_skipped GREATER 0)
        set(_skipped_names "")
        foreach(row IN LISTS MAG_BACKEND_ROWS)
            string(REPLACE "::" ";" _F "${row}")
            list(GET _F 0 _name)
            list(GET _F 4 _status)
            if (NOT _status STREQUAL "Built")
                list(APPEND _skipped_names "${_name}")
            endif()
        endforeach()
        if (_skipped_names)
            list(JOIN _skipped_names ", " _skipped_str)
            message(STATUS "Skipped backends: ${_skipped_str}")
        endif()
        message(WARNING "Only ${_built}/${_total} CPU backends compiled. " "Upgrade your compiler (GCC/Clang/MSVC) to enable newer -march targets.")
    endif()
    message(STATUS "")
endfunction()
