# src/serger/config/__init__.py

"""Configuration handling for serger.

This module provides configuration loading, parsing, validation, and resolution.
"""

from .config_loader import (
    can_run_configless,
    find_config,
    load_and_validate_config,
    load_config,
    parse_config,
)
from .config_resolve import (
    PyprojectMetadata,
    extract_pyproject_metadata,
    resolve_build_config,
    resolve_config,
    resolve_post_processing,
)
from .config_types import (
    CommentsMode,
    DocstringMode,
    DocstringModeLocation,
    DocstringModeSimple,
    ExternalImportMode,
    IncludeConfig,
    IncludeResolved,
    InternalImportMode,
    MainMode,
    MetaBuildConfigResolved,
    ModuleActionAffects,
    ModuleActionCleanup,
    ModuleActionFull,
    ModuleActionMode,
    ModuleActions,
    ModuleActionScope,
    ModuleActionSimple,
    ModuleActionType,
    ModuleMode,
    OriginType,
    PathResolved,
    PostCategoryConfig,
    PostCategoryConfigResolved,
    PostProcessingConfig,
    PostProcessingConfigResolved,
    RootConfig,
    RootConfigResolved,
    ShimSetting,
    StitchMode,
    ToolConfig,
    ToolConfigResolved,
)
from .config_validate import (
    DRYRUN_KEYS,
    DRYRUN_MSG,
    FIELD_EXAMPLES,
    ROOT_ONLY_KEYS,
    ROOT_ONLY_MSG,
    SchemaErrorAggregator,
    ValidationSummary,
    validate_config,
)


__all__ = [  # noqa: RUF022
    # config_loader
    "can_run_configless",
    "find_config",
    "load_and_validate_config",
    "load_config",
    "parse_config",
    # config_resolve
    "PyprojectMetadata",
    "extract_pyproject_metadata",
    "resolve_build_config",
    "resolve_config",
    "resolve_post_processing",
    # config_types
    "CommentsMode",
    "DocstringMode",
    "DocstringModeLocation",
    "DocstringModeSimple",
    "ExternalImportMode",
    "IncludeConfig",
    "IncludeResolved",
    "InternalImportMode",
    "MainMode",
    "MetaBuildConfigResolved",
    "ModuleActionAffects",
    "ModuleActionCleanup",
    "ModuleActionFull",
    "ModuleActionMode",
    "ModuleActionScope",
    "ModuleActionSimple",
    "ModuleActionType",
    "ModuleActions",
    "ModuleMode",
    "OriginType",
    "PathResolved",
    "PostCategoryConfig",
    "PostCategoryConfigResolved",
    "PostProcessingConfig",
    "PostProcessingConfigResolved",
    "RootConfig",
    "RootConfigResolved",
    "ShimSetting",
    "StitchMode",
    "ToolConfig",
    "ToolConfigResolved",
    # config_validate
    "DRYRUN_KEYS",
    "DRYRUN_MSG",
    "FIELD_EXAMPLES",
    "ROOT_ONLY_KEYS",
    "ROOT_ONLY_MSG",
    "SchemaErrorAggregator",
    "ValidationSummary",
    "validate_config",
]
