"""Migrating db_conn schemas + replacing pickled DB schema fields

Revision ID: 50d76d243ce0
Revises: 34a183e32104
Create Date: 2024-10-23 09:57:26.879594

"""

import os
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from cryptography.fernet import Fernet

# revision identifiers, used by Alembic.
revision: str = "50d76d243ce0"
down_revision: Union[str, None] = "34a183e32104"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropping views since in some prior revisions some views weren't dropped and replace
    import json
    import pickle

    from basejump.core.database.crud.crud_utils import gen_client_id_suffixes
    from basejump.core.database.db_connect import ConnectDB, conn_params_noasync

    conn_db = ConnectDB(conn_params=conn_params_noasync)
    basejump_engine_noasync = conn_db.connect_db()
    suffixes = gen_client_id_suffixes(engine=basejump_engine_noasync, reverse=False, local_override=True)
    print("Running suffixes...", suffixes)
    for suffix in suffixes:
        print("Running suffix:", suffix)
        if not suffix or suffix == "0":
            continue
        # Drop the view
        op.execute(f"DROP VIEW connect{suffix}.db_conn")
    # For all rows in the database table, unpickle and then resave as JSON that has been converted to bytes
    # Use an update to set all schemas in db_conn to an empty list since no schemas needed to be resolved
    # TEST 241 is the last client created using the old pickling
    engine = conn_db.connect_db()
    with engine.connect() as conn:
        result = conn.execute(sa.text("select client_id, db_id, schemas from connect.database where client_id <= 152"))
        result_all = result.all()
    for row in result_all:
        f = Fernet(os.environ["ENCRYPTION_KEY"])
        bytes_value = f.decrypt(bytes(row.schemas))
        # deepcode ignore Deserialization: This is a migration file that removed pickle
        schemas = pickle.loads(bytes_value)
        if schemas:
            pass
            # breakpoint()  # Just want to see if there are actually any schemas and make sure they're converted correctly
        json_value = json.dumps(schemas)
        value = json_value.encode("UTF-8")
        value_encrypted = f.encrypt(value)
        op.execute(
            f"UPDATE connect.database SET schemas = decode('{value_encrypted.hex()}','hex') WHERE client_id = {row.client_id} and db_id = {row.db_id}"
        )
    op.execute("""UPDATE connect.db_conn SET schemas = '"[]"'::jsonb""")
    print("Adding views...")
    for suffix in suffixes:
        if not suffix or suffix == "0":
            continue
        # Create views
        for table in ["connect.db_conn"]:
            table_name_w_suffix = f"{table.split('.')[0] + suffix}.{table.split('.')[1]}"
            op.execute(
                f"""\
        CREATE VIEW {table_name_w_suffix} WITH(security_invoker=TRUE) AS \
        SELECT * FROM {table} \
        WHERE client_id = {suffix}"""
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
