# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.speos.file.v1 import file_transfer_pb2 as ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2


class FileTransferServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reserve = channel.unary_unary(
                '/ansys.api.speos.file.v1.FileTransferService/Reserve',
                request_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Reserve_Request.SerializeToString,
                response_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Reserve_Response.FromString,
                )
        self.Upload = channel.stream_unary(
                '/ansys.api.speos.file.v1.FileTransferService/Upload',
                request_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Chunk.SerializeToString,
                response_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Upload_Response.FromString,
                )
        self.Download = channel.unary_stream(
                '/ansys.api.speos.file.v1.FileTransferService/Download',
                request_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Download_Request.SerializeToString,
                response_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Chunk.FromString,
                )
        self.Delete = channel.unary_unary(
                '/ansys.api.speos.file.v1.FileTransferService/Delete',
                request_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Delete_Request.SerializeToString,
                response_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Delete_Response.FromString,
                )
        self.AddDependencies = channel.unary_unary(
                '/ansys.api.speos.file.v1.FileTransferService/AddDependencies',
                request_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.AddDependencies_Request.SerializeToString,
                response_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.AddDependencies_Response.FromString,
                )
        self.ListDependencies = channel.unary_unary(
                '/ansys.api.speos.file.v1.FileTransferService/ListDependencies',
                request_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.ListDependencies_Request.SerializeToString,
                response_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.ListDependencies_Response.FromString,
                )


class FileTransferServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Reserve(self, request, context):
        """Reserve a FileSystemItem
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upload(self, request_iterator, context):
        """Upload a file 
        Mandatory Client's Metadata:
        key: "file-size" - value: size of the file in bytes
        Optional Client's Metadata:
        key: "reserved-file-uri" - value: FileSystemItem reserved uri
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Download a FileSystemItem
        Server's' Initial Metadata:
        key: "file-size" - value: size of the file in bytes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete a FileSystemItem
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDependencies(self, request, context):
        """Add dependencies to a FileSystemItem
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDependencies(self, request, context):
        """List all dependencies of a FileSystemItem
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.Reserve,
                    request_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Reserve_Request.FromString,
                    response_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Reserve_Response.SerializeToString,
            ),
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Chunk.FromString,
                    response_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Upload_Response.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Download_Request.FromString,
                    response_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Chunk.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Delete_Request.FromString,
                    response_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Delete_Response.SerializeToString,
            ),
            'AddDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDependencies,
                    request_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.AddDependencies_Request.FromString,
                    response_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.AddDependencies_Response.SerializeToString,
            ),
            'ListDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDependencies,
                    request_deserializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.ListDependencies_Request.FromString,
                    response_serializer=ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.ListDependencies_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.speos.file.v1.FileTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileTransferService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.speos.file.v1.FileTransferService/Reserve',
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Reserve_Request.SerializeToString,
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Reserve_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ansys.api.speos.file.v1.FileTransferService/Upload',
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Chunk.SerializeToString,
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Upload_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ansys.api.speos.file.v1.FileTransferService/Download',
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Download_Request.SerializeToString,
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.speos.file.v1.FileTransferService/Delete',
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Delete_Request.SerializeToString,
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.Delete_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.speos.file.v1.FileTransferService/AddDependencies',
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.AddDependencies_Request.SerializeToString,
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.AddDependencies_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.speos.file.v1.FileTransferService/ListDependencies',
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.ListDependencies_Request.SerializeToString,
            ansys_dot_api_dot_speos_dot_file_dot_v1_dot_file__transfer__pb2.ListDependencies_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
