# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intrepidcs/vspyx/rpc/Communication/DissectorProcessor.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'intrepidcs/vspyx/rpc/Communication/DissectorProcessor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;intrepidcs/vspyx/rpc/Communication/DissectorProcessor.proto\x12\"intrepidcs.vspyx.rpc.Communication\"b\n\rHijackingHook\x12\x10\n\x08Protocol\x18\x01 \x01(\t\x12\x12\n\nExpression\x18\x02 \x01(\t\x12\x11\n\tHijackTag\x18\x03 \x01(\t\x12\x18\n\x10PayloadAttribute\x18\x04 \x01(\t\"\x80\x01\n\rDissectorHook\x12\x0e\n\x04\x46ile\x18\x01 \x01(\tH\x00\x12\x10\n\x06\x44irect\x18\x02 \x01(\tH\x00\x12\x43\n\x06Hijack\x18\x03 \x01(\x0b\x32\x31.intrepidcs.vspyx.rpc.Communication.HijackingHookH\x00\x42\x08\n\x06Source\"V\n\x12\x44issectorProcessor\x12@\n\x05Hooks\x18\x01 \x03(\x0b\x32\x31.intrepidcs.vspyx.rpc.Communication.DissectorHookB(Z&intrepidcs.com/vspyx/rpc/communicationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intrepidcs.vspyx.rpc.Communication.DissectorProcessor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&intrepidcs.com/vspyx/rpc/communication'
  _globals['_HIJACKINGHOOK']._serialized_start=99
  _globals['_HIJACKINGHOOK']._serialized_end=197
  _globals['_DISSECTORHOOK']._serialized_start=200
  _globals['_DISSECTORHOOK']._serialized_end=328
  _globals['_DISSECTORPROCESSOR']._serialized_start=330
  _globals['_DISSECTORPROCESSOR']._serialized_end=416
# @@protoc_insertion_point(module_scope)
