ncharge = 109
nmass = 268

# ----------------------------------------------------------------------


class mendy(object):
    def __init__(self):
        self.name = "Undefined"
        self.element = "__"
        self.charge = 0.0
        self.mass = 0.0


# ----------------------------------------------------------------------


def create_table_mendeleiev():

    table_mendeleiev = [[mendy() for i in range(nmass + 1)] for j in range(ncharge + 1)]

    for icharge in range(ncharge + 1):
        for imass in range(nmass + 1):
            table_mendeleiev[icharge][imass].name = "Undefined"
            table_mendeleiev[icharge][imass].element = "__"

    table_mendeleiev[1][1].name = "Hydrogen"
    table_mendeleiev[1][2].name = "Deuterium"
    table_mendeleiev[1][3].name = "Tritium"

    table_mendeleiev[2][1].name = "Helium"
    table_mendeleiev[2][2].name = "Helium"
    table_mendeleiev[2][3].name = "Helium-3"
    table_mendeleiev[2][4].name = "Helium-4"

    for imass in range(nmass + 1):
        table_mendeleiev[3][imass].name = "Lithium"
        table_mendeleiev[4][imass].name = "Beryllium"
        table_mendeleiev[5][imass].name = "Boron"
        table_mendeleiev[6][imass].name = "Carbon"
        table_mendeleiev[7][imass].name = "Nitrogen"
        table_mendeleiev[8][imass].name = "Oxygen"
        table_mendeleiev[9][imass].name = "Fluorine"
        table_mendeleiev[10][imass].name = "Neon"
        table_mendeleiev[11][imass].name = "Sodium"
        table_mendeleiev[12][imass].name = "Magnesium"
        table_mendeleiev[13][imass].name = "Aluminium"
        table_mendeleiev[14][imass].name = "Silicon"
        table_mendeleiev[15][imass].name = "Phosphorus"
        table_mendeleiev[16][imass].name = "Sulphur"
        table_mendeleiev[17][imass].name = "Chlorine"
        table_mendeleiev[18][imass].name = "Argon"
        table_mendeleiev[19][imass].name = "Potassium"
        table_mendeleiev[20][imass].name = "Calcium"
        table_mendeleiev[21][imass].name = "Scandium"
        table_mendeleiev[22][imass].name = "Titanium"
        table_mendeleiev[23][imass].name = "Vanadium"
        table_mendeleiev[24][imass].name = "Chromium"
        table_mendeleiev[25][imass].name = "Manganese"
        table_mendeleiev[26][imass].name = "Iron"
        table_mendeleiev[27][imass].name = "Cobalt"
        table_mendeleiev[28][imass].name = "Nickel"
        table_mendeleiev[29][imass].name = "Copper"
        table_mendeleiev[30][imass].name = "Zinc"
        table_mendeleiev[31][imass].name = "Gallium"
        table_mendeleiev[32][imass].name = "Germanium"
        table_mendeleiev[33][imass].name = "Arsenic"
        table_mendeleiev[34][imass].name = "Selenium"
        table_mendeleiev[35][imass].name = "Bromine"
        table_mendeleiev[36][imass].name = "Krypton"
        table_mendeleiev[37][imass].name = "Rubidium"
        table_mendeleiev[38][imass].name = "Strontium"
        table_mendeleiev[39][imass].name = "Yttrium"
        table_mendeleiev[40][imass].name = "Zirconium"
        table_mendeleiev[41][imass].name = "Niobium"
        table_mendeleiev[42][imass].name = "Molybdenum"
        table_mendeleiev[43][imass].name = "Technetium"
        table_mendeleiev[44][imass].name = "Ruthenium"
        table_mendeleiev[45][imass].name = "Rhodium"
        table_mendeleiev[46][imass].name = "Palladium"
        table_mendeleiev[47][imass].name = "Silver"
        table_mendeleiev[48][imass].name = "Cadmium"
        table_mendeleiev[49][imass].name = "Indium"
        table_mendeleiev[50][imass].name = "Tin"
        table_mendeleiev[51][imass].name = "Antimony"
        table_mendeleiev[52][imass].name = "Tellurium"
        table_mendeleiev[53][imass].name = "Iodine"
        table_mendeleiev[54][imass].name = "Xenon"
        table_mendeleiev[55][imass].name = "Caesium"
        table_mendeleiev[56][imass].name = "Barium"
        table_mendeleiev[57][imass].name = "Lanthanum"
        table_mendeleiev[58][imass].name = "Cerium"
        table_mendeleiev[57][imass].name = "Lanthanum"
        table_mendeleiev[58][imass].name = "Cerium"
        table_mendeleiev[59][imass].name = "Praseodymium"
        table_mendeleiev[60][imass].name = "Neodymium"
        table_mendeleiev[61][imass].name = "Promethium"
        table_mendeleiev[62][imass].name = "Samarium"
        table_mendeleiev[63][imass].name = "Europium"
        table_mendeleiev[64][imass].name = "Gadolinium"
        table_mendeleiev[65][imass].name = "Terbium"
        table_mendeleiev[66][imass].name = "Dysprosium"
        table_mendeleiev[67][imass].name = "Holmium"
        table_mendeleiev[68][imass].name = "Erbium"
        table_mendeleiev[69][imass].name = "Thulium"
        table_mendeleiev[70][imass].name = "Ytterbium"
        table_mendeleiev[71][imass].name = "Lutetium"
        table_mendeleiev[72][imass].name = "Hafnium"
        table_mendeleiev[73][imass].name = "Tantalum"
        table_mendeleiev[74][imass].name = "Tungsten"
        table_mendeleiev[75][imass].name = "Rhenium"
        table_mendeleiev[76][imass].name = "Osmium"
        table_mendeleiev[77][imass].name = "Iridium"
        table_mendeleiev[78][imass].name = "Platinum"
        table_mendeleiev[79][imass].name = "Gold"
        table_mendeleiev[80][imass].name = "Mercury"
        table_mendeleiev[81][imass].name = "Thallium"
        table_mendeleiev[82][imass].name = "Lead"
        table_mendeleiev[83][imass].name = "Bismuth"
        table_mendeleiev[84][imass].name = "Polonium"
        table_mendeleiev[85][imass].name = "Astatine"
        table_mendeleiev[86][imass].name = "Radon"
        table_mendeleiev[87][imass].name = "Francium"
        table_mendeleiev[88][imass].name = "Radium"
        table_mendeleiev[89][imass].name = "Actinium"
        table_mendeleiev[90][imass].name = "Thorium"
        table_mendeleiev[91][imass].name = "Protactinium"
        table_mendeleiev[92][imass].name = "Uranium"
        table_mendeleiev[93][imass].name = "Neptunium"
        table_mendeleiev[94][imass].name = "Plutonium"
        table_mendeleiev[95][imass].name = "Americium"
        table_mendeleiev[96][imass].name = "Curium"
        table_mendeleiev[97][imass].name = "Berkelium"
        table_mendeleiev[98][imass].name = "Californium"
        table_mendeleiev[99][imass].name = "Einsteinium"
        table_mendeleiev[100][imass].name = "Fermium"
        table_mendeleiev[101][imass].name = "Mendelevium"
        table_mendeleiev[102][imass].name = "Nobelium"
        table_mendeleiev[103][imass].name = "Lawrencium"
        table_mendeleiev[104][imass].name = "Rutherfordium"
        table_mendeleiev[105][imass].name = "Dubnium"
        table_mendeleiev[106][imass].name = "Seaborgium"
        table_mendeleiev[107][imass].name = "Bohrium"
        table_mendeleiev[108][imass].name = "Hassium"
        table_mendeleiev[109][imass].name = "Meitnerium"

    table_mendeleiev[1][1].element = "H"
    table_mendeleiev[1][2].element = "D"
    table_mendeleiev[1][3].element = "T"

    table_mendeleiev[2][1].element = "He"
    table_mendeleiev[2][2].element = "He"
    table_mendeleiev[2][3].element = "He3"
    table_mendeleiev[2][4].element = "He4"

    for imass in range(nmass + 1):
        table_mendeleiev[3][imass].element = "Li"
        table_mendeleiev[4][imass].element = "Be"
        table_mendeleiev[5][imass].element = "B"
        table_mendeleiev[6][imass].element = "C"
        table_mendeleiev[7][imass].element = "N"
        table_mendeleiev[8][imass].element = "O"
        table_mendeleiev[9][imass].element = "F"
        table_mendeleiev[10][imass].element = "Ne"
        table_mendeleiev[11][imass].element = "Na"
        table_mendeleiev[12][imass].element = "Mg"
        table_mendeleiev[13][imass].element = "Al"
        table_mendeleiev[14][imass].element = "Si"
        table_mendeleiev[15][imass].element = "P"
        table_mendeleiev[16][imass].element = "S"
        table_mendeleiev[17][imass].element = "Cl"
        table_mendeleiev[18][imass].element = "Ar"
        table_mendeleiev[19][imass].element = "K"
        table_mendeleiev[20][imass].element = "Ca"
        table_mendeleiev[21][imass].element = "Sc"
        table_mendeleiev[22][imass].element = "Ti"
        table_mendeleiev[23][imass].element = "V"
        table_mendeleiev[24][imass].element = "Cr"
        table_mendeleiev[25][imass].element = "Mn"
        table_mendeleiev[26][imass].element = "Fe"
        table_mendeleiev[27][imass].element = "Co"
        table_mendeleiev[28][imass].element = "Ni"
        table_mendeleiev[29][imass].element = "Cu"
        table_mendeleiev[30][imass].element = "Zn"
        table_mendeleiev[31][imass].element = "Ga"
        table_mendeleiev[32][imass].element = "Ge"
        table_mendeleiev[33][imass].element = "As"
        table_mendeleiev[34][imass].element = "Se"
        table_mendeleiev[35][imass].element = "Br"
        table_mendeleiev[36][imass].element = "Kr"
        table_mendeleiev[37][imass].element = "Rb"
        table_mendeleiev[38][imass].element = "Sr"
        table_mendeleiev[39][imass].element = "Y"
        table_mendeleiev[40][imass].element = "Zr"
        table_mendeleiev[41][imass].element = "Nb"
        table_mendeleiev[42][imass].element = "Mo"
        table_mendeleiev[43][imass].element = "Tc"
        table_mendeleiev[44][imass].element = "Ru"
        table_mendeleiev[45][imass].element = "Rh"
        table_mendeleiev[46][imass].element = "Pd"
        table_mendeleiev[47][imass].element = "Ag"
        table_mendeleiev[48][imass].element = "Cd"
        table_mendeleiev[49][imass].element = "In"
        table_mendeleiev[50][imass].element = "Sn"
        table_mendeleiev[51][imass].element = "Sb"
        table_mendeleiev[52][imass].element = "Te"
        table_mendeleiev[53][imass].element = "I"
        table_mendeleiev[54][imass].element = "Xe"
        table_mendeleiev[55][imass].element = "Cs"
        table_mendeleiev[56][imass].element = "Ba"
        table_mendeleiev[57][imass].element = "La"
        table_mendeleiev[58][imass].element = "Ce"
        table_mendeleiev[57][imass].element = "La"
        table_mendeleiev[58][imass].element = "Ce"
        table_mendeleiev[59][imass].element = "Pr"
        table_mendeleiev[60][imass].element = "Nd"
        table_mendeleiev[61][imass].element = "Pm"
        table_mendeleiev[62][imass].element = "Sm"
        table_mendeleiev[63][imass].element = "Eu"
        table_mendeleiev[64][imass].element = "Gd"
        table_mendeleiev[65][imass].element = "Tb"
        table_mendeleiev[66][imass].element = "Dy"
        table_mendeleiev[67][imass].element = "Ho"
        table_mendeleiev[68][imass].element = "Er"
        table_mendeleiev[69][imass].element = "Tm"
        table_mendeleiev[70][imass].element = "Yb"
        table_mendeleiev[71][imass].element = "Lu"
        table_mendeleiev[72][imass].element = "Hf"
        table_mendeleiev[73][imass].element = "Ta"
        table_mendeleiev[74][imass].element = "W"
        table_mendeleiev[75][imass].element = "Re"
        table_mendeleiev[76][imass].element = "Os"
        table_mendeleiev[77][imass].element = "Ir"
        table_mendeleiev[78][imass].element = "Pt"
        table_mendeleiev[79][imass].element = "Au"
        table_mendeleiev[80][imass].element = "Hg"
        table_mendeleiev[81][imass].element = "Tl"
        table_mendeleiev[82][imass].element = "Pb"
        table_mendeleiev[83][imass].element = "Bi"
        table_mendeleiev[84][imass].element = "Po"
        table_mendeleiev[85][imass].element = "At"
        table_mendeleiev[86][imass].element = "Rn"
        table_mendeleiev[87][imass].element = "Fr"
        table_mendeleiev[88][imass].element = "Ra"
        table_mendeleiev[89][imass].element = "Ac"
        table_mendeleiev[90][imass].element = "Th"
        table_mendeleiev[91][imass].element = "Pa"
        table_mendeleiev[92][imass].element = "U"
        table_mendeleiev[93][imass].element = "Np"
        table_mendeleiev[94][imass].element = "Pu"
        table_mendeleiev[95][imass].element = "Am"
        table_mendeleiev[96][imass].element = "Cm"
        table_mendeleiev[97][imass].element = "Bk"
        table_mendeleiev[98][imass].element = "Cf"
        table_mendeleiev[99][imass].element = "Es"
        table_mendeleiev[100][imass].element = "Fm"
        table_mendeleiev[101][imass].element = "Md"
        table_mendeleiev[102][imass].element = "No"
        table_mendeleiev[103][imass].element = "Lr"
        table_mendeleiev[104][imass].element = "Rf"
        table_mendeleiev[105][imass].element = "Db"
        table_mendeleiev[106][imass].element = "Sg"
        table_mendeleiev[107][imass].element = "Bh"
        table_mendeleiev[108][imass].element = "Hs"
        table_mendeleiev[109][imass].element = "Mt"

    return table_mendeleiev


# ----------------------------------------------------------------------
