# instruction to render the output to JSON format
render = 'JSON'
source = 'national'

status_map = {
    '000': {'gbd': 'Delete', 'office': 'Indifferent'},
    '626': {'gbd': 'Delete', 'office': 'Dead/Cancelled'},

    '622': {'gbd': 'Other', 'office': 'Indifferent'},

    
    '401': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '400': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '402': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '403': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '404': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '405': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '406': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '411': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '412': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '414': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '415': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '416': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '417': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},

    '600': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '601': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '602': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '603': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '604': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '605': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '606': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '607': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '608': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '609': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '610': {'gbd': 'Ended', 'office': 'Dead'},
    '612': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '614': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '618': {'gbd': 'Ended', 'office': 'Dead/Abandoned'},
    '632': {'gbd': 'Ended', 'office': 'Dead'},

    '709': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '710': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '711': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '712': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '713': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '714': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '781': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},
    '782': {'gbd': 'Ended', 'office': 'Dead/Cancelled'},

    '700': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '701': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '702': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '703': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '704': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '705': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '706': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '707': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '708': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '717': {'gbd': 'Registered', 'office': 'Live'},
    '624': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '625': {'gbd': 'Registered', 'office': 'Live/Registered'},
    
    '778': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '780': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '790': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '739': {'gbd': 'Registered', 'office': 'Live/Registered'},
    '800': {'gbd': 'Registered', 'office': 'Live/Registered'},

    '410': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '413': {'gbd': 'Pending', 'office': 'Live/Pending'},

    '616': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '620': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '630': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '631': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '638': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '640': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '641': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '642': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '643': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '644': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '645': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '646': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '647': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '648': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '649': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '650': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '651': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '652': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '653': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '654': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '655': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '656': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '657': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '658': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '659': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '660': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '661': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '663': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '664': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '665': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '666': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '667': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '668': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '672': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '680': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '681': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '682': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '686': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '688': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '689': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '690': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '692': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '693': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '694': {'gbd': 'Pending', 'office': 'Live/Pending'},

    '718': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '719': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '720': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '721': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '722': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '724': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '725': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '730': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '731': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '732': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '733': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '734': {'gbd': 'Pending', 'office': 'Live/Pending'},

    '740': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '744': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '745': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '746': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '748': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '752': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '753': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '756': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '757': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '760': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '762': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '763': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '764': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '765': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '766': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '771': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '772': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '773': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '774': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '775': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '777': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '779': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '794': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '801': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '802': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '803': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '804': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '806': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '807': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '808': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '809': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '810': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '811': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '812': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '813': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '814': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '815': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '816': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '817': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '818': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '819': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '820': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '821': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '822': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '823': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '824': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '825': {'gbd': 'Pending', 'office': 'Live/Pending'},

    '715': {'gbd': 'Pending', 'office': 'Indifferent/Cancelled'},

    '900': {'gbd': 'Expired', 'office': 'Dead/Expired'},
    '901': {'gbd': 'Ended', 'office': 'Dead'},
    '968': {'gbd': 'Ended', 'office': 'Dead'},
    '969': {'gbd': 'Pending', 'office': 'Live/Pending'},
    '973': {'gbd': 'Unknown', 'office': 'Suspended Pending Administrative Review'}
    
}
