# -------------------------------------------------------------------
# This file was auto-generated. Do not edit directly.
# Generated by: StageGeneratorV2
# -------------------------------------------------------------------

"""This module defines the Change Apply stage."""

from ibm_watsonx_data_integration.services.datastage.models.flow.dag import StageNode
from ibm_watsonx_data_integration.services.datastage.models.stage_models.change_apply import change_apply
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ibm_watsonx_data_integration.services.datastage.models.flow.dag import DAG


class ChangeApplyStage(StageNode):
    """This class defines the Change Apply stage."""

    def __init__(self, dag: "DAG", configuration: change_apply = None, *, label: str = None) -> None:
        """Initializes an instance of a Change Apply stage."""
        super().__init__(dag, configuration=configuration, label=label)
        self.configuration: change_apply = configuration or change_apply()
