# -------------------------------------------------------------------
# This file was auto-generated. Do not edit directly.
# Generated by: StageGeneratorV2
# -------------------------------------------------------------------

"""This module defines the IBM Db2 on Cloud stage."""

from ibm_watsonx_data_integration.cpd_models.connections_model import Connection
from ibm_watsonx_data_integration.services.datastage.models.connections.db2cloud_connection import Db2cloudConn
from ibm_watsonx_data_integration.services.datastage.models.flow.dag import StageNode
from ibm_watsonx_data_integration.services.datastage.models.stage_models.db2cloud import db2cloud
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ibm_watsonx_data_integration.services.datastage.models.flow.dag import DAG


class IBMDb2OnCloudStage(StageNode):
    """This class defines the IBM Db2 on Cloud stage."""

    def __init__(self, dag: "DAG", configuration: db2cloud = None, *, label: str = None) -> None:
        """Initializes an instance of a IBM Db2 on Cloud stage."""
        super().__init__(dag, configuration=configuration, label=label)
        self.configuration: db2cloud = configuration or db2cloud()

    def use_connection(self, connection: Connection) -> None:
        """Adds a project-level connection to this connector stage."""
        self.configuration.connection = Db2cloudConn().from_connection(connection)
