# -------------------------------------------------------------------
# This file was auto-generated. Do not edit directly.
# Generated by: StageGeneratorV2
# -------------------------------------------------------------------

"""This module defines the Sequential file stage."""

from ibm_watsonx_data_integration.services.datastage.models.flow.dag import StageNode
from ibm_watsonx_data_integration.services.datastage.models.stage_models.sequentialfile import sequentialfile
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ibm_watsonx_data_integration.services.datastage.models.flow.dag import DAG


class SequentialFileStage(StageNode):
    """This class defines the Sequential file stage."""

    def __init__(self, dag: "DAG", configuration: sequentialfile = None, *, label: str = None) -> None:
        """Initializes an instance of a Sequential file stage."""
        super().__init__(dag, configuration=configuration, label=label)
        self.configuration: sequentialfile = configuration or sequentialfile()
