"""Pydantic models for the Apple Search Ads API.

This module exports all the data models used to interact with the
Apple Search Ads API. All models are Pydantic BaseModels with full
type hints and validation.
"""

from asa_api_client.models.ad_groups import (
    AdGroup,
    AdGroupCreate,
    AdGroupDisplayStatus,
    AdGroupServingStateReason,
    AdGroupServingStatus,
    AdGroupStatus,
    AdGroupUpdate,
    AutomatedKeywordsOptInStatus,
    CpaGoal,
    TargetingDimensions,
)
from asa_api_client.models.base import (
    Condition,
    ConditionOperator,
    Money,
    PageDetail,
    PaginatedResponse,
    Pagination,
    Selector,
    Sorting,
    SortOrder,
)
from asa_api_client.models.campaigns import (
    AdChannelType,
    BillingEvent,
    Campaign,
    CampaignCountryOrRegionServingStateReason,
    CampaignCreate,
    CampaignDisplayStatus,
    CampaignServingStateReason,
    CampaignServingStatus,
    CampaignStatus,
    CampaignSupplySource,
    CampaignUpdate,
)
from asa_api_client.models.keywords import (
    Keyword,
    KeywordCreate,
    KeywordMatchType,
    KeywordStatus,
    KeywordUpdate,
    NegativeKeyword,
    NegativeKeywordCreate,
)
from asa_api_client.models.reports import (
    GranularityType,
    ImpressionShareDateRange,
    ImpressionShareReport,
    ImpressionShareReportRequest,
    ImpressionShareReportRow,
    ImpressionShareReportStatus,
    ReportingRequest,
    ReportingResponse,
    ReportMetadata,
    ReportRow,
    SpendRow,
)

__all__ = [
    "AdChannelType",
    "AdGroup",
    "AdGroupCreate",
    "AdGroupDisplayStatus",
    "AdGroupServingStateReason",
    "AdGroupServingStatus",
    "AdGroupStatus",
    "AdGroupUpdate",
    "AutomatedKeywordsOptInStatus",
    "BillingEvent",
    "Campaign",
    "CampaignCountryOrRegionServingStateReason",
    "CampaignCreate",
    "CampaignDisplayStatus",
    "CampaignServingStateReason",
    "CampaignServingStatus",
    "CampaignStatus",
    "CampaignSupplySource",
    "CampaignUpdate",
    "Condition",
    "ConditionOperator",
    "CpaGoal",
    "GranularityType",
    "ImpressionShareDateRange",
    "ImpressionShareReport",
    "ImpressionShareReportRequest",
    "ImpressionShareReportRow",
    "ImpressionShareReportStatus",
    "Keyword",
    "KeywordCreate",
    "KeywordMatchType",
    "KeywordStatus",
    "KeywordUpdate",
    "Money",
    "NegativeKeyword",
    "NegativeKeywordCreate",
    "PageDetail",
    "PaginatedResponse",
    "Pagination",
    "ReportMetadata",
    "ReportRow",
    "ReportingRequest",
    "ReportingResponse",
    "Selector",
    "SortOrder",
    "Sorting",
    "SpendRow",
    "TargetingDimensions",
]
