# coding: utf-8

"""
    Backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NodeType(str, Enum):
    """
    NodeType
    """

    """
    allowed enum values
    """
    INPUTNODE = 'InputNode'
    OUTPUTNODE = 'OutputNode'
    LLMNODE = 'LLMNode'
    PYDANTICVALIDATORNODE = 'PydanticValidatorNode'
    REGEXNODE = 'RegExNode'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NodeType from a JSON string"""
        return cls(json.loads(json_str))


