"""CLI模板模块

包含所有用于项目初始化和代码生成的模板。

模板组织结构:
- project/: 项目初始化模板（pyproject.toml, .env, settings.py等）
- generators/: 代码生成模板（test, builder, repository, api_client等）
"""

# 导出所有项目模板
# 导出所有代码生成模板
from .generators import (
    ENV_BASE_TEMPLATE,
    ENV_DEV_TEMPLATE,
    ENV_EXAMPLE_TEMPLATE,
    ENV_PROD_TEMPLATE,
    ENV_TEST_TEMPLATE,
    GEN_API_CLIENT_TEMPLATE,
    GEN_BUILDER_TEMPLATE,
    GEN_REPOSITORY_TEMPLATE,
    GEN_TEST_COMPLETE_TEMPLATE,
    GEN_TEST_TEMPLATE,
    SETTINGS_ENHANCED_TEMPLATE,
)

# 导出增强功能模板（从project中导入）
from .project import (
    BASE_API_TEMPLATE,
    CONFTEST_TEMPLATE,
    CONSTANTS_ERROR_CODES_TEMPLATE,
    DATA_CLEANERS_TEMPLATE,
    DOCS_API_TEMPLATE,
    ENHANCED_GITIGNORE_TEMPLATE,
    ENV_TEMPLATE,
    FIXTURES_INIT_TEMPLATE,
    GITIGNORE_TEMPLATE,
    PYPROJECT_TOML_TEMPLATE,
    README_TEMPLATE,
    SCRIPT_RUN_TESTS_TEMPLATE,
    # API项目模板
    SETTINGS_TEMPLATE,
    TEST_EXAMPLE_TEMPLATE,
    UI_CONFTEST_TEMPLATE,
    UI_FIXTURES_INIT_TEMPLATE,
    UI_PAGE_OBJECT_TEMPLATE,
    # UI项目模板
    UI_SETTINGS_TEMPLATE,
    UI_TEST_EXAMPLE_TEMPLATE,
    UOW_TEMPLATE,  # v3.7.0+
    UTILS_CONVERTERS_TEMPLATE,
    UTILS_VALIDATORS_TEMPLATE,
)

__all__ = [
    # 基础配置文件
    "ENV_TEMPLATE",
    "GITIGNORE_TEMPLATE",
    "README_TEMPLATE",
    "PYPROJECT_TOML_TEMPLATE",
    # API项目模板
    "SETTINGS_TEMPLATE",
    "CONFTEST_TEMPLATE",
    "FIXTURES_INIT_TEMPLATE",
    "BASE_API_TEMPLATE",
    "DATA_CLEANERS_TEMPLATE",
    "TEST_EXAMPLE_TEMPLATE",
    "UOW_TEMPLATE",  # v3.7.0+
    # UI项目模板
    "UI_SETTINGS_TEMPLATE",
    "UI_CONFTEST_TEMPLATE",
    "UI_PAGE_OBJECT_TEMPLATE",
    "UI_TEST_EXAMPLE_TEMPLATE",
    "UI_FIXTURES_INIT_TEMPLATE",
    # 增强功能模板
    "UTILS_VALIDATORS_TEMPLATE",
    "UTILS_CONVERTERS_TEMPLATE",
    "CONSTANTS_ERROR_CODES_TEMPLATE",
    "ENHANCED_GITIGNORE_TEMPLATE",
    "SCRIPT_RUN_TESTS_TEMPLATE",
    "DOCS_API_TEMPLATE",
    # 代码生成模板
    "GEN_TEST_TEMPLATE",
    "GEN_TEST_COMPLETE_TEMPLATE",
    "GEN_BUILDER_TEMPLATE",
    "GEN_REPOSITORY_TEMPLATE",
    "GEN_API_CLIENT_TEMPLATE",
    "SETTINGS_ENHANCED_TEMPLATE",
    "ENV_BASE_TEMPLATE",
    "ENV_DEV_TEMPLATE",
    "ENV_TEST_TEMPLATE",
    "ENV_PROD_TEMPLATE",
    "ENV_EXAMPLE_TEMPLATE",
]
