from ..Base import *
from ..Proxy import *
from ..AcadEntity import AcadEntity as AcadEntity

class AcadPolyline(AcadEntity):
    def __init__(self, obj) -> None: ...
    Area: float
    Closed: bool
    ConstantWidth: float
    Coordinates: PyGePoint3dArray
    Elevation: float
    Length: float
    LinetypeGeneration: bool
    Normal: PyGeVector3d
    Thickness: float
    Type: AcPolylineType
    def Coordinate(self, Index: In[int]) -> PyGePoint3d: ...
    def Copy(self) -> AcadPolyline: ...
    def AppendVertex(self, Point: In[PyGePoint3d]) -> None: ...
    def Explode(self) -> vObjectArray: ...
    def GetBulge(self, Index: In[int]) -> float: ...
    def GetWidth(self, Index: In[int]) -> vDoubleArray: ...
    def Offset(self, Distance: In[float]) -> vObjectArray: ...
    def SetBulge(self, Index: In[int], Value: In[float]) -> None: ...
    def SetWidth(self, SegmentIndex: In[int], StartWidth: In[float], EndWidth: In[float]) -> None: ...
