from ..Base import *
from ..Proxy import *
from ..AcadEntity import AcadEntity as AcadEntity

class AcadTable(AcadEntity):
    def __init__(self, obj) -> None: ...
    AllowManualHeights: bool
    AllowManualPositions: bool
    BreaksEnabled: bool
    BreakSpacing: float
    Columns: int
    ColumnWidth: float
    Direction: PyGeVector3d
    EnableBreak: bool
    FlowDirection: AcTableDirection
    HasSubSelection: bool
    HeaderSuppressed: bool
    Height: float
    HorzCellMargin: float
    InsertionPoint: PyGePoint3d
    MinimumTableHeight: float
    MinimumTableWidth: float
    RegenerateTableSuppressed: bool
    RepeatBottomLabels: bool
    RowHeight: float
    Rows: int
    StyleName: str
    TableBreakFlowDirection: AcTableFlowDirection
    TableBreakHeight: float
    TableStyleOverrides: AcTableStyleOverrides
    TitleSuppressed: bool
    VertCellMargin: float
    Width: float
    def ClearSubSelection(self) -> None: ...
    def ClearTableStyleOverrides(self, flag: In[int]) -> None: ...
    def Copy(self, flag: In[int]) -> AcadTable: ...
    def CreateContent(self, nRow: In[int], nCol: In[int], nIndex: In[int]) -> int: ...
    def DeleteCellContent(self, row: In[int], col: In[int]) -> None: ...
    def DeleteColumns(self, col: In[int], cols: In[int]) -> None: ...
    def DeleteContent(self, nRow: In[int], nCol: In[int]) -> None: ...
    def DeleteRows(self, row: In[int], Rows: In[int]) -> None: ...
    def EnableMergeAll(self, nRow: In[int], nCol: In[int], bEnable: In[bool]) -> None: ...
    def FormatValue(self, row: In[int], col: In[int], nOption: In[AcFormatOption]) -> str: ...
    def GenerateLayout(self) -> None: ...
    def GetAlignment(self, rowType: In[AcRowType]) -> AcCellAlignment: ...
    def GetAttachmentPoint(self, row: In[int], col: In[int]) -> AcAttachmentPoint: ...
    def GetAutoScale(self, row: In[int], col: In[int]) -> bool: ...
    def GetAutoScale2(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> bool: ...
    def GetBackgroundColor(self, rowType: In[AcRowType]) -> AcadAcCmColor: ...
    def GetBackgroundColorNone(self, rowType: In[AcRowType]) -> bool: ...
    def GetBlockAttributeValue(self, row: In[int], col: In[int], attdefId: In[int]) -> str: ...
    def GetBlockAttributeValue2(self, nRow: In[int], nCol: In[int], nContent: In[int], blkId: In[int]) -> str: ...
    def GetBlockRotation(self, row: In[int], col: In[int]) -> float: ...
    def GetBlockScale(self, row: In[int], col: In[int]) -> float: ...
    def GetBlockTableRecordId(self, row: In[int], col: In[int]) -> int: ...
    def GetBlockTableRecordId2(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> int: ...
    def GetBreakHeight(self, nIndex: In[int]) -> float: ...
    def GetCellAlignment(self, row: In[int], col: In[int]) -> AcCellAlignment: ...
    def GetCellBackgroundColor(self, row: In[int], col: In[int]) -> AcadAcCmColor: ...
    def GetCellBackgroundColorNone(self, row: In[int], col: In[int]) -> bool: ...
    def GetCellContentColor(self, row: In[int], col: In[int]) -> AcadAcCmColor: ...
    def GetCellDataType(self, row: In[int], col: In[int], pDataType: In[AcValueDataType], pUnitType: In[AcValueUnitType]) -> None: ...
    def GetCellExtents(self, row: In[int], col: In[int], bOuterCell: In[bool]) -> None: ...
    def GetCellFormat(self, row: In[int], col: In[int]) -> str: ...
    def GetCellGridColor(self, row: In[int], col: In[int], edge: In[AcCellEdgeMask]) -> AcadAcCmColor: ...
    def GetCellGridLineWeight(self, row: In[int], col: In[int], edge: In[AcCellEdgeMask]) -> AcLineWeight: ...
    def GetCellGridVisibility(self, row: In[int], col: In[int], edge: In[AcCellEdgeMask]) -> bool: ...
    def GetCellState(self, nRow: In[int], nCol: In[int]) -> AcCellState: ...
    def GetCellStyle(self, nRow: In[int], nCol: In[int]) -> str: ...
    def GetCellStyleOverrides(self, row: In[int], col: In[int]) -> str: ...
    def GetCellTextHeight(self, row: In[int], col: In[int]) -> float: ...
    def GetCellTextStyle(self, row: In[int], col: In[int]) -> str: ...
    def GetCellType(self, row: In[int], col: In[int]) -> AcCellType: ...
    def GetCellValue(self, row: In[int], col: In[int]) -> Variant: ...
    def GetColumnName(self, nIndex: In[int]) -> str: ...
    def GetColumnWidth(self, col: In[int]) -> float: ...
    def GetContentColor(self, rowType: In[AcRowType]) -> AcadAcCmColor: ...
    def GetCellContentColor2(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> AcadAcCmColor: ...
    def GetContentLayout(self, nRow: In[int], nCol: In[int]) -> AcCellContentLayout: ...
    def GetContentType(self, nRow: In[int], nCol: In[int]) -> AcCellContentType: ...
    def GetCustomData(self, nRow: In[int], nCol: In[int], szKey: In[str]) -> Variant: ...
    def GetDataFormat(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> str: ...
    def GetDataType(self, rowType: In[AcRowType]) -> tuple[AcValueDataType, AcValueUnitType]: ...
    def GetDataType2(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> tuple[AcValueDataType, AcValueUnitType]: ...
    def GetFieldId(self, row: In[int], col: In[int]) -> int: ...
    def GetFieldId2(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> int: ...
    def GetFormat(self, rowType: In[AcRowType]) -> str: ...
    def GetFormula(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> str: ...
    def GetGridColor(self, gridLineType: In[AcGridLineType], rowType: In[AcRowType]) -> AcadAcCmColor: ...
    def GetGridColor2(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType]) -> AcadAcCmColor: ...
    def GetGridDoubleLineSpacing(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType]) -> float: ...
    def GetGridLineStyle(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType]) -> AcGridLineStyle: ...
    def GetGridLinetype(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType]) -> int: ...
    def GetGridLineWeight(self, gridLineType: In[AcGridLineType], rowType: In[AcRowType]) -> AcLineWeight: ...
    def GetGridLineWeight2(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType]) -> AcLineWeight: ...
    def GetGridVisibility(self, gridLineType: In[AcGridLineType], rowType: In[AcRowType]) -> bool: ...
    def GetGridVisibility2(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType]) -> bool: ...
    def GetHasFormula(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> bool: ...
    def GetMargin(self, nRow: In[int], nCol: In[int], nMargin: In[AcCellMargin]) -> float: ...
    def GetMinimumColumnWidth(self, col: In[int]) -> float: ...
    def GetMinimumRowHeight(self, row: In[int]) -> float: ...
    def GetOverride(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> AcCellProperty: ...
    def GetRotation(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> float: ...
    def GetRowHeight(self, row: In[int]) -> float: ...
    def GetRowType(self, row: In[int]) -> AcRowType: ...
    def GetScale(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> float: ...
    def GetSubSelection(self) -> tuple: ...
    def GetText(self, row: In[int], col: In[int]) -> str: ...
    def GetTextHeight(self, rowType: In[AcRowType]) -> float: ...
    def GetTextHeight2(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> float: ...
    def GetTextRotation(self, row: In[int], col: In[int]) -> AcRotationAngle: ...
    def GetTextString(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> str: ...
    def GetTextStyle(self, rowTypes: In[AcRowType]) -> str: ...
    def GetTextStyle2(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> str: ...
    def GetValue(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> Variant: ...
    def HitTest(self, wpt: In[PyGePoint3d], wviewVec: In[PyGeVector3d]) -> vIntegerArray: ...
    def InsertColumns(self, col: In[int], Width: In[float], cols: In[int]) -> None: ...
    def InsertColumnsAndInherit(self, col: In[int], nInheritFrom: In[int], nNumCols: In[int]) -> None: ...
    def InsertRows(self, row: In[int], Height: In[float], Rows: In[int]) -> None: ...
    def InsertRowsAndInherit(self, nIndex: In[int], nInheritFrom: In[int], nNumRows: In[int]) -> None: ...
    def IsContentEditable(self, nRow: In[int], nCol: In[int]) -> bool: ...
    def IsEmpty(self, nRow: In[int], nCol: In[int]) -> bool: ...
    def IsFormatEditable(self, nRow: In[int], nCol: In[int]) -> bool: ...
    def IsMergeAllEnabled(self, nRow: In[int], nCol: In[int]) -> bool: ...
    def IsMergedCell(self, row: In[int], col: In[int], minRow: In[int], maxRow: In[int], minCol: In[int], maxCol: In[int]) -> bool: ...
    def MergeCells(self, minRow: In[int], maxRow: In[int], minCol: In[int], maxCol: In[int]) -> None: ...
    def MoveContent(self, nRow: In[int], nCol: In[int], nFromIndex: In[int], nToIndex: In[int]) -> None: ...
    def RecomputeTableBlock(self, bForceUpdate: In[bool]) -> None: ...
    def RemoveAllOverrides(self, nRow: In[int], nCol: In[int]) -> None: ...
    def ReselectSubRegion(self) -> None: ...
    def ResetCellValue(self, row: In[int], col: In[int]) -> None: ...
    def Select(self, wpt: In[PyGePoint3d], wvwVec: In[PyGeVector3d], wvwxvec: In[PyGeVector3d], allowOutside: In[bool]) -> tuple[float, float, int, int]: ...
    def SelectSubRegion(self, wpt1: In[PyGePoint3d], wpt2: In[PyGePoint3d], wvwVec: In[PyGeVector3d], wvwxVec: In[PyGeVector3d], seltype: In[AcSelectType], bIncludeCurrentSelection: In[bool]) -> tuple[int, int, int, int]: ...
    def SetAlignment(self, rowTypes: In[AcRowType], cellAlignment: In[AcCellAlignment]) -> None: ...
    def SetAutoScale(self, row: In[int], col: In[int], bValue: In[bool]) -> None: ...
    def SetAutoScale2(self, nRow: In[int], nCol: In[int], nContent: In[int], bAutoFit: In[bool]) -> None: ...
    def SetBackgroundColor(self, rowTypes: In[AcRowType], pColor: In[AcadAcCmColor]) -> None: ...
    def SetBackgroundColorNone(self, rowTypes: In[AcRowType], bValue: In[bool]) -> None: ...
    def SetBlockAttributeValue(self, row: In[int], col: In[int], attdefId: In[int], StringValue: In[str]) -> None: ...
    def SetBlockAttributeValue2(self, nRow: In[int], nCol: In[int], nContent: In[int], blkId: In[int], value: In[str]) -> None: ...
    def SetBlockRotation(self, row: In[int], col: In[int], blkRotation: In[float]) -> None: ...
    def SetBlockScale(self, row: In[int], col: In[int], blkScale: In[float]) -> None: ...
    def SetBlockTableRecordId(self, row: In[int], col: In[int], blkId: In[int], bAutoFit: In[bool]) -> None: ...
    def SetBlockTableRecordId2(self, nRow: In[int], nCol: In[int], nContent: In[int], blkId: In[int], autoFit: In[bool]) -> None: ...
    def SetBreakHeight(self, nIndex: In[int], dHeight: In[float]) -> None: ...
    def SetCellAlignment(self, row: In[int], col: In[int], cellAlignment: In[AcCellAlignment]) -> None: ...
    def SetCellBackgroundColor(self, row: In[int], col: In[int], pColor: In[AcadAcCmColor]) -> None: ...
    def SetCellBackgroundColorNone(self, row: In[int], col: In[int], bValue: In[bool]) -> None: ...
    def SetCellContentColor(self, row: In[int], col: In[int], pColor: In[AcadAcCmColor]) -> None: ...
    def SetCellDataType(self, row: In[int], col: In[int], dataType: In[AcValueDataType], unitType: In[AcValueUnitType]) -> None: ...
    def SetCellFormat(self, row: In[int], col: In[int], pFormat: In[str]) -> None: ...
    def SetCellGridColor(self, row: In[int], col: In[int], edges: In[AcCellEdgeMask], pColor: In[AcadAcCmColor]) -> None: ...
    def SetCellGridLineWeight(self, row: In[int], col: In[int], edges: In[AcCellEdgeMask], Lineweight: In[AcLineWeight]) -> None: ...
    def SetCellGridVisibility(self, row: In[int], col: In[int], edges: In[AcCellEdgeMask], bValue: In[bool]) -> None: ...
    def SetCellState(self, nRow: In[int], nCol: In[int], nLock: In[AcCellState]) -> None: ...
    def SetCellStyle(self, nRow: In[int], nCol: In[int], szCellStyle: In[str]) -> None: ...
    def SetCellTextHeight(self, row: In[int], col: In[int], TextHeight: In[float]) -> None: ...
    def SetCellTextStyle(self, row: In[int], col: In[int], bstrName: In[str]) -> None: ...
    def SetCellType(self, row: In[int], col: In[int], CellType: In[AcCellType]) -> None: ...
    def SetCellValue(self, row: In[int], col: In[int]) -> Variant: ...
    def SetCellValueFromText(self, row: In[int], col: In[int], val: In[str], nOption: In[AcParseOption]) -> None: ...
    def SetColumnName(self, nIndex: In[int], name: In[str]) -> None: ...
    def SetColumnWidth(self, col: In[int], Width: In[float]) -> None: ...
    def SetContentColor(self, rowTypes: In[AcRowType], pColor: In[AcadAcCmColor]) -> None: ...
    def SetContentColor2(self, nRow: In[int], nCol: In[int], nContent: In[int], pColor: In[AcadAcCmColor]) -> None: ...
    def SetContentLayout(self, nRow: In[int], nCol: In[int], nLayout: In[AcCellContentLayout]) -> None: ...
    def SetCustomData(self, nRow: In[int], nCol: In[int], szKey: In[str], data: In[Variant]) -> None: ...
    def SetDataFormat(self, nRow: In[int], nCol: In[int], nContent: In[int], szFormat: In[str]) -> None: ...
    def SetDataType(self, rowTypes: In[AcRowType], nDataType: In[AcValueDataType], nUnitType: In[AcValueUnitType]) -> None: ...
    def SetDataType2(self, nRow: In[int], nCol: In[int], nContent: In[int], dataType: In[AcValueDataType], unitType: In[AcValueUnitType]) -> None: ...
    def SetFieldId(self, row: In[int], col: In[int], fieldId: In[int]) -> None: ...
    def SetFieldId2(self, nRow: In[int], nCol: In[int], nContent: In[int], acDbObjectId: In[int], nflag: In[AcCellOption]) -> None: ...
    def SetFormat(self, rowTypes: In[AcRowType], pFormat: In[str]) -> None: ...
    def SetFormula(self, nRow: In[int], nCol: In[int], nContent: In[int], pszFormula: In[str]) -> None: ...
    def SetGridColor(self, gridLineTypes: In[AcGridLineType], rowTypes: In[AcRowType], pColor: In[AcadAcCmColor]) -> None: ...
    def SetGridColor2(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType], pColor: In[AcadAcCmColor]) -> None: ...
    def SetGridDoubleLineSpacing(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType], fSpacing: In[float]) -> None: ...
    def SetGridLineStyle(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType], nLineStyle: In[AcGridLineStyle]) -> None: ...
    def SetGridLinetype(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType], idLinetype: In[int]) -> None: ...
    def SetGridLineWeight(self, gridLineTypes: In[AcGridLineType], rowTypes: In[AcRowType], Lineweight: In[AcLineWeight]) -> None: ...
    def SetGridLineWeight2(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType], lineWeight: In[AcLineWeight]) -> None: ...
    def SetGridVisibility(self, gridLineTypes: In[AcGridLineType], rowTypes: In[AcRowType], bValue: In[bool]) -> None: ...
    def SetGridVisibility2(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType], bVisible: In[bool]) -> None: ...
    def SetMargin(self, nRow: In[int], nCol: In[int], nMargins: In[AcCellMargin], fMargin: In[float]) -> None: ...
    def SetOverride(self, nRow: In[int], nCol: In[int], nContent: In[int], nProp: In[AcCellProperty]) -> None: ...
    def SetRotation(self, nRow: In[int], nCol: In[int], nContent: In[int], pValue: In[float]) -> None: ...
    def SetRowHeight(self, row: In[int], Height: In[float]) -> None: ...
    def SetScale(self, nRow: In[int], nCol: In[int], nContent: In[int], scale: In[float]) -> None: ...
    def SetSubSelection(self, rowMin: In[int], rowMax: In[int], colMin: In[int], colMax: In[int]) -> None: ...
    def SetText(self, row: In[int], col: In[int], pStr: In[str]) -> None: ...
    def SetTextHeight(self, rowTypes: In[AcRowType], TextHeight: In[float]) -> None: ...
    def SetTextHeight2(self, nRow: In[int], nCol: In[int], nContent: In[int], height: In[float]) -> None: ...
    def SetTextRotation(self, row: In[int], col: In[int], TextRotation: In[AcRotationAngle]) -> None: ...
    def SetTextString(self, nRow: In[int], nCol: In[int], nContent: In[int], text: In[str]) -> None: ...
    def SetTextStyle(self, rowTypes: In[AcRowType], bstrName: In[str]) -> None: ...
    def SetTextStyle2(self, nRow: In[int], nCol: In[int], nContent: In[int], StringStyleName: In[str]) -> None: ...
    def SetToolTip(self, nRow: In[int], nCol: In[int], tip: In[str]) -> None: ...
    def SetValue(self, nRow: In[int], nCol: In[int], nContent: In[int], acValue: In[Variant]) -> None: ...
    def SetValueFromText(self, nRow: In[int], nCol: In[int], nContent: In[int], szText: In[str], nOption: In[AcParseOption]) -> None: ...
    def UnmergeCells(self, minRow: In[int], maxRow: In[int], minCol: In[int], maxCol: In[int]) -> None: ...
