from typing import Any

from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType

class Line(_BaseTraceHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def color(self) -> str | None: ...
    @color.setter
    def color(self, val: str | None) -> None: ...
    @property
    def width(self) -> int | float | None: ...
    @width.setter
    def width(self, val: int | float | None) -> None: ...
    def __init__(
        self,
        arg: dict[str, str | int | float] | Line = ...,
        color: str = ...,
        width: int | float = ...,
        **kwargs: Any,
    ) -> None: ...
