from typing import Any

from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from plotly.graph_objs.candlestick.legendgrouptitle import Font

class Legendgrouptitle(_BaseTraceHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def font(self) -> Font | dict[str, Any]: ...
    @font.setter
    def font(self, val: Font | dict[str, Any]) -> None: ...
    @property
    def text(self) -> str | int | float: ...
    @text.setter
    def text(self, val: str | int | float) -> None: ...
    def __init__(
        self,
        arg: Legendgrouptitle | dict[str, Any] | None = ...,
        font: Font | dict[str, Any] | None = ...,
        text: str | int | float | None = ...,
        **kwargs: Any,
    ) -> None: ...
