from typing import Any

from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType

class Stream(_BaseTraceHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def maxpoints(self) -> int | float | None: ...
    @maxpoints.setter
    def maxpoints(self, val: int | float | None) -> None: ...
    @property
    def token(self) -> str | None: ...
    @token.setter
    def token(self, val: str | None) -> None: ...
    def __init__(
        self,
        arg: Stream | dict[str, Any] | None = ...,
        maxpoints: int | float | None = ...,
        token: str | None = ...,
        **kwargs: Any,
    ) -> None: ...
