# pyright: reportPropertyTypeMismatch=false
from typing import Any

from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType
from plotly.graph_objs.candlestick import Line

class Increasing(_BaseTraceHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def fillcolor(self) -> str | None: ...
    @fillcolor.setter
    def fillcolor(self, val: str | None) -> None: ...
    @property
    def line(self) -> Line: ...
    @line.setter
    def line(self, val: Line | dict[str, Any]) -> None: ...
    def __init__(
        self,
        arg: Increasing | dict[str, Any] | None = ...,
        fillcolor: str | None = ...,
        line: Line | dict[str, Any] | None = ...,
        **kwargs: Any,
    ) -> None: ...
