from typing import Any

from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType

class Line(_BaseTraceHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def width(self) -> int | float | None: ...
    @width.setter
    def width(self, val: int | float | None) -> None: ...
    def __init__(
        self, arg: Line | dict[str, Any] | None = ..., width: int | float | None = ..., **kwargs: Any
    ) -> None: ...
