from _typeshed import Incomplete
from minjiang_client.plugin.plugin_register import plugin_register as plugin_register
from minjiang_client.utils import parse_type as parse_type, single_decorator as single_decorator

class WaveformRegister:
    waveforms: Incomplete
    waveform_funcs: Incomplete
    waveform_compiler_setup: Incomplete
    waveform_compiler_setup_desc: Incomplete
    def __init__(self) -> None: ...
    def get_waveforms(self): ...
    def get_waveform_func(self, wave_name): ...
    def get_waveform_compiler_setup(self): ...
    def get_waveform_compiler_setup_desc(self): ...
    def clear(self) -> None: ...
    def reg_waveform(self, wave_name, wave_func: callable): ...

waveform_register: Incomplete
plugins: Incomplete
waves: Incomplete
