# Generated by Django 5.1.6 on 2025-04-10 20:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0025_alter_onlycards_featured_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlycards",
            name="feature",
            field=wagtail.fields.StreamField(
                [("enap_herofeature", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("background_image", 0), ("title", 1), ("description", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
