from typing import Any

from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType

class Margin(_BaseLayoutHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def autoexpand(self) -> bool | None: ...
    @autoexpand.setter
    def autoexpand(self, val: bool | None) -> None: ...
    @property
    def b(self) -> int | float | None: ...
    @b.setter
    def b(self, val: int | float | None) -> None: ...
    @property
    def l(self) -> int | float | None: ...  # noqa: E743
    @l.setter
    def l(self, val: int | float | None) -> None: ...  # noqa: E743
    @property
    def pad(self) -> int | float | None: ...
    @pad.setter
    def pad(self, val: int | float | None) -> None: ...
    @property
    def r(self) -> int | float | None: ...
    @r.setter
    def r(self, val: int | float | None) -> None: ...
    @property
    def t(self) -> int | float | None: ...
    @t.setter
    def t(self, val: int | float | None) -> None: ...
    def __init__(
        self,
        arg: Margin | dict[str, Any] | None = ...,
        autoexpand: bool | None = ...,
        b: int | float | None = ...,
        l: int | float | None = ...,
        pad: int | float | None = ...,
        r: int | float | None = ...,
        t: int | float | None = ...,
        **kwargs: Any,
    ) -> None: ...
