"""The Cards sub-package exposes the core integrations of the cards in the AdaLab Gallery."""

from .cards import (
    create_card,
    create_card_group,
    create_url_card,
    create_url_subtype,
    delete_card,
    delete_card_group,
    delete_url_subtype,
    edit_card,
    edit_card_group,
    edit_url_card,
    edit_url_subtype,
    expose_card,
    get_card_contents,
    get_card_issues,
    get_card_types,
    get_card_types_stats,
    get_cards,
    get_url_subtypes,
    hide_card,
    launch_card,
    set_card_visibility,
    toggle_card_favorite,
    toggle_card_review,
)

__all__ = [
    "create_card",
    "create_card_group",
    "create_url_card",
    "create_url_subtype",
    "delete_card",
    "delete_card_group",
    "delete_url_subtype",
    "edit_card",
    "edit_card_group",
    "edit_url_card",
    "edit_url_subtype",
    "expose_card",
    "get_card_contents",
    "get_card_issues",
    "get_card_types",
    "get_card_types_stats",
    "get_url_subtypes",
    "get_cards",
    "hide_card",
    "launch_card",
    "set_card_visibility",
    "toggle_card_favorite",
    "toggle_card_review",
]
__title__ = "adalib Cards"
