
import base64
DATA_B64 = "Ik5UTiBQaMO6IFF1w70gMDRobC0+QsSQQiBQaMO6IFF1w70gMzFobCI6IHsKwqAgwqAgwqAgwqAgwqAgwqAgIm9iamVjdHMiOiBbCsKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgICJ0w6B1IFRpYW4gU2hlbmcgWW91IDIiCsKgIMKgIMKgIMKgIMKgIMKgIF0sCsKgIMKgIMKgIMKgIMKgIMKgICJwYXNzYWdlIjogIklJLiBWw5lORyBCSeG7gk5cbjYuIFTDoHUgbsaw4bubYyBuZ2/DoGkgdmkgcGjhuqFtIHbDuW5nIE7hu5lpIHRo4buneSAoQ1NCIGLDoW8gY8Ohbyk6XG5Mw7pjIDA4LjQwIG5nw6B5IDA0LzQvMjAyNSwgdMOgdSBUaWFuIFNoZW5nIFlvdSAyL1RRIG5o4buVIG5lbyBy4budaSBraHUgduG7sWMgTlROIFBow7ogUXXDvSAwNGhsIMSRaSB24buBIHBow61hIELhuq9jLCBsw7pjIDEzLjAwIOG7nyBCxJBCIFBow7ogUXXDvSAzMWhsLCBIPTE14bWSLCBWPTA4aGwvaC4gQ8OhYyBs4buxYyBsxrDhu6NuZyBj4bunYSBUYSB0aeG6v3AgdOG7pWMgdGhlbyBkw7VpLiIsCsKgIMKgIMKgIMKgIMKgIMKgICJjb29ycyI6IFsKwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgWwrCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCAxMDguOTE3NTQ0LArCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCAxMC40NjM5MTgKwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgXSwKwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgWwrCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCAxMDkuMTQ0NzU0LArCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCDCoCAxMS4wMDI0MjIKwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgXQrCoCDCoCDCoCDCoCDCoCDCoCBdLArCoCDCoCDCoCDCoCDCoCDCoCAibG9jcyI6IFsKwqAgwqAgwqAgwqAgwqAgwqAgwqAgwqAgIk5UTiBQaMO6IFF1w70gMDRobCIsCsKgIMKgIMKgIMKgIMKgIMKgIMKgIMKgICJCxJBCIFBow7ogUXXDvSAzMWhsIgrCoCDCoCDCoCDCoCDCoCDCoCBdCsKgIMKgIMKgIMKgIH0="
def save(filename="code_moi_ve.py"):
    try:
        decoded = base64.b64decode(DATA_B64).decode("utf-8")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(decoded)
        print(f"OK: Da luu code vao {filename}")
    except Exception as e:
        print(f"LOI: {e}")
