"""LSP server configurations for various programming languages."""

from anyenv.lsp_servers._base import (
    CargoInstall,
    CLIDiagnosticConfig,
    Diagnostic,
    DiagnosticsResult,
    DotnetInstall,
    GemInstall,
    GitHubRelease,
    GoInstall,
    LSPServerInfo,
    NpmInstall,
    RootDetection,
)
from anyenv.lsp_servers._registry import LSPServerRegistry
from anyenv.lsp_servers._runner import DiagnosticRunner
from anyenv.lsp_servers._servers import (
    ALL_SERVERS,
    ASTRO,
    BASEDPYRIGHT,
    CLANGD,
    CSHARP_LS,
    DART,
    DENO,
    ELIXIR_LS,
    ESLINT,
    GOPLS,
    JDTLS,
    LUA_LS,
    MYPY,
    PHP_INTELEPHENSE,
    PYRIGHT,
    RUBOCOP,
    RUST_ANALYZER,
    SOURCEKIT_LSP,
    SVELTE,
    TYPESCRIPT,
    VUE,
    YAML_LS,
    ZLS,
    # Custom server classes
    AstroServer,
    GoplsServer,
    MypyServer,
    PyrightServer,
    RustAnalyzerServer,
    TypeScriptServer,
)

__all__ = [
    "ALL_SERVERS",
    "ASTRO",
    "BASEDPYRIGHT",
    "CLANGD",
    "CSHARP_LS",
    "DART",
    "DENO",
    "ELIXIR_LS",
    "ESLINT",
    "GOPLS",
    "JDTLS",
    "LUA_LS",
    "MYPY",
    "PHP_INTELEPHENSE",
    "PYRIGHT",
    "RUBOCOP",
    "RUST_ANALYZER",
    "SOURCEKIT_LSP",
    "SVELTE",
    "TYPESCRIPT",
    "VUE",
    "YAML_LS",
    "ZLS",
    "AstroServer",
    "CLIDiagnosticConfig",
    "CargoInstall",
    "Diagnostic",
    "DiagnosticRunner",
    "DiagnosticsResult",
    "DotnetInstall",
    "GemInstall",
    "GitHubRelease",
    "GoInstall",
    "GoplsServer",
    "LSPServerInfo",
    "LSPServerRegistry",
    "MypyServer",
    "NpmInstall",
    "PyrightServer",
    "RootDetection",
    "RustAnalyzerServer",
    "TypeScriptServer",
]
