"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from enum import Enum
import pydantic
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FunctionChainID(str, Enum):
    CHAIN = "chain"


class FunctionChainSchemaTypedDict(TypedDict):
    processor: str
    r"""The data processor (Pack/Pipeline) to send events through"""


class FunctionChainSchema(BaseModel):
    processor: str
    r"""The data processor (Pack/Pipeline) to send events through"""


class FunctionChainTypedDict(TypedDict):
    filename: str
    group: str
    id: FunctionChainID
    load_time: float
    mod_time: float
    name: str
    uischema: Dict[str, Any]
    version: str
    async_timeout: NotRequired[float]
    cribl_version: NotRequired[str]
    disabled: NotRequired[bool]
    handle_signals: NotRequired[bool]
    sync: NotRequired[bool]
    schema_: NotRequired[FunctionChainSchemaTypedDict]


class FunctionChain(BaseModel):
    filename: Annotated[str, pydantic.Field(alias="__filename")]

    group: str

    id: FunctionChainID

    load_time: Annotated[float, pydantic.Field(alias="loadTime")]

    mod_time: Annotated[float, pydantic.Field(alias="modTime")]

    name: str

    uischema: Dict[str, Any]

    version: str

    async_timeout: Annotated[Optional[float], pydantic.Field(alias="asyncTimeout")] = (
        None
    )

    cribl_version: Optional[str] = None

    disabled: Optional[bool] = None

    handle_signals: Annotated[Optional[bool], pydantic.Field(alias="handleSignals")] = (
        None
    )

    sync: Optional[bool] = None

    schema_: Annotated[
        Optional[FunctionChainSchema], pydantic.Field(alias="schema")
    ] = None
