"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import models, utils
from cribl_control_plane.types import BaseModel
from cribl_control_plane.utils import validate_open_enum
from enum import Enum
import pydantic
from pydantic import field_serializer
from pydantic.functional_validators import PlainValidator
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FunctionOtlpTracesID(str, Enum):
    OTLP_TRACES = "otlp_traces"


class FunctionOTLPTracesOTLPVersion(str, Enum, metaclass=utils.OpenEnumMeta):
    # 0.10.0
    ZERO_DOT_10_DOT_0 = "0.10.0"
    # 1.3.1
    ONE_DOT_3_DOT_1 = "1.3.1"


class FunctionOtlpTracesSchemaTypedDict(TypedDict):
    drop_non_trace_events: NotRequired[bool]
    otlp_version: NotRequired[FunctionOTLPTracesOTLPVersion]
    batch_otlp_traces: NotRequired[bool]
    r"""Batch OTLP traces by shared top-level `resource` attributes"""


class FunctionOtlpTracesSchema(BaseModel):
    drop_non_trace_events: Annotated[
        Optional[bool], pydantic.Field(alias="dropNonTraceEvents")
    ] = False

    otlp_version: Annotated[
        Annotated[
            Optional[FunctionOTLPTracesOTLPVersion],
            PlainValidator(validate_open_enum(False)),
        ],
        pydantic.Field(alias="otlpVersion"),
    ] = FunctionOTLPTracesOTLPVersion.ZERO_DOT_10_DOT_0

    batch_otlp_traces: Annotated[
        Optional[bool], pydantic.Field(alias="batchOTLPTraces")
    ] = False
    r"""Batch OTLP traces by shared top-level `resource` attributes"""

    @field_serializer("otlp_version")
    def serialize_otlp_version(self, value):
        if isinstance(value, str):
            try:
                return models.FunctionOTLPTracesOTLPVersion(value)
            except ValueError:
                return value
        return value


class FunctionOtlpTracesTypedDict(TypedDict):
    filename: str
    group: str
    id: FunctionOtlpTracesID
    load_time: float
    mod_time: float
    name: str
    uischema: Dict[str, Any]
    version: str
    async_timeout: NotRequired[float]
    cribl_version: NotRequired[str]
    disabled: NotRequired[bool]
    handle_signals: NotRequired[bool]
    sync: NotRequired[bool]
    schema_: NotRequired[FunctionOtlpTracesSchemaTypedDict]


class FunctionOtlpTraces(BaseModel):
    filename: Annotated[str, pydantic.Field(alias="__filename")]

    group: str

    id: FunctionOtlpTracesID

    load_time: Annotated[float, pydantic.Field(alias="loadTime")]

    mod_time: Annotated[float, pydantic.Field(alias="modTime")]

    name: str

    uischema: Dict[str, Any]

    version: str

    async_timeout: Annotated[Optional[float], pydantic.Field(alias="asyncTimeout")] = (
        None
    )

    cribl_version: Optional[str] = None

    disabled: Optional[bool] = None

    handle_signals: Annotated[Optional[bool], pydantic.Field(alias="handleSignals")] = (
        None
    )

    sync: Optional[bool] = None

    schema_: Annotated[
        Optional[FunctionOtlpTracesSchema], pydantic.Field(alias="schema")
    ] = None
