from ..Base import *
from ..Proxy import *
from ..AcadObject import *

class AcadPlot(AppObject):
    def __init__(self, obj) -> None: ...
    Application: AcadApplication
    BatchPlotProgress: bool
    NumberOfCopies: int
    QuietErrorMode: bool
    def DisplayPlotPreview(self, Preview: In[AcPreviewMode]) -> None: ...
    def PlotToDevice(self, plotConfig: In[str] = '') -> bool: ...
    def PlotToFile(self, plotFile: In[str], plotConfig: In[str] = '') -> bool: ...
    def SetLayoutsToPlot(self, layoutList: In[vStringArray]) -> None: ...
    def StartBatchMode(self, entryCount: In[int]) -> None: ...
