from ..Base import *
from ..AcadObject import *
from ..Proxy import AccessMode as AccessMode, proxy_property as proxy_property

class AcadLayerStateManager(AppObject):
    def __init__(self, obj) -> None: ...
    def Mask(self, Name: In[str]) -> AcLayerStateMask | int: ...
    def Delete(self, Name: In[str]) -> None: ...
    def Export(self, Name: In[str], FileName: In[str]) -> None: ...
    def Import(self, FileName: In[str]) -> None: ...
    def Rename(self, OldName: In[str], NewName: In[str]) -> None: ...
    def Restore(self, Name: In[str]) -> None: ...
    def Save(self, Name: In[str], Mask: In[AcLayerStateMask | int]) -> None: ...
    def SetDatabase(self, Database: In[AcadDatabase]) -> None: ...
