from ..Base import *
from ..Proxy import *
from ..AcadObject import *

class AcadTableStyle(AcadObject):
    def __init__(self, obj) -> None: ...
    BitFlags: int
    Description: str
    FlowDirection: AcTableDirection
    HeaderSuppressed: bool
    HorzCellMargin: float
    Name: str
    NumCellStyles: int
    TemplateId: int
    TitleSuppressed: bool
    VertCellMargin: float
    def CreateCellStyle(self, StringCellStyle: In[str]) -> None: ...
    def CreateCellStyleFromStyle(self, StringCellStyle: In[str], StringSourceCellStyle: In[str]) -> None: ...
    def DeleteCellStyle(self, StringCellStyle: In[str]) -> None: ...
    def EnableMergeAll(self, nRow: In[int], nCol: In[int], bEnable: In[bool]) -> None: ...
    def GetAlignment(self, rowType: In[AcRowType]) -> AcCellAlignment: ...
    def GetAlignment2(self, bstrCellStyle: In[str]) -> AcCellAlignment: ...
    def GetBackgroundColor(self, rowType: In[AcRowType]) -> AcadAcCmColor: ...
    def GetBackgroundColor2(self, bstrCellStyle: In[str]) -> AcadAcCmColor: ...
    def GetBackgroundColorNone(self, rowType: In[AcRowType]) -> bool: ...
    def GetCellClass(self, StringCellStyle: In[str]) -> int: ...
    def GetCellStyles(self) -> Variant: ...
    def GetColor(self, rowType: In[AcRowType]) -> AcadAcCmColor: ...
    def GetColor2(self, bstrCellStyle: In[str]) -> AcadAcCmColor: ...
    def GetDataType(self, rowType: In[AcRowType]) -> tuple: ...
    def GetDataType2(self, nRow: In[int], nCol: In[int], nContent: In[int]) -> tuple: ...
    def GetFormat(self, rowType: In[AcRowType]) -> str: ...
    def GetFormat2(self, StringCellStyle: In[str]) -> str: ...
    def GetGridColor(self, gridLineType: In[AcGridLineType], rowType: In[AcRowType]) -> AcadAcCmColor: ...
    def GetGridColor2(self, bstrCellStyle: In[str], gridLineType: In[AcGridLineType]) -> AcadAcCmColor: ...
    def GetGridLineWeight(self, gridLineType: In[AcGridLineType], rowType: In[AcRowType]) -> AcLineWeight: ...
    def GetGridLineWeight2(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType]) -> AcLineWeight: ...
    def GetGridVisibility(self, gridLineType: In[AcGridLineType], rowType: In[AcRowType]) -> bool: ...
    def GetGridVisibility2(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType]) -> bool: ...
    def GetIsCellStyleInUse(self, pszCellStyle: In[str]) -> bool: ...
    def GetIsMergeAllEnabled(self, StringCellStyle: In[str]) -> bool: ...
    def GetRotation(self, StringCellStyle: In[str]) -> float: ...
    def GetTextHeight(self, rowType: In[AcRowType]) -> float: ...
    def GetTextHeight2(self, StringCellStyle: In[str]) -> float: ...
    def GetTextStyle(self, rowType: In[AcRowType]) -> str: ...
    def GetTextStyleId(self, bstrCellStyle: In[str]) -> float: ...
    def GetUniqueCellStyleName(self, pszBaseName: In[str]) -> str: ...
    def RenameCellStyle(self, StringOldName: In[str], StringNewName: In[str]) -> None: ...
    def SetAlignment(self, rowTypes: In[AcRowType], cellAlignment: In[AcCellAlignment]) -> None: ...
    def SetAlignment2(self, bstrCellStyle: In[str], cellAlignment: In[AcCellAlignment]) -> None: ...
    def SetBackgroundColor(self, rowTypes: In[AcRowType], pColor: In[AcadAcCmColor]) -> None: ...
    def SetBackgroundColor2(self, bstrCellStyle: In[str], color: In[AcadAcCmColor]) -> None: ...
    def SetBackgroundColorNone(self, rowTypes: In[AcRowType], bValue: In[bool]) -> None: ...
    def SetCellClass(self, StringCellStyle: In[str], cellClass: In[int]) -> None: ...
    def SetColor(self, rowTypes: In[AcRowType], pColor: In[AcadAcCmColor]) -> None: ...
    def SetColor2(self, bstrCellStyle: In[str], color: In[AcadAcCmColor]) -> None: ...
    def SetDataType(self, rowTypes: In[AcRowType], nDataType: In[AcValueDataType], nUnitType: In[AcValueUnitType]) -> None: ...
    def SetDataType2(self, nRow: In[int], nCol: In[int], nContent: In[int], dataType: In[AcValueDataType], unitType: In[AcValueUnitType]) -> None: ...
    def SetFormat(self, rowTypes: In[AcRowType], pFormat: In[str]) -> None: ...
    def SetFormat2(self, bstrCellStyle: In[str], bstrFormat: In[str]) -> None: ...
    def SetGridColor(self, gridLineTypes: In[AcGridLineType], rowTypes: In[AcRowType], pColor: In[AcadAcCmColor]) -> None: ...
    def SetGridColor2(self, nRow: In[int], nCol: In[int], nGridLineType: In[AcGridLineType], pColor: In[AcadAcCmColor]) -> None: ...
    def SetGridLineWeight(self, gridLineTypes: In[AcGridLineType], rowTypes: In[AcRowType], Lineweight: In[AcLineWeight]) -> None: ...
    def SetGridLineWeight2(self, bstrCellStyle: In[str], gridLineType: In[AcGridLineType], Lineweight: In[AcLineWeight]) -> None: ...
    def SetGridVisibility(self, gridLineTypes: In[AcGridLineType], rowTypes: In[AcRowType], bVisible: In[bool]) -> None: ...
    def SetGridVisibility2(self, bstrCellStyle: In[str], gridLineType: In[AcGridLineType], bValue: In[bool]) -> None: ...
    def SetRotation(self, bstrCellStyle: In[str], Rotation: In[float]) -> None: ...
    def SetTemplateId(self, val: In[int], option: In[AcMergeCellStyleOption]) -> None: ...
    def SetTextHeight(self, rowTypes: In[AcRowType], TextHeight: In[float]) -> None: ...
    def SetTextHeight2(self, bstrCellStyle: In[str], Height: In[float]) -> None: ...
    def SetTextStyle(self, rowTypes: In[AcRowType], bstrName: In[str]) -> None: ...
    def SetTextStyleId(self, bstrCellStyle: In[str], val: In[int]) -> None: ...
