from ..Base import *
from ..Proxy import *

class AcadSummaryInfo(AppObject):
    def __init__(self, obj) -> None: ...
    Author: str
    Comments: str
    HyperlinkBase: str
    Keywords: str
    LastSavedBy: str
    RevisionNumber: str
    Subject: str
    Title: str
    def AddCustomInfo(self, key: In[str], Value: In[str]) -> None: ...
    def GetCustomByIndex(self, Index: In[int]) -> str: ...
    def GetCustomByKey(self, pKey: In[str]) -> vStringArray: ...
    def NumCustomInfo(self) -> int: ...
    def RemoveCustomByIndex(self, Index: In[int]) -> None: ...
    def RemoveCustomByKey(self, key: In[str]) -> None: ...
    def SetCustomByIndex(self, Index: In[int], key: In[str], Value: In[str]) -> None: ...
    def SetCustomByKey(self, key: In[str], Value: In[str]) -> None: ...
