from ..AcadObject import *
from .AcadRegisteredApplication import AcadRegisteredApplication as AcadRegisteredApplication

class AcadRegisteredApplications(IAcadObjectCollection):
    def __init__(self, obj) -> None: ...
    def Add(self, Name: In[str]) -> AcadRegisteredApplication: ...
    def Item(self, Index: In[int]) -> AcadRegisteredApplication: ...
    def __iter__(self): ...
