from ..Base import *
from ..Proxy import *
from .AcadPopupMenu import *

class AcadPopupMenus(AppObject):
    def __init__(self, obj) -> None: ...
    Application: AcadApplication
    Count: int
    Parent: AppObject
    def Add(self, Name: In[str]) -> AcadPopupMenu: ...
    def InsertMenuInMenuBar(self, MenuName: In[str], Index: In[int]) -> None: ...
    def Item(self, Index: In[int]) -> AcadPopupMenu: ...
    def RemoveMenuFromMenuBar(self, Index: In[int]) -> None: ...
    def __iter__(self): ...
