# Generated by Django 5.1.6 on 2025-04-08 15:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0002_alter_enapformacao_accordion_cursos"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="MbaEspecializacao",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "course_intro_topics",
                    wagtail.fields.StreamField(
                        [("course_intro_topics", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Título principal sobre o curso",
                                    "label": "Título do Curso",
                                    "required": True,
                                },
                            ),
                            1: (
                                "enap_designsystem.blocks.html_blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Descrição geral do curso",
                                    "label": "Descrição do Curso",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Imagem para destacar o curso",
                                    "label": "Imagem",
                                    "required": True,
                                },
                            ),
                            3: (
                                "enap_designsystem.blocks.html_blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Descreva a modalidade do curso",
                                    "label": "Descrição da Modalidade",
                                    "required": True,
                                },
                            ),
                            4: (
                                "enap_designsystem.blocks.html_blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Descreva o conteúdo do curso",
                                    "label": "Descrição do Curso",
                                    "required": True,
                                },
                            ),
                            5: (
                                "enap_designsystem.blocks.html_blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Descreva a metodologia do curso",
                                    "label": "Descrição da Metodologia",
                                    "required": True,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("image", 2),
                                        ("modalidade_description", 3),
                                        ("curso_description", 4),
                                        ("metodologia_description", 5),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "MBA e Especialização",
                "verbose_name_plural": "MBAs e Especializações",
            },
            bases=("wagtailcore.page",),
        ),
    ]
