# Generated by Django 5.1.7 on 2025-06-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0171_remove_enaptemplatev1_teste_courses"),
        (
            "enap_designsystem",
            "0196_alter_areaaluno_body_alter_cursoeadpage_curso_and_more",
        ),
    ]

    operations = []
