# Generated by Django 5.1.6 on 2025-08-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0285_alter_templateespecializacao_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateespecializacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Inscrições Abertas", "Inscrições Abertas"),
                    ("Inscrições Em Andamento", "Inscrições Em Andamento"),
                    ("Inscrições Encerrada", "Inscrições Encerradas"),
                ],
                default="aberto",
                help_text="Status atual do curso de especialização",
                max_length=100,
                verbose_name="Status do Curso",
            ),
        ),
    ]
