# Generated by Django 5.1.6 on 2025-08-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0331_alter_sejaavaliador_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concursoinovacao",
            options={
                "verbose_name": "Concursos de inovação - Edital",
                "verbose_name_plural": "Concursos de inovação - Edital",
            },
        ),
        migrations.AlterModelOptions(
            name="editalconcursoinovacao",
            options={
                "verbose_name": "Concurso de inovação - Home",
                "verbose_name_plural": "Concursos de inovação - Home",
            },
        ),
        migrations.AlterModelOptions(
            name="sejaavaliador",
            options={
                "verbose_name": "Concurso de inovação - Seja Avaliador",
                "verbose_name_plural": "Concurso de inovação - Seja Avaliador",
            },
        ),
    ]
