# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import ConfigDict, Field
from typing import List as PyList

from fhirschemapy.R4B.base import CodeableConcept, Identifier, Reference
from fhirschemapy.R4B.domain_resource import DomainResource


class Basic(DomainResource):
    model_config = ConfigDict(serialize_by_alias=True, extra="forbid")

    resource_type: str = Field(
        default="Basic",
        alias="resourceType",
        serialization_alias="resourceType",
        frozen=True,
        pattern="Basic",
    )

    author: Reference | None = Field(None, alias="author", serialization_alias="author")
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    created: str | None = Field(None, alias="created", serialization_alias="created")
    identifier: PyList[Identifier] | None = Field(
        None, alias="identifier", serialization_alias="identifier"
    )
    subject: Reference | None = Field(
        None, alias="subject", serialization_alias="subject"
    )

    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(
            exclude_unset=True, exclude_none=True, indent=indent
        )

    @classmethod
    def from_json(cls, json: str) -> Basic:
        return cls.model_validate_json(json)
