__title__ = 'Mayan EDMS'
__version__ = '4.7.8'
__build__ = 0x040708
__build_string__ = 'v4.7.8_Sat Dec 13 22:08:55 2025 +0000'
__django_version__ = '4.2'
__author__ = 'Roberto Rosario'
__author_email__ = 'roberto.rosario@mayan-edms.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'GPL 2.0'
__copyright_short__ = '2025 Roberto Rosario'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.mayan-edms.com'
