### COLUMN NAMES ###
# Provided in this file are dicts to standardize column names as necessary #

def col_map():
    return {
        'schedule':{
            'season':'season',
            'id':'game_id',
            'game_title':'game_title',
            'game_date':'game_date',
            'gameType':'season_type',
            'neutralSite':'neutral_site',
            'startTimeUTC':'start_time_utc',
            'start_time_est':'start_time_est',
            'easternUTCOffset':'eastern_utc',
            'venueUTCOffset':'venue_utc',
            'venueTimezone':'venue_timezone',
            'gameState':'game_state',
            'gameScheduleState':'game_schedule_state',
            'tvBroadcasts':'tv_broadcasts',
            'threeMinRecap':'three_min_recap',
            'threeMinRecapFr':'three_min_recap_fr',
            'condensedGame':'condensed_game',
            'condensedGameFr':'condensed_game_fr',
            'gameCenterLink':'gamecenter_link',
            'venue.default':'venue',
            'awayTeam.id':'away_team_id',
            'homeTeam.id':'home_team_id',
            'awayTeam.abbrev':'away_team_abbr',
            'homeTeam.abbrev':'home_team_abbr',
            'awayTeam.logo':'away_team_logo',
            'homeTeam.logo':'home_team_logo',
            'awayTeam.awaySplitSquad':'away_team_split_squad',
            'homeTeam.homeSplitSquad':'home_team_split_squad',
            'awayTeam.score':'away_score',
            'homeTeam.score':'home_score',
            'periodDescriptor.number':'period',
            'periodDescriptor.maxRegulationPeriods':'period_max_regulation',
            'periodDescriptor.periodType':'period_type',
            'gameOutcome.lastPeriodType':'period_type_last',
            'gameOutcome.otPeriods':'ot_periods',
            'seriesUrl':'series_url',
            'seriesStatus.round':'series_round',
            'seriesStatus.seriesAbbrev':'series_abbr',
            'seriesStatus.seriesTitle':'series_name',
            'seriesStatus.seriesLetter':'series_letter',
            'seriesStatus.neededToWin':'series_games_needed_to_win',
            'seriesStatus.gameNumberOfSeries':'series_game_num',
            'seriesStatus.topSeedTeamAbbrev':'top_seed_team_abbr',
            'seriesStatus.bottomSeedTeamAbbrev':'bottom_seed_team_abbr',
            'seriesStatus.topSeedWins':'top_seed_wins',
            'seriesStatus.bottomSeedWins':'bottom_seed_wins',
            'clock.timeRemaining':'period_time_remaining',
            'clock.secondsRemaining':'period_seconds_remaining',
            'clock.running':'period_clock_running',
            'clock.inIntermission':'game_in_intermission'
        },
        'season_info':{
            'id':'season',
            'formattedSeasonId':'season_name',
            'seasonOrdinal':'season_ordinal',
            'startDate':'start_date',
            'endDate':'end_date',
            'numberOfGames':'games_num',
            'totalRegularSeasonGames':'regular_season_total_games_num',
            'totalPlayoffGames':'playoffs_total_games_num',
            'regularSeasonStartDate':'regular_season_start_date',
            'regularSeasonEndDate':'regular_season_end_date',
            'standingsStart':'standings_start_date',
            'standingsEnd':'standings_end_date',
            'allStarGameInUse':'all_star_game',
            'conferencesInUse':'conferences',
            'divisionsInUse':'divisions',
            'wildcardInUse':'wildcard',
            'entryDraftInUse':'entry_draft',
            'nhlStanleyCupOwner':'nhl_stanley_cup_owner',
            'olympicsParticipation':'olympic_participation',
            'tiesInUse':'ties',
            'pointForOTLossInUse':'ot_loss_point',
            'regulationWinsInUse':'reg_wins',
            'rowInUse':'row',
            'supplementalDraftInUse':'supplemental_draft'
        },
        'standings':{
            "clinchIndicator": "clinch_indicator",
            "conferenceAbbrev": "conference_abbr",
            "conferenceHomeSequence": "conference_home_sequence",
            "conferenceL10Sequence": "conference_l10_sequence",
            "conferenceName": "conference_name",
            "conferenceRoadSequence": "conference_road_sequence",
            "conferenceSequence": "conference_sequence",
            "date": "date",
            "divisionAbbrev": "division_abbr",
            "divisionHomeSequence": "division_home_sequence",
            "divisionL10Sequence": "division_l10_sequence",
            "divisionName": "division_name",
            "divisionRoadSequence": "division_road_sequence",
            "divisionSequence": "division_sequence",
            "gameTypeId": "game_type_id",
            "gamesPlayed": "GP",
            "goalDifferential": "GD",
            "goalDifferentialPctg": "GD%",
            "goalAgainst": "GA",
            "goalFor": "GF",
            "goalsForPctg": "GF%",
            "homeGamesPlayed": "HGP",
            "homeGoalDifferential": "HGD",
            "homeGoalsAgainst": "HGA",
            "homeGoalsFor": "HGF",
            "homeLosses": "HL",
            "homeOtLosses": "HOL",
            "homePoints": "HPTS",
            "homeRegulationPlusOtWins": "HROW",
            "homeRegulationWins": "HRW",
            "homeTies": "HT",
            "homeWins": "HW",
            "l10GamesPlayed": "l10_GP",
            "l10GoalDifferential": "l10_GD",
            "l10GoalsAgainst": "l10_GA",
            "l10GoalsFor": "l10_GF",
            "l10Losses": "l10_L",
            "l10OtLosses": "l10_OTL",
            "l10Points": "l10_PTS",
            "l10RegulationPlusOtWins": "l10_ROW",
            "l10RegulationWins": "l10_RW",
            "l10Ties": "l10_T",
            "l10Wins": "l10_W",
            "leagueHomeSequence": "league_home_sequence",
            "leagueL10Sequence": "league_l10_sequence",
            "leagueRoadSequence": "league_road_sequence",
            "leagueSequence": "league_sequence",
            "losses": "L",
            "otLosses": "OTL",
            "pointPctg": "PTS%",
            "points": "PTS",
            "regulationPlusOtWinPctg": "ROW%",
            "regulationPlusOtWins": "ROW",
            "regulationWinPctg": "RW%",
            "regulationWins": "RW",
            "roadGamesPlayed": "AGP",
            "roadGoalDifferential": "AGD",
            "roadGoalsAgainst": "AGA",
            "roadGoalsFor": "AGF",
            "roadLosses": "AL",
            "roadOtLosses": "AOTL",
            "roadPoints": "APTS",
            "roadRegulationPlusOtWins": "AROW",
            "roadRegulationWins": "ARW",
            "roadTies": "AT",
            "roadWins": "AW",
            "seasonId": "season",
            "shootoutLosses": "SOL",
            "shootoutWins": "SOW",
            "streakCode": "streak_code",
            "streakCount": "streak_count",
            "teamLogo": "team_logo",
            "ties": "T",
            "waiversSequence": "waivers_sequence",
            "wildcardSequence": "wildcard_sequence",
            "winPctg": "W%",
            "wins": "W",
            "placeName.default": "place_name",
            "teamName.default": "team_name",
            "teamCommonName.default": "team_common_name",
            "teamAbbrev.default": "team_abbr",
            "seriesUrl": "series_url",
            "seriesTitle": "series_title",
            "seriesAbbrev": "series_abbrev",
            "seriesLetter": "series_letter",
            "playoffRound": "playoff_round",
            "topSeedRank": "top_seed_rank",
            "topSeedRankAbbrev": "top_seed_rank_abbr",
            "topSeedWins": "top_seed_wins",
            "bottomSeedRank": "bottom_seed_rank",
            "bottomSeedRankAbbrev": "bottom_seed_rank_abbr",
            "bottomSeedWins": "bottom_seed_wins",
            "winningTeamId": "winning_team_id",
            "losingTeamId": "losing_team_id",
            "topSeedTeam.id": "top_seed_team_id",
            "topSeedTeam.abbrev": "top_seed_team_abbr",
            "topSeedTeam.name.default": "top_seed_team_name",
            "topSeedTeam.commonName.default": "top_seed_team_common_name",
            "topSeedTeam.placeNameWithPreposition.default": "top_seed_team_place_name",
            "topSeedTeam.logo": "top_seed_team_logo",
            "topSeedTeam.darkLogo": "top_seed_team_dark_logo",
            "bottomSeedTeam.id": "bottom_seed_team_id",
            "bottomSeedTeam.abbrev": "bottom_seed_team_abbr",
            "bottomSeedTeam.name.default": "bottom_seed_team_name",
            "bottomSeedTeam.commonName.default": "bottom_seed_team_common_name",
            "bottomSeedTeam.placeNameWithPreposition.default": "bottom_seed_team_place_name",
            "bottomSeedTeam.logo": "bottom_seed_team_logo",
            "bottomSeedTeam.darkLogo": "bottom_seed_team_dark_logo",
            "seriesLogo": "series_logo",
        },
        'roster':{
            "id": "player_id",
            "team_abbr": "team_abbr",
            "season": "season",
            "headshot": "headshot",
            "sweaterNumber": "sweater_number",
            "positionCode": "position",
            "heading_position": "heading_position",
            "shootsCatches": "handedness",
            "heightInInches": "height_in",
            "weightInPounds": "weight_lbs",
            "heightInCentimeters": "height_cm",
            "weightInKilograms": "weight_kg",
            "birthDate": "birth_date",
            "birthCountry": "birth_country",
            "player_name":"player_name",
            "firstName.default": "player_first_name",
            "lastName.default": "player_last_name",
            "birthCity.default": "birth_city",
            "birthStateProvince.default": "birth_state_province"
            },
        'prospects':{
            "id": "player_id",
            "headshot": "headshot",
            "sweaterNumber": "sweater_number",
            "positionCode": "position",
            "shootsCatches": "handedness",
            "heightInInches": "height_in",
            "weightInPounds": "weight_lbs",
            "heightInCentimeters": "height_cm",
            "weightInKilograms": "weight_kg",
            "birthDate": "birth_date",
            "birthCountry": "birth_country",
            "player_name":"player_name",
            "firstName.default": "player_first_name",
            "lastName.default": "player_last_name",
            "birthCity.default": "birth_city",
            "birthStateProvince.default": "birth_state_province",
        },
        'player_info':{
            'playerId': 'player_id',
            'player_name': 'player_name',
            'isActive': 'is_active',
            'currentTeamId': 'current_team_id',
            'currentTeamAbbrev': 'current_team_abbr',
            'badges': 'badges',
            'teamLogo': 'team_logo',
            'sweaterNumber': 'sweater_number',
            'position': 'position',
            'headshot': 'headshot',
            'heroImage': 'hero_image',
            'heightInInches': 'height_in',
            'heightInCentimeters': 'height_cm',
            'weightInPounds': 'weight_lbs',
            'weightInKilograms': 'weight_kg',
            'birthDate': 'birth_date',
            'birthCountry': 'birth_country',
            'shootsCatches': 'handedness',
            'playerSlug': 'player_slug',
            'inTop100AllTime': 'in_top_100_all_time',
            'inHHOF': 'in_hhof',
            'shopLink': 'shop_link',
            'twitterLink': 'twitter_link',
            'watchLink': 'watch_link',
            'last5Games': 'last_5_games',
            'seasonTotals': 'season_totals',
            'awards': 'awards',
            'currentTeamRoster': 'current_team_roster',
            'fullTeamName.default': 'full_team_name',
            'teamCommonName.default': 'team_common_name',
            'teamPlaceNameWithPreposition.default': 'team_place_name_with_preposition',
            'firstName.default': 'player_first_name',
            'lastName.default': 'player_last_name',
            'birthCity.default': 'birth_city',
            'birthStateProvince.default': 'birth_state_province',
            'draftDetails.year': 'draft_year',
            'draftDetails.teamAbbrev': 'draft_team_abbr',
            'draftDetails.round': 'draft_round',
            'draftDetails.pickInRound': 'draft_pick_in_round',
            'draftDetails.overallPick': 'draft_overall_pick',
        },
        'team_info':{
            "id":"team_id",
            "franchiseId":"franchise_id",
            "fullName":"team_name",
            "leagueId":"league_id",
            "triCode":"team_abbr",
            "logo_light":"logo_light",
            "logo_dark":"logo_dark",
            "country3Code":"country_abbr",
            "countryCode":"country_abbr_2",
            "countryName":"country_name",
            "hasPlayerStats":"has_player_stats",
            "imageUrl":"country_flag_large",
            "isActive":"is_active",
            "nationalityName":"nationality",
            "olympicUrl":"olympic_url",
            "thumbnailUrl":"thumbnail_url"
        },
        'draft_rankings':{
            "id": "player_id",
            "player_name":"player_name",
            "firstName": "player_first_name",
            "lastName": "player_last_name",
            "headshot": "headshot",
            "sweaterNumber": "sweater_number",
            "positionCode": "position",
            "shootsCatches": "handedness",
            "heightInInches": "height_in",
            "weightInPounds": "weight_lbs",
            "heightInCentimeters": "height_cm",
            "weightInKilograms": "weight_kg",
            "birthDate": "birth_date",
            "birthCity": "birth_city",
            "birthCountry": "birth_country",
            "birthStateProvince": "birth_state_province",
            "lastAmateurClub": "last_amateur_club",
            "lastAmateurLeague": "last_amateur_league",
            "midtermRank":"midterm_rank",
            "finalRank":"final_rank"
        }
    }