from _typeshed import Incomplete
from minjiang_client.plugin.plugin_register import plugin_register as plugin_register
from typing import Any

class UtilityServerManager:
    servers: Incomplete
    port_pool: Incomplete
    used_ports: Incomplete
    lock: Incomplete
    monitor_thread: Incomplete
    running: bool
    utility_registry: Incomplete
    def __init__(self) -> None: ...
    def refresh_utility_registry(self) -> None: ...
    def start_utility_server(self, group_name: str, utility_name: str, utility_config: dict, utility_module_path: str = None) -> dict: ...
    def stop_utility_server(self, server_id: str) -> bool: ...
    def list_utility_servers(self) -> list[dict]: ...
    def list_all_running_utilities_grouped(self) -> dict[str, Any]: ...
    def get_utilities_without_group_name(self) -> list[dict]: ...
    def get_utilities_with_group_name(self, group_name: str) -> list[dict]: ...
    def cleanup_all_servers(self) -> None: ...

utility_manager: Incomplete
