"""
OpenGeode-GeosciencesIO Python binding for model
"""
from __future__ import annotations
import opengeode.lib64.opengeode_py_mesh
import opengeode.lib64.opengeode_py_model
import opengeode_geosciences.lib64.opengeode_geosciences_py_explicit
__all__: list[str] = ['BRepGeosExporter', 'GeosciencesIOModelLibrary', 'StructuralModelGeosExporter']
class BRepGeosExporter:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep, arg1: str) -> None:
        ...
    def add_cell_property_1d(self, arg0: str) -> None:
        ...
    def add_cell_property_2d(self, arg0: str) -> None:
        ...
    def add_cell_property_3d(self, arg0: str) -> None:
        ...
    def add_well_perforations(self, arg0: opengeode.lib64.opengeode_py_mesh.PointSet3D) -> None:
        ...
    def run(self) -> None:
        ...
class GeosciencesIOModelLibrary:
    @staticmethod
    def initialize() -> None:
        ...
class StructuralModelGeosExporter:
    def __init__(self, arg0: opengeode_geosciences.lib64.opengeode_geosciences_py_explicit.StructuralModel, arg1: str) -> None:
        ...
    def add_cell_property_1d(self, arg0: str) -> None:
        ...
    def add_cell_property_2d(self, arg0: str) -> None:
        ...
    def add_cell_property_3d(self, arg0: str) -> None:
        ...
    def add_well_perforations(self, arg0: opengeode.lib64.opengeode_py_mesh.PointSet3D) -> None:
        ...
    def run(self) -> None:
        ...
