"""Error codes enumeration for document processing operations."""

from enum import Enum


class ErrorCode(Enum):
    """Standard error codes for document processing operations."""

    # General processing errors
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"

    # Document extraction errors
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_CORRUPTED = "DOCUMENT_CORRUPTED"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    MEMORY_EXCEEDED = "MEMORY_EXCEEDED"

    # Network-related errors
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    NETWORK_CONNECTION_FAILED = "NETWORK_CONNECTION_FAILED"
    DOWNLOAD_SIZE_EXCEEDED = "DOWNLOAD_SIZE_EXCEEDED"
    HTTP_ERROR = "HTTP_ERROR"

    # Validation errors
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    CONTENT_VALIDATION_FAILED = "CONTENT_VALIDATION_FAILED"
    TYPE_VALIDATION_FAILED = "TYPE_VALIDATION_FAILED"

    # Engine-specific errors
    ENGINE_NOT_FOUND = "ENGINE_NOT_FOUND"
    ENGINE_INITIALIZATION_FAILED = "ENGINE_INITIALIZATION_FAILED"
    ENGINE_EXECUTION_FAILED = "ENGINE_EXECUTION_FAILED"
