from datetime import date
from typing import Any

class Formates:
    @staticmethod
    def fInt(value: Any) -> tuple[bool, int | None]: ...
    @staticmethod
    def fFloat(value: Any) -> tuple[bool, float | None]: ...
    @staticmethod
    def fBool(value: Any) -> tuple[bool, bool | None]: ...
    @staticmethod
    def fDate(value: Any, fmt: str = '%Y-%m-%d') -> tuple[bool, date | None]: ...
    @staticmethod
    def fEnum(value: Any, choices: set[str] | list[str]) -> tuple[bool, str | None]: ...
    @staticmethod
    def fJSON(value: Any) -> tuple[bool, dict | None]: ...
