import logging
import logging.handlers
from _typeshed import Incomplete
from pathlib import Path
from rich.console import Console

LogOutputMode: Incomplete
ColorSysMode: Incomplete
RotationMode: Incomplete
TimeInterval: Incomplete

class CustomRotatingFileHandler(logging.handlers.RotatingFileHandler):
    stream: Incomplete
    def doRollover(self) -> None: ...

class CustomTimedRotatingFileHandler(logging.handlers.TimedRotatingFileHandler):
    suffix: str
    extMatch: Incomplete
    def __init__(self, filename, when: str = 'h', interval: int = 1, backupCount: int = 0, encoding=None, delay: bool = False, utc: bool = False) -> None: ...
    stream: Incomplete
    rolloverAt: Incomplete
    def doRollover(self) -> None: ...

class Logger:
    DEBUG: Incomplete
    INFO: Incomplete
    WARNING: Incomplete
    ERROR: Incomplete
    CRITICAL: Incomplete
    def __new__(cls, log_dir: str | Path = './logs', filename_prefix: str = '', level_console: int = ..., level_file: int = ..., rotation_mode: RotationMode = 'none', rotation_interval: TimeInterval = 'day', rotation_size: int = ..., color_system: ColorSysMode = 'auto', *args, **kwargs): ...
    def get_logger(self) -> logging.Logger: ...
    def get_console(self) -> Console: ...
    def get_log_file_path(self) -> Path: ...
    def get_rotation_mode(self) -> RotationMode: ...
    def debug(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def info(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def warning(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def error(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def critical(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', **kwargs): ...
    def exception(self, *messages, output: LogOutputMode = 'both', sep: str = ' ', exc_info: bool = True, **kwargs): ...
