# coding: utf-8

"""
    Pingera API

     The official API for Pingera, a monitoring and status page platform. This API allows you to manage checks, organizations, incidents, and more.   Some useful links: * [Pingera website](https://pingera.ru?utm_source=api_docs) * [API documentation](https://docs.pingera.ru/api/overview) * [Application](https://app.pingera.ru) * [Status page](https://status.pingera.ru) 

    The version of the OpenAPI document: v1
    Contact: privet@pingera.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pingera.models.check_server import CheckServer

class TestCheckServer(unittest.TestCase):
    """CheckServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckServer:
        """Test CheckServer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckServer`
        """
        model = CheckServer()
        if include_optional:
            return CheckServer(
                server_metadata = {"datacenter":"aws-oregon","provider":"aws"},
                ip_address = '192.168.1.100',
                country = 'United States',
                id = 'srv123abc456',
                region = 'us-west-1'
            )
        else:
            return CheckServer(
        )
        """

    def testCheckServer(self):
        """Test CheckServer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
