# coding: utf-8

"""
    Pingera API

     The official API for Pingera, a monitoring and status page platform. This API allows you to manage checks, organizations, incidents, and more.   Some useful links: * [Pingera website](https://pingera.ru?utm_source=api_docs) * [API documentation](https://docs.pingera.ru/api/overview) * [Application](https://app.pingera.ru) * [Status page](https://status.pingera.ru) 

    The version of the OpenAPI document: v1
    Contact: privet@pingera.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pingera.models.password_verification_response import PasswordVerificationResponse

class TestPasswordVerificationResponse(unittest.TestCase):
    """PasswordVerificationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasswordVerificationResponse:
        """Test PasswordVerificationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasswordVerificationResponse`
        """
        model = PasswordVerificationResponse()
        if include_optional:
            return PasswordVerificationResponse(
                password_name = 'VIP Access',
                token_type = 'Bearer',
                expires_in = 3600,
                access_token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...'
            )
        else:
            return PasswordVerificationResponse(
        )
        """

    def testPasswordVerificationResponse(self):
        """Test PasswordVerificationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
