from typing import Any

from plotly.basedatatypes import BaseLayoutHierarchyType as _BaseLayoutHierarchyType

class Line(_BaseLayoutHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def color(self) -> str | None: ...
    @color.setter
    def color(self, val: str | None) -> None: ...
    @property
    def dash(self) -> str | None: ...
    @dash.setter
    def dash(self, val: str | None) -> None: ...
    @property
    def width(self) -> int | float | None: ...
    @width.setter
    def width(self, val: int | float | None) -> None: ...
    def __init__(
        self,
        arg: Line | dict[str, Any] | None = ...,
        color: str | None = ...,
        dash: str | None = ...,
        width: int | float | None = ...,
        **kwargs: Any,
    ) -> None: ...
