# -------------------------------------------------------------------
# This file was auto-generated. Do not edit directly.
# Generated by: StageGeneratorV2
# -------------------------------------------------------------------

"""This module defines the Column Generator stage."""

from ibm_watsonx_data_integration.services.datastage.models.flow.dag import StageNode
from ibm_watsonx_data_integration.services.datastage.models.stage_models.column_generator import column_generator
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ibm_watsonx_data_integration.services.datastage.models.flow.dag import DAG


class ColumnGeneratorStage(StageNode):
    """This class defines the Column Generator stage."""

    def __init__(self, dag: "DAG", configuration: column_generator = None, *, label: str = None) -> None:
        """Initializes an instance of a Column Generator stage."""
        super().__init__(dag, configuration=configuration, label=label)
        self.configuration: column_generator = configuration or column_generator()
