# Generated by Django 5.1.7 on 2025-04-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0016_alter_enaptemplatev1_suap_courses"),
        ("enap_designsystem", "0028_onlycards_course_intro_topics"),
    ]

    operations = []
