# coding: utf-8

"""
    Pingera API

     The official API for Pingera, a monitoring and status page platform. This API allows you to manage checks, organizations, incidents, and more.   Some useful links: * [Pingera website](https://pingera.ru?utm_source=api_docs) * [API documentation](https://docs.pingera.ru/api/overview) * [Application](https://app.pingera.ru) * [Status page](https://status.pingera.ru) 

    The version of the OpenAPI document: v1
    Contact: privet@pingera.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ExecutionGroupStatistics(BaseModel):
    """
    ExecutionGroupStatistics
    """ # noqa: E501
    completed_executions: Optional[StrictInt] = Field(default=None, description="Number of completed executions")
    max_response_time: Optional[StrictInt] = Field(default=None, description="Slowest response time across regions in milliseconds")
    failed_executions: Optional[StrictInt] = Field(default=None, description="Number of failed executions")
    total_executions: Optional[StrictInt] = Field(default=None, description="Total number of regional executions expected")
    avg_response_time: Optional[StrictInt] = Field(default=None, description="Average response time across all regions in milliseconds")
    min_response_time: Optional[StrictInt] = Field(default=None, description="Fastest response time across regions in milliseconds")
    __properties: ClassVar[List[str]] = ["completed_executions", "max_response_time", "failed_executions", "total_executions", "avg_response_time", "min_response_time"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutionGroupStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_response_time (nullable) is None
        # and model_fields_set contains the field
        if self.max_response_time is None and "max_response_time" in self.model_fields_set:
            _dict['max_response_time'] = None

        # set to None if avg_response_time (nullable) is None
        # and model_fields_set contains the field
        if self.avg_response_time is None and "avg_response_time" in self.model_fields_set:
            _dict['avg_response_time'] = None

        # set to None if min_response_time (nullable) is None
        # and model_fields_set contains the field
        if self.min_response_time is None and "min_response_time" in self.model_fields_set:
            _dict['min_response_time'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutionGroupStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completed_executions": obj.get("completed_executions"),
            "max_response_time": obj.get("max_response_time"),
            "failed_executions": obj.get("failed_executions"),
            "total_executions": obj.get("total_executions"),
            "avg_response_time": obj.get("avg_response_time"),
            "min_response_time": obj.get("min_response_time")
        })
        return _obj


