# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist, validator
from alexasomba_paystack.models.order_items import OrderItems
from alexasomba_paystack.models.order_shipping import OrderShipping

class OrderCreate(BaseModel):
    """
    OrderCreate
    """
    email: StrictStr = Field(..., description="The email of the customer placing the order")
    first_name: StrictStr = Field(..., description="The customer's first name")
    last_name: StrictStr = Field(..., description="The customer's last name")
    phone: StrictStr = Field(..., description="The customer's mobile number")
    currency: StrictStr = Field(..., description="Currency in which amount is set")
    items: conlist(OrderItems) = Field(...)
    shipping: OrderShipping = Field(...)
    is_gift: Optional[StrictBool] = Field(None, description="A flag to indicate if the order is for someone else")
    pay_for_me: Optional[StrictBool] = Field(None, description="A flag to indicate if the someone else should pay for the order")
    __properties = ["email", "first_name", "last_name", "phone", "currency", "items", "shipping", "is_gift", "pay_for_me"]

    @validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('GHS', 'KES', 'NGN', 'USD', 'ZAR'):
            raise ValueError("must be one of enum values ('GHS', 'KES', 'NGN', 'USD', 'ZAR')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OrderCreate:
        """Create an instance of OrderCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of shipping
        if self.shipping:
            _dict['shipping'] = self.shipping.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OrderCreate:
        """Create an instance of OrderCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OrderCreate.parse_obj(obj)

        _obj = OrderCreate.parse_obj({
            "email": obj.get("email"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "phone": obj.get("phone"),
            "currency": obj.get("currency"),
            "items": [OrderItems.from_dict(_item) for _item in obj.get("items")] if obj.get("items") is not None else None,
            "shipping": OrderShipping.from_dict(obj.get("shipping")) if obj.get("shipping") is not None else None,
            "is_gift": obj.get("is_gift"),
            "pay_for_me": obj.get("pay_for_me")
        })
        return _obj


