import boto3

__version__: str
__application__: str

def add_propagation(client: boto3.client, transit_gateway_route_table_id: str, transit_gateway_attachment_id: str) -> dict: ...
def add_static_route(client: boto3.client, transit_gateway_route_table_id: str, transit_gateway_attachment_id: str, destination_cidr_block: str) -> dict: ...
def main(access_key_id: str | None = ..., secret_access_key: str | None = ..., session_token: str | None = ..., region_name: str | None = ..., routes: list[dict] = []) -> None: ...
