"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from builtins import (
    float,
    int,
)

from google.protobuf.descriptor import (
    Descriptor,
    FileDescriptor,
)

from google.protobuf.message import (
    Message,
)

from typing import (
    Text,
)

from typing_extensions import (
    Literal,
)


DESCRIPTOR: FileDescriptor = ...

class GetEntrustableVolumeBySymbolReq(Message):
    DESCRIPTOR: Descriptor = ...
    ACCOUNT_ID_FIELD_NUMBER: int
    ACCOUNT_NAME_FIELD_NUMBER: int
    CHANNEL_ID_FIELD_NUMBER: int
    SYMBOL_FIELD_NUMBER: int
    PRICE_FIELD_NUMBER: int
    ORDER_BUSINESS_FIELD_NUMBER: int
    ORDER_TYPE_FIELD_NUMBER: int
    RID_FIELD_NUMBER: int
    account_id: Text = ...
    """账户ID"""

    account_name: Text = ...
    """资金账户"""

    channel_id: Text = ...
    """交易通道id"""

    symbol: Text = ...
    """symbol"""

    price: float = ...
    """委托价格"""

    order_business: int = ...
    """委托业务属性"""

    order_type: int = ...
    """委托类型"""

    rid: Text = ...
    """请求ID, 唯一标识本次请求"""

    def __init__(self,
        *,
        account_id : Text = ...,
        account_name : Text = ...,
        channel_id : Text = ...,
        symbol : Text = ...,
        price : float = ...,
        order_business : int = ...,
        order_type : int = ...,
        rid : Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: Literal[u"account_id",b"account_id",u"account_name",b"account_name",u"channel_id",b"channel_id",u"order_business",b"order_business",u"order_type",b"order_type",u"price",b"price",u"rid",b"rid",u"symbol",b"symbol"]) -> None: ...

class GetEntrustableVolumeBySymbolRsp(Message):
    DESCRIPTOR: Descriptor = ...
    ACCOUNT_ID_FIELD_NUMBER: int
    ACCOUNT_NAME_FIELD_NUMBER: int
    CHANNEL_ID_FIELD_NUMBER: int
    MAX_ENTRUSTABLE_VOLUME_FIELD_NUMBER: int
    AVAILABLE_VOLUME_FIELD_NUMBER: int
    MARGIN_PER_UNIT_FIELD_NUMBER: int
    RID_FIELD_NUMBER: int
    account_id: Text = ...
    """账户ID"""

    account_name: Text = ...
    """资金账户"""

    channel_id: Text = ...
    """交易通道id"""

    max_entrustable_volume: int = ...
    """最大可委托数量"""

    available_volume: int = ...
    """可用数量"""

    margin_per_unit: float = ...
    """单位保证金 当卖出开仓时，margin_per_unit为卖开1张预估的占用保证金，其余情况下为0"""

    rid: Text = ...
    """请求ID, 唯一标识本次请求"""

    def __init__(self,
        *,
        account_id : Text = ...,
        account_name : Text = ...,
        channel_id : Text = ...,
        max_entrustable_volume : int = ...,
        available_volume : int = ...,
        margin_per_unit : float = ...,
        rid : Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: Literal[u"account_id",b"account_id",u"account_name",b"account_name",u"available_volume",b"available_volume",u"channel_id",b"channel_id",u"margin_per_unit",b"margin_per_unit",u"max_entrustable_volume",b"max_entrustable_volume",u"rid",b"rid"]) -> None: ...
