from plotly.graph_objs import (
    # AngularAxis,
    # Annotation,
    # Annotations,
    Bar,
    Barpolar,
    Box,
    Candlestick,
    Carpet,
    Choropleth,
    Choroplethmap,
    Choroplethmapbox,
    # ColorBar,
    Cone,
    Contour,
    Contourcarpet,
    # Contours,
    # Data,
    Densitymap,
    Densitymapbox,
    # ErrorX,
    # ErrorY,
    # ErrorZ,
    Figure,
    # Font,
    Frame,
    # Frames,
    Funnel,
    Funnelarea,
    Heatmap,
    Histogram,
    Histogram2d,
    Histogram2dContour,
    # Histogram2dcontour,
    Icicle,
    Image,
    Indicator,
    Isosurface,
    Layout,
    # Legend,
    # Line,
    # Margin,
    # Marker,
    Mesh3d,
    Ohlc,
    Parcats,
    Parcoords,
    Pie,
    # RadialAxis,
    Sankey,
    Scatter,
    Scatter3d,
    Scattercarpet,
    Scattergeo,
    Scattergl,
    Scattermap,
    Scattermapbox,
    Scatterpolar,
    Scatterpolargl,
    Scattersmith,
    Scatterternary,
    # Scene,
    Splom,
    # Stream,
    Streamtube,
    Sunburst,
    Surface,
    Table,
    # Trace,
    Treemap,
    Violin,
    Volume,
    Waterfall,
    # XAxis,
    # XBins,
    # YAxis,
    # YBins,
    # ZAxis,
    bar,
    barpolar,
    box,
    candlestick,
    carpet,
    choropleth,
    choroplethmap,
    choroplethmapbox,
    cone,
    contour,
    contourcarpet,
    densitymap,
    densitymapbox,
    funnel,
    funnelarea,
    heatmap,
    histogram,
    histogram2d,
    histogram2dcontour,
    icicle,
    image,
    indicator,
    isosurface,
    layout,
    mesh3d,
    ohlc,
    parcats,
    parcoords,
    pie,
    sankey,
    scatter,
    scatter3d,
    scattercarpet,
    scattergeo,
    scattergl,
    scattermap,
    scattermapbox,
    scatterpolar,
    scatterpolargl,
    scattersmith,
    scatterternary,
    splom,
    streamtube,
    sunburst,
    surface,
    table,
    treemap,
    violin,
    volume,
    waterfall,
)

__all__ = [
    # "AngularAxis",
    # "Annotation",
    # "Annotations",
    "Bar",
    "Barpolar",
    "Box",
    "Candlestick",
    "Carpet",
    "Choropleth",
    "Choroplethmap",
    "Choroplethmapbox",
    # "ColorBar",
    "Cone",
    "Contour",
    "Contourcarpet",
    # "Contours",
    # "Data",
    "Densitymap",
    "Densitymapbox",
    # "ErrorX",
    # "ErrorY",
    # "ErrorZ",
    "Figure",
    # "Font",
    "Frame",
    # "Frames",
    "Funnel",
    "Funnelarea",
    "Heatmap",
    "Histogram",
    "Histogram2d",
    "Histogram2dContour",
    # "Histogram2dcontour",
    "Icicle",
    "Image",
    "Indicator",
    "Isosurface",
    "Layout",
    # "Legend",
    # "Line",
    # "Margin",
    # "Marker",
    "Mesh3d",
    "Ohlc",
    "Parcats",
    "Parcoords",
    "Pie",
    # "RadialAxis",
    "Sankey",
    "Scatter",
    "Scatter3d",
    "Scattercarpet",
    "Scattergeo",
    "Scattergl",
    "Scattermap",
    "Scattermapbox",
    "Scatterpolar",
    "Scatterpolargl",
    "Scattersmith",
    "Scatterternary",
    # "Scene",
    "Splom",
    # "Stream",
    "Streamtube",
    "Sunburst",
    "Surface",
    "Table",
    # "Trace",
    "Treemap",
    "Violin",
    "Volume",
    "Waterfall",
    # "XAxis",
    # "XBins",
    # "YAxis",
    # "YBins",
    # "ZAxis",
    "bar",
    "barpolar",
    "box",
    "candlestick",
    "carpet",
    "choropleth",
    "choroplethmap",
    "choroplethmapbox",
    "cone",
    "contour",
    "contourcarpet",
    "densitymap",
    "densitymapbox",
    "funnel",
    "funnelarea",
    "heatmap",
    "histogram",
    "histogram2d",
    "histogram2dcontour",
    "icicle",
    "image",
    "indicator",
    "isosurface",
    "layout",
    "mesh3d",
    "ohlc",
    "parcats",
    "parcoords",
    "pie",
    "sankey",
    "scatter",
    "scatter3d",
    "scattercarpet",
    "scattergeo",
    "scattergl",
    "scattermap",
    "scattermapbox",
    "scatterpolar",
    "scatterpolargl",
    "scattersmith",
    "scatterternary",
    "splom",
    "streamtube",
    "sunburst",
    "surface",
    "table",
    "treemap",
    "violin",
    "volume",
    "waterfall",
]
