import argparse
from . import Command as Command, register_command as register_command, validate_command_args as validate_command_args

class SelfCommand(Command):
    @property
    def name(self) -> str: ...
    @property
    def help(self) -> str: ...
    def add_arguments(self, parser: argparse.ArgumentParser) -> None: ...
    def execute(self, subcommand: str = 'update') -> None: ...
