"""Представления, предоставляемые пакетом."""

from django.http import HttpRequest, JsonResponse

def check_connection(_: HttpRequest) -> JsonResponse: ...
def dag(request: HttpRequest) -> JsonResponse: ...
def dag_run(request: HttpRequest) -> JsonResponse: ...
def ti_logs(request: HttpRequest) -> JsonResponse: ...
