from .Base import *
from .Proxy import *
from .AcadObject import *
from .Objects import *

class AcadEntity(AcadObject):
    def __init__(self, obj) -> None: ...
    EntityTransparency: AcEntityTransparency
    Hyperlinks: AcadHyperlinks
    Layer: str
    Linetype: str
    LinetypeScale: float
    Lineweight: AcLineWeight
    Material: str
    PlotStyleName: str
    TrueColor: AcadAcCmColor
    Visible: bool
    def ArrayPolar(self, NumberOfObjects: In[int], AngleToFill: In[float], CenterPoint: In[PyGePoint3d]) -> vObjectArray: ...
    def ArrayRectangular(self, NumberOfRows: In[int], NumberOfColumns: In[int], NumberOfLevels: In[int], DistBetweenRows: In[float], DistBetweenColumns: In[float], DistBetweenLevels: In[float]) -> vObjectArray: ...
    def Copy(self) -> AcadEntity: ...
    def GetBoundingBox(self) -> PyGePoint3dArray: ...
    def Highlight(self, HighlightFlag: In[bool]) -> None: ...
    def IntersectWith(self, IntersectObject: In[AcadEntity | AcadAttributeReference], ExtendOption: In[AcExtendOption]) -> PyGePoint3dArray: ...
    def Mirror(self, Point1: In[PyGePoint3d], Point2: In[PyGePoint3d]) -> AcadEntity: ...
    def Mirror3D(self, Point1: In[PyGePoint3d], Point2: In[PyGePoint3d], Point3: In[PyGePoint3d]) -> AcadEntity: ...
    def Move(self, Point1: In[PyGePoint3d], Point2: In[PyGePoint3d]) -> None: ...
    def Rotate(self, BasePoint: In[PyGePoint3d], RotationAngle: In[float]) -> None: ...
    def Rotate3D(self, Point1: In[PyGePoint3d], Point2: In[PyGePoint3d], RotationAngle: In[float]) -> None: ...
    def ScaleEntity(self, BasePoint: In[PyGePoint3d], ScaleFactor: In[float]) -> None: ...
    def TransformBy(self, TransformationMatrix: In[PyGeMatrix3d]) -> None: ...
    def Update(self) -> None: ...

class AcadSubEntity(AppObject):
    def __init__(self, obj) -> None: ...
    Color: AcColor
    Hyperlinks: AcadHyperlinks
    Layer: str
    Linetype: str
    LinetypeScale: float
    Lineweight: AcLineWeight
    ObjectName: str
    PlotStyleName: str
