from .filetype_detector import BizFileKind as BizFileKind, detect_file_type as detect_file_type
from pathlib import Path

def merge_text_files(source_files: list[str | Path], output_file: str | Path, separator: str = '\n', encoding: str = 'utf-8', overwrite: bool = False) -> Path: ...
def split_text_file(source_file: str | Path, marker: str, output_dir: str | Path | None = None, output_prefix: str = 'part', keep_marker: bool = True, strict: bool = False, encoding: str | None = None) -> list[Path]: ...
