from typing import Any

from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType

class Textfont(_BaseTraceHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def color(self) -> str | None: ...
    @color.setter
    def color(self, val: str | None) -> None: ...
    def __init__(
        self,
        arg: dict[str, Any] | Textfont = ...,
        color: str = ...,
        **kwargs: Any,
    ) -> None: ...
